### ISSUE TITLE
Metadata int/long inconsistency

### ISSUE THREAD

**Issue by DatBrick** [Vector35/binaryninja-api#1048]
Binary Ninja Version: 1.1.1212-dev, 154b07e5
Platform: Windows 10 (10.0)

While `store_metadata` supports `int` types, `query_metadata` returns them as `long` types. This means you can't re-store metadata which contains an integer without processing/fixing it first.

**Comment by plafosse** [comment]
This unfortunately is a limitation on python2. The only workaround for this would be to store additional metadata that is only useful to python2 and tells whether or not the integer is a long or not. The backing store is just a native `uint64_t`. There are other issues similar to this that we aren't going to try to create workarounds for such as big nums. Fortunately upcoming python 3 (coming very soon like this week hopefully) will address this issue since there is no difference between ints and longs in python 3. Thanks for the report.
