### ISSUE TITLE
__gmon_start__ not detected as an external

### ISSUE THREAD

**Issue by krx** [Vector35/binaryninja-api#1066]
Binary: [xz_amd64](https://github.com/trailofbits/mcsema/raw/binja_updates/tests/test_suite/amd64/linux/bin/xz_amd64)

The plt entry for `__gmon_start__` at `4023f0` gets defined as an internal function (`sub_4023f0`) instead of an external with the correct name.

There is a `__gmon_start__@GOT` defined at `60fff8`, but the plt stub instead refers to `610208` which is given a general `data_` symbol

**Comment by plafosse** [comment]
Sorry for the delay in addressing this issue. Any chance we can get that binary re-uploaded?

**Comment by curtis-w** [comment]
We found what looks like the same binary at https://github.com/trailofbits/mcsema/blob/master/tests/test_suite_generator/src/linux/xz_amd64/xz_amd64

**Comment by plafosse** [comment]
Looks like this was an issue with handling duplicate symbols in ELF files, essentially we just gave up if there were ever two. We now handle this condition for ELF files by appending a "_<number>" to the end of the symbol's "raw name". The short name and fullName remain the same. This issue is fixed in 1.1.1803
