### ISSUE TITLE
DataVariable identified incorrectly

### ISSUE THREAD

**Issue by kumarak** [Vector35/binaryninja-api#1087]
Looking to extract the global variables (with their references) and traversing through the list of `DataVariable`. I find instances where the struct global variables are split into the multiple variables. Is there a way to identify such cases? 
In apache binary, `httpd_version` variable is of size 24 but it is identified incorrectly.

<img width="435" alt="screen shot 2018-07-19 at 9 57 26 am" src="https://user-images.githubusercontent.com/1365912/42947051-720008d0-8b3a-11e8-9bc6-8a460cf2dff6.png">

The analysis is missing the indirect references of the variable in the function `ap_get_server_revision` where the reference of `httpd_version` is passed as the first argument. 

<img width="547" alt="screen shot 2018-07-19 at 10 02 32 am" src="https://user-images.githubusercontent.com/1365912/42947283-07134d06-8b3b-11e8-94b7-e7b2472c1b0e.png">

**Comment by psifertex** [comment]
We talked it over and it looks like this is more of a missing feature of automatic structure recovery rather than a fault of any of the current expected analysis. 

It's not, unfortunately, an easy fix or anything on our immediate timeline for fixing. Definitely a longer-term goal so we'll leave this issue open to track it (and rename the issue appropriately) but won't have a timeline for a fix any time soon unfortunately. 

Let me know if we're misunderstanding the issue.

**Comment by plafosse** [comment]
Closing this issue as we've not heard a response in months.
