### ISSUE TITLE
Add type annotations to the Python API

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1094]
See the [relevant section of PEP-484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) for python 2.7 compatibility.

**Comment by sum-catnip** [comment]
this is really underrated imo

adding this would make plugin development soooooooooo much easier. you would have full autocomplete to see all the functions and properties, you could easily nativate through the code via goto definition and all the goods your editor offers.
You wouldnt have to play the game of `what type does this thing return` then go into the binja terminal just to run `type` on it and search for that type in the binja documentation.

documentation would improve by alot because youd have links to the type something returns and dont have to play above mentioned game just to read documentation.

Also this may sounds like more effort than it actually is. Theres projects like [MonkeyType](https://pypi.org/project/MonkeyType/) (used along with [retype](https://pypi.org/project/retype/)) developed by facebook, used for instagram or [pyannotate](https://github.com/dropbox/pyannotate) from dropbox, which can add type annotations for python2 and 3 based on runtime information. Ofc those tools arent perfect by any means but its a really good starting point and can safe many hours of work.

Im not sure how one would go about applying those tools to an embedded python instance but if i figure something out ill make a pull request.

**Comment by plafosse** [comment]
Mostly done as of 2.4.2969
