### ISSUE TITLE
Allow edges to be selected and shown as such

### ISSUE THREAD

**Issue by SeanHeelan** [Vector35/binaryninja-api#1181]
This is a feature request I suppose (let me know if there's somewhere else I should be making these) =) In dense graphs it is often quite difficult to know for sure where an edge in the graph lands without double clicking on it. It would be very helpful if, on hover, the edge's thickness was increased or it was made easier to distinguish from other edges in some way. If this had the side effect of making edges easier to click on this would also be useful!

**Comment by psifertex** [comment]
Yup, this is the right place for features! 

That's a very good suggestion. We debated internally a bit whether stroke, color, or weight was the right hint but /some/ sort of visual hint would indeed be a good idea.

I'm holding off tagging it for 1.2 release for now even though we're putting many UI improvements there since it's a slightly larger change required to implement given the current architecture for that code. 

That said, we've already got plans at some point to re-work our existing disassembly graphs to use the new [flowgraph API](https://api.binary.ninja/binaryninja.flowgraph-module.html) and expand out the API to have more features (mainly around edges) so I expect that's where we'd end up implementing this if we do. If we do end up implementing that change in 1.2, this change would likely be included.

**Comment by psifertex** [comment]
Yup, this is a good spot for feature request. Already mentioned in slack, but this is a bit more work than I'd like given our current UI architecture so we'll probably revisit it after UI plugins and a bunch of other UI changes land to see how doable it is then.

**Comment by plafosse** [comment]
Added in v1.1.1596, additionally keyboard navigation works now and is quite nice for navigating dense graphs.
