### ISSUE TITLE
Crash on second flowgraph plugin call

### ISSUE THREAD

**Issue by mechanicalnull** [Vector35/binaryninja-api#1273]
Using the attached plugin to test out the flowgraph API, it causes binary ninja to segfault the second time I use the plugin (right click an MLIL var and select "Graph backward slice").

I've reproduced on multiple binaries and on builds 1.1.1500-dev and 1.1.1470.

[graph_slice.txt](https://github.com/Vector35/binaryninja-api/files/2845383/graph_slice.txt)

**Comment by psifertex** [comment]
Thanks for the report -- can you confirm whether this only happens in python3? 

We believe it's a garbage collection / object lifetime issue for callbacks. 

In the meantime, when a flowgraph object is created, you need to keep a reference to the callbacks in a global list to keep it from being collected and triggering the crash.

**Comment by mechanicalnull** [comment]
I encountered this while testing it with python 2.7, but just reproduced it under python 3.

**Comment by joshwatson** [comment]
Try moving the FlowGraph object's declaration to the global scope and see if it still happens. I believe there's a garbage collection issue with FlowGraph objects currently

**Comment by plafosse** [comment]
We've actually separately confirmed this, it doesn't seem to be a problem with the callbacks going out of scope.

**Comment by plafosse** [comment]
I can't seem to reproduce this issue any longer, it seems like it was fixed. Can you try to reproduce and confirm?

**Comment by plafosse** [comment]
Oh one of the API's changed so you'll need to change this bit of code

```
        defining_instructions = [
            function.get_ssa_var_definition(new_var).instr_index for
            new_var in instruction_to_visit.vars_read
            if function.get_ssa_var_definition(new_var) is not None
        ]
```

Not adding the ``.instr_index``

**Comment by plafosse** [comment]
Scratch that, we do have a repro now :P

**Comment by D0ntPanic** [comment]
The underlying issue is that nodes that are not part of the graph were able to be added as edges without any validation, which caused a crash during layout.

The plugin given here accidentally triggers this case by creating a `dict` object as a default value in a parameter list. This leads to a common bug in Python code where all calls to the function share the same `dict` object and thus have unexpected values present.

Fixed in build 1630. An exception is now generated if an invalid edge is added.
