### ISSUE TITLE
Value-set analysis through indirect global data references

### ISSUE THREAD

**Issue by devtty1er** [Vector35/binaryninja-api#1291]
Binary Ninja Version: 1.1.1535-dev, e4581019
Platform: macOS 10.14

The following jump table fails to analyze:

![https://imgur.com/Ie3relD](https://imgur.com/download/Ie3relD)
![https://imgur.com/8SEovLZ](https://imgur.com/download/8SEovLZ)

`jump_targets` is in `.rodata`.

[.bndb [/bin/cp]](https://www.dropbox.com/s/2v7x8ododpoobpn/cp.bndb?dl=0) @ `0x47fb`

**Comment by plafosse** [comment]
The link appears to be broken.

**Comment by devtty1er** [comment]
@plafosse Oops... fixed.

**Comment by plafosse** [comment]
The issue here is that the variable `data_1a0f0` is being constrained in global memory. It is possible (though not likely in this case) that the global memory in question is aliased by something else.  It would be actually incorrect for us to assume that between the check `[var] u> 6` and the use `rax_4 = zx([var])` that the memory being referenced hasn't changed. Unfortunately we don't have a good solution to this issue currently. In the future we hope to be able to provide two solutions: 1) The ability to easily specify the constraints manually, (this would allow the analysis to figure out the indirect jump targets). 2) Provide greater analysis analysis allowing us to under some circumstances to identify when a piece of global memory isn't likely to be aliased and thus we could allow the value set analysis to work as people would expect.

I'm going to change the title of this ticket to reflect the underlying issue.

**Comment by psifertex** [comment]
A full system to track this would require a huge refactor, going to tag this one as dependent on #281 as we think that's the right fix for situations like this.

**Comment by devtty1er** [comment]
This particular case was fixed with recent jump table improvements.
