### ISSUE TITLE
Wrong instruction length on thumb instruction set

### ISSUE THREAD

**Issue by valour01** [Vector35/binaryninja-api#1342]
Hello. I refer to the version Version 1.1.1470 (Build ID a3b48b43), which should be the latest version.

I noticed that the API `bv.get_instruction_length()` is not right on thumb instruction set. Below you could find the return value of the API and the corresponding GUI view.

This is a part of the assembly code.
![image](https://user-images.githubusercontent.com/5527468/57267419-acf90000-70b2-11e9-97d0-b65935630081.png)

However, with the instruction. The return value is below:
```
In [3]: bv.get_instruction_length(0x13270)
Out[3]: 4L

In [4]: bv.get_instruction_length(0x13272)
Out[4]: 0L

In [5]: bv.get_instruction_length(0x13274)
Out[5]: 4L

In [6]: bv.get_instruction_length(0x13276)
Out[6]: 0L

```

This is not right. You guys could check and reproduce it with any binary compiled in thumb mode. Many Thanks

**Comment by plafosse** [comment]
I think the API is working a little differently than you suspect it is. Its most likely that if you do `bv.arch` it will tell you its ARMv7 which does indeed have a 4 byte instruction length for all instructions.  Binary Ninja supports having an arbitrary number of active architectures within a single BinaryView, but by default it uses whatever one the entry point is specified as. `get_instruction_length` and others like it have parameter which you can pass to tell it which architecture is currently being analyzed. Since BinaryNinja also support multiple overlapping basic blocks of different architecture types it is not sufficient to just specify an address for us to know with certainty which architecture this address corresponds to. So doing something like `bv. get_instruction_length(0x13276, current_function.arch)` should get you what you're looking for.

**Comment by plafosse** [comment]
I believe this above comment answers the issue you're experiencing. If it doesn't please let us know and we can reopen it.
