### ISSUE TITLE
Mach-O Universal (FAT) binary support

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#135]
Blocking on "Container formats support #133"

**Comment by joshwatson** [comment]
I implemented something that *half* works so far: https://github.com/joshwatson/binaryninja-fat_macho

It works on the initial load, but I’ve got to diagnose what’s happening with opening a previously saved bndb. It reanalyzes it over again, and doesn’t save user actions (or at least doesn’t reapply them)

**Comment by CouleeApps** [comment]
Implemented in core as of build 1.1.1696

**Comment by jeffli678** [comment]
It seems the patching functionality is not working properly: the binary appears to be patched (in the view), however, when I save the binary, it is identical to the original one. Tested with a iOS fat binary that comes with both a armv7 and arm64 arch.

**Comment by bpotchik** [comment]
We currently have a regression with this item. Reopening until fixed.

**Comment by melomac** [comment]
Please note the "Go to" feature (G) doesn't work when in Graph View and with a FAT Mach-O file.

**Comment by melomac** [comment]
Double clicking an address in the log view doesn't work either.
Surprising, it works on the same address from the Tag view...

**Comment by bpotchik** [comment]
Fixed in 2.1.2295-dev.

There were several bugs/limitations with the previous Fat Mach-O BinaryViewType support. The old BinaryViewType with the architecture embedded in the type name is now deprecated. The new Universal BinaryViewType is available and it fixes rebasing, relocations, persistent file writes, and some navigation issues from html reports.

Open with options is supported with Universal Mach-O files and it's possible to select the object file within that dialog. Additionally, only one object file from the container is available to load/save in a BNDB.

Old BNDBs will continue to load, however none of the analysis data is migrated to the new view.
