### ISSUE TITLE
Search for keybinding by hotkey in keybindings ui

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#1350]
Would be nice to have the ability to search for keybindings by hotkey so you don't have to search manually.

**Comment by comex** [comment]
Search by command name would be useful, too.

**Comment by nshp** [comment]
@comex You can just start typing in the keybindings UI to filter by command name. It works just like other listings (the strings view, symbols, etc).

**Comment by psifertex** [comment]
Also, you can use the command-palette (CMD-p) to search for the action name and it shows the keybindings from there as well.

**Comment by psifertex** [comment]
I don't know that we're going to implement the search by keybinding feature so I'm going to close this one out for now. We might reconsider in the future, I just don't know if the extra feature of having to have a special. I did just enable the search box by default in the keybinding view (builds >= 2945) so that's no longer undiscoverable and you can sort by keybinding which makes finding a particular keybind pretty quickly. If anyone feels strongly that this isn't usable enough feel free to re-open.
