### ISSUE TITLE
High RAM usage until Crash

### ISSUE THREAD

**Issue by securitykitten** [Vector35/binaryninja-api#1352]
Binary Ninja Version: `1.1.1666-dev, f37efedc`
Platform: `openSUSE Tumbleweed`

When analyzing a file (11.5kb in size) with BinaryNinja, RAM usage grows until a crash.  In my use cases, it went as high as 20gb until the OS intervened. 

Analysis mode: full

Malware is attached (password: infected) 
[fef0d99aac2ec06961cf92a14e128e74e513084949b5a5b96c5e2d3a98570fb8.zip](https://github.com/Vector35/binaryninja-api/files/3208923/fef0d99aac2ec06961cf92a14e128e74e513084949b5a5b96c5e2d3a98570fb8.zip)

If there is any more information needed please let me know.  Thanks!

**Comment by psifertex** [comment]
Looks like the opaque predicate method this sample is using to insert garbage jumps into the disassembly is causing some worst-case performance problems. Unfortunately, our generic plugin (https://binary.ninja/2017/10/01/automated-opaque-predicate-removal.html) likely won't help a ton because some of the flag setting happens via function calls. That said, it does clean up some of them. 

While general improvements to our analysis engine might help, there's unfortunately lots of tricks that bad-performing malware can do to trigger pathological cases in all analysis tools. The good news is there are several work-arounds. 

The first and easiest is to simply use the triage plugin (if you're on the latest dev, it's already included in your install but just needs to be copied into your plugin folder to be enabled) and open it in a basic analysis mode. That limits the amount of analysis that attempts to run and makes BN not only much faster, but much more resistant to pathological cases at the cost of not lifting all functions to our higher levels of IL. 

The second method would be to open up the binary and enable some analysis limits on functions you'll find that you can keep BN from OOM'ing and crashing during analysis though, again, you won't have complete analysis for the worst behaving functions.

Once you've done that, you could probably write a quick script to scan for conditional branches and NOP them out in trivial cases where the destination is an obvious string (as was the case for a bunch when I just happened to look at it) and then you can save and re-open with the more full featured analysis enabled. 

So the short summary is unfortunately there are lots of ways to create worst-case analysis patterns and you can either include stricter limits on our analysis, modify the binary to remove the bad behaving functions.

Hope that helps.

**Comment by psifertex** [comment]
Actually, after poking at this a bit more I think there's something else going on causing our analysis to fail more than it should. Re-opening while I look a bit at it.

**Comment by bpotchik** [comment]
Thanks for providing an interesting binary. You can analyze this binary starting with 1.1.1775-dev, and in conjunction with a new setting: 'analysis.conservative.disallowBranchToString'. This adds some bumper guards which prevent analysis from spending too much time down wrong paths.

I have some thoughts for a more generic solution, which centers around prioritizing some of the initial analysis, however that will take some more thinking.

**Comment by securitykitten** [comment]
Thanks for looking into this issue, I downloaded the latest version and tried out the option.  

Just confirming that it did work and I can now disassemble the sample.
