### ISSUE TITLE
Can't change token display type in TokenizedTextView

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1403]
`InstructionTextToken` objects that I create with `PossibleAddressToken` or `IntegerToken` type cannot change their display type in a `TokenizedTextView`. However, I've noticed that if I just pass through one of these tokens from a `DisassemblyTextRenderer`, it will change display types as expected.

I'm not seeing any difference between the attributes of the tokens I generate vs the ones that come from the `DisassemblyTextRenderer` so I'm at a loss as to what is causing the issue; it's currently forcing me to manually look up symbols and set the token type to `CodeSymbolToken` or `ImportToken` if a symbol exists, which is probably not super efficient.

**Comment by D0ntPanic** [comment]
It is intentional that `TokenizedTextView` does not modify the tokens in any way, because we do not want to force a single use case of this view. Tokens passed to the view are shown as provided to the API, and this will not be changed. `DisassemblyTextRenderer` is the class responsible for display types and symbol name replacement. Unfortunately, the API was not flexible for certain custom views, such as those that wish to replace the IL rendering with their own.

A new API needed during HLIL development has been backported to dev that should help fix some of these use cases. Try the `DisassemblyTextRenderer.post_process_lines` API, which processes a provided set of tokens in the same way that normal disassembly does. Available in build 1808.
