### ISSUE TITLE
Make "Code" feature

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1404]
Currently the only way to disassemble code in BN is to create a function. There are times, particularly when dealing with firmware, or pieces of code that don't quite fit the "function" model where it would be nice to see the disassembly, without the "function" overhead.

We should allow the creation of "code" regions which when displayed in linear view will do a _true linear_ (i.e. non-recursive) disassembly.  Users should be able to create them by hitting "c" on a non-code, non-datavar address in linear disassembly. This should create a code section from the address selected until the end of the section/segment, next-datavar, next-code, or next invalid disassembly.

**Comment by cnSchwarzer** [comment]
No more delays please, i think this feature is really important.

**Comment by psifertex** [comment]
Thanks for the feedback. Can you describe your intended workflow so we can make sure our future changes will solve it for you?

**Comment by cnSchwarzer** [comment]
Thanks, 
For some 'strange' code in some ctf matches, they use trash code to mislead disassembler. 
For example they use:
```
push {r0-r5,r7}
unk #1
```
to cause an sigill interrupt and handle code there.
Currently BN will stop analyse the binary at the first occurrence of 'unk #1', however there're many more codes following, those are defineitel not function, which requires this Make Code feature.
Just like IDA Pro, you simply press 'C' to convert bunch of binary to disassembly, just like you press 'D' to convert to data.

Moreover, In ARM mode, currently the BN distinguish ARM/thumb by using whether the jump target address is odd or even, please provide a feature to set a block of function/code to arm/thumb mode, just like IDA Pro's Alt+G.

**Comment by psifertex** [comment]
Is there a reason that pressing `p` to make a new function at the code location doesn't work? Part of the reason I ask is that our current plan for `c` would be to just show disassembly but not do any actual lifting/analysis. If you want the code to continue analysis then `p` would be a better choice and currently works (or you can bind `del` to PATCH/NOP which is what I do then you can NOP the bytes causing analysis to continue.

We do still plan to implement `c` but as I said, it will probably just be a display-level filter that will show bytes as dumb disassembly but will not do any lifting/analysis which is probably not what you want for the situation described above. 

I use the following snippet to toggle arm/thumb. Does this work for you? (Install the snippet plugin from the plugin manager, paste this into a snippet, then bind to whatever hotkey you'd like):

```

# ARM/Thum have an odd quirk where the same architecture module handles both and
# uses the lowest bit of the address to determine the correct architecture, so
# the normal API usage of specifing the optional platform will not work. Here's a
# quick snippet to show now to toggle the architecture of the current function by
# removing/creating it

if current_function.arch == Architecture['armv7']:
	new_arch = Architecture['thumb2']
	offset = 1
elif current_function.arch == Architecture['thumb2']:
	new_arch = Architecture['armv7']
	offset = 0
else:
	raise AttributeError("This snippet only works on thumb or armv7 functions")

address = (current_function.start & 0xfffffffe) + offset

new_platform = bv.platform.get_related_platform(new_arch)
bv.remove_function(current_function)
bv.create_user_function(address, plat=new_platform)
log_info("Creating a %s function at %x" % (str(new_arch), address - (address % 2)))```

If you want it to handle a range of bytes and thus remove/create multiple functions, you can modify it to use current_selection so that it changes any functions within a range if you prefer as well, happy to show how to do that modification.

**Comment by nshp** [comment]
In that CTF case, it might be better to patch the `unk #1` into a NOP (assuming instructions continue right after it). Just highlight that line, hit 'e', and enter 'nop'. Analysis should work just fine from there.

**Comment by psifertex** [comment]
Yeah, that was my suggestion as well. That's why I have this key binding:

<img width="672" alt="Screen Shot 2020-11-06 at 12 21 13 PM" src="https://user-images.githubusercontent.com/140215/98395648-9080af80-202a-11eb-9912-46c0879d5369.png">

Side note: it's kinda magical using it on call instructions in HLIL (though it's not clean for all HLIL instructions because the lack of many to many mappings right now)

**Comment by cnSchwarzer** [comment]
> Is there a reason that pressing `p` to make a new function at the code location doesn't work? Part of the reason I ask is that our current plan for `c` would be to just show disassembly but not do any actual lifting/analysis. If you want the code to continue analysis then `p` would be a better choice and currently works (or you can bind `del` to PATCH/NOP which is what I do then you can NOP the bytes causing analysis to continue.
> 
> We do still plan to implement `c` but as I said, it will probably just be a display-level filter that will show bytes as dumb disassembly but will not do any lifting/analysis which is probably not what you want for the situation described above.
> 
> I use the following snippet to toggle arm/thumb. Does this work for you? (Install the snippet plugin from the plugin manager, paste this into a snippet, then bind to whatever hotkey you'd like):
> 
> ```
> 
> # ARM/Thum have an odd quirk where the same architecture module handles both and
> # uses the lowest bit of the address to determine the correct architecture, so
> # the normal API usage of specifing the optional platform will not work. Here's a
> # quick snippet to show now to toggle the architecture of the current function by
> # removing/creating it
> 
> if current_function.arch == Architecture['armv7']:
> 	new_arch = Architecture['thumb2']
> 	offset = 1
> elif current_function.arch == Architecture['thumb2']:
> 	new_arch = Architecture['armv7']
> 	offset = 0
> else:
> 	raise AttributeError("This snippet only works on thumb or armv7 functions")
> 
> address = (current_function.start & 0xfffffffe) + offset
> 
> new_platform = bv.platform.get_related_platform(new_arch)
> bv.remove_function(current_function)
> bv.create_user_function(address, plat=new_platform)
> log_info("Creating a %s function at %x" % (str(new_arch), address - (address % 2)))```
> 
> If you want it to handle a range of bytes and thus remove/create multiple functions, you can modify it to use current_selection so that it changes any functions within a range if you prefer as well, happy to show how to do that modification. 
> ```

Yes, it will be ok to just convert bunch of bytes to a dumb disassembly but not continue analyse.

**Comment by psifertex** [comment]
Excellent, that's the current plan for this feature.

Did you have a chance to try out that snippet? Does that help solve your other issue? If not, mind filing a separate bug report with more details so we can track it independently of this one?

**Comment by jeffli678** [comment]
This is also super helpful for the debugger!

**Comment by psifertex** [comment]
In lieu of a first-class feature, [this plugin](https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/make_code.py) has been created that can make creating sections of code that don't exist in functions easier. It's a bit of a hack but quite usable.

**Comment by xusheng6** [comment]
This feature can be triggered in the following ways:

1. Press `C`
2. Select menu "Debugger"->"Make Code"
3. Right click and select "Debugger"->"Make Code"

**Comment by fuzyll** [comment]
This came up during a meeting today. I continue to get questions on this and don't believe this has actually been addressed in the way that users would consider "complete". So, I'm reopening this.

**Comment by 9hozt** [comment]
Hi there :)

As mentionned by @plafosse in the issue, this feature is mandatory for reversing firmwares. Indeed, firmware often has "standalone code" that are not functions. A good example are Exception Vectors. 

Here is a concrete example:

![image](https://github.com/Vector35/binaryninja-api/assets/116867625/fec5a8c7-aac2-42c0-9c66-9409811489cf)
 We can clearly identify the ARM branch here.

```bash
ghozt@maze:~$ rasm2 -d -a arm "7cf09fe5" 
ldr pc, [pc, 0x7c]
```

Creating functions on this code leads to some unreadable view: 

![image](https://github.com/Vector35/binaryninja-api/assets/116867625/ac352d87-805b-4472-ba65-223dc74a8921)

I think it'll be better if binja allows to create code that will be display in a linear way to better understand these execption vectors.

This is only one example, but this feature will be really appreciate by firmware reversers ^^

**Comment by whitequark** [comment]
> this feature is mandatory for reversing firmwares

Is it? I reverse mainly firmware and I've never felt that I must have it... It doesn't feel particularly burdensome to have a function per vector for example, and it can actually be convenient because then I can write a script that gives it the right name and have it always apply at the well-known vector address instead of parsing the vector.
