### ISSUE TITLE
Malware sample causes analysis loop

### ISSUE THREAD

**Issue by securitykitten** [Vector35/binaryninja-api#1416]
When forcing analysis of a function BinaryNinja will spin indefinitely. 

|Setting|Value|
|--------|--------|
|BinaryNinja Version|Version 1.1.1814-dev (Build ID c4712e9a)|
|Analysis Mode|Full|
|Disallow Branch to String|Enabled|
|Always Analyze Indirect Branches|Enabled|

* Open the following malware (password infected)
[9d021d6bd49eaa892edd327fba7670bd3ac099d92282de760ba35c9e4bee6a00.zip](https://github.com/Vector35/binaryninja-api/files/3448643/9d021d6bd49eaa892edd327fba7670bd3ac099d92282de760ba35c9e4bee6a00.zip)
* Browse to `sub409cc0`
* Select "Force Analysis of this Function"
![image](https://user-images.githubusercontent.com/5833122/62161178-90e8b180-b2e3-11e9-8d87-b3747da5d712.png)
* Attempt to view the MLIL or LLIL

I understand this is probably generating a worst-case scenario/pattern, but in situations where BinaryNinja is inline and automatically disassembling there is a need for some analysis guard rails.

Let me know if you have any questions.

**Comment by psifertex** [comment]
Thanks for reporting the issue, we're happy to have samples that trigger pathological cases. That said, we don't really need more guard rails -- we have them, and they triggered as they should. The fact that when you override them it it spins is not surprising. 

We may change the language to be a bit stronger since "this may take a while" is more appropriate for some of our other "force analysis" cases such as when functions are too large, but in the case of "excessive incremental updates" it's almost certainly a pathological issue that needs to be resolved and it will never finish.

**Comment by bpotchik** [comment]
Thanks for reporting this issue. The message about excessive incremental updates most likely means an analysis loop was encountered. It looks as if we have an issue processing a 'no-return' during a certain situation. We will investigate and report back.

**Comment by securitykitten** [comment]
@psifertex :+1:   Completely understandable.  Thanks for the update. 

The expectation on these tickets is not to have the BinaryNinja team "solve the problem", but rather to pass over edge cases that may be causing issues in the disassembly or lifters.  Hopefully this sample is causing an edge case to occur that can be easily patched.

In our use-case, we are as greedy as possible and use/abuse as much of BinaryNinja's MLIL as we can.  So we're forcing analysis on our side and then externally watchdog'ing them.  If the disassembly is all we can get back, then that's what we use.  Working our way up the chain incrementally.

**Comment by bpotchik** [comment]
This analysis loop appears to have been fixed a while ago. I tested with 2146-dev. Thanks for reporting.
