### ISSUE TITLE
Warn when running as root and document QWebEngine workaround

### ISSUE THREAD

**Issue by marpie** [Vector35/binaryninja-api#1454]
I'm using BinaryNinja in one of my VMs that is running as root, as the VM is reset on every shutdown.

While most things work fine, BinaryNinja is crashing while invoking the "Edit" \ "Preferences" \ "Manage Plugins" action. It seems to be related to the Chrome Sandbox:

## Steps to reproduce:

1. Open *root*-Terminal
2. Navigate to BinaryNinja directory
3. Execute `./binaryninja`
4. Navigate to "Edit" \ "Preferences" \ "Manage Plugins"

The crashed instance shows the following error message in the console:

```
[16:45] [root@k01] [/opt/binaryninja]: ./binaryninja 
[2305:2305:0930/164511.694147:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

## Possible Solution

It is possible to set `QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox` to instruct QT to not enable the sandbox.

Maybe this could be added in the docs for reference.

## Environment

* OS: *Kali Linux (5.2.0-kali2-amd64)*
* Binary Ninja Version: *1.2.1902-dev (Build ID 96eb66b6)*

**Edit**: Workaround found, see *possible solution*. Ticket can be closed.

**Comment by psifertex** [comment]
Thanks for the report and the proposed workaround -- we'd still like to avoid this situation so we might look into other fixes. 

We do recommend not running Binary Ninja as root in general, but crashing is still poor behavior.

**Comment by marpie** [comment]
> We do recommend not running Binary Ninja as root in general, but crashing is still poor behavior.

Absolutely, I would not recommend setting this as a default option. As the snapshot of my VM is reset on every shutdown, I don't consider this an issue here.

**Comment by psifertex** [comment]
I'm going to re-open this since it's about to get a lot worse as we're changing the start-tab to include a QWebEngine instance as well. I'll go ahead and re-title it if you don't mind with our planned fix.

We'd like to warn the user when running as root with a message that lets them know about this environment variable since otherwise the default launch behavior will be to crash.

**Comment by psifertex** [comment]
Fixed in builds >=1908.

Note that it doesn't currently link to this specific issue since I suspect there will be other complications for root users in the future, but it at least warns that it's unsupported. This does mean you'll have to hit `escape` to cancel the automatic quit, but it's still possible to run as root.
