### ISSUE TITLE
Allow closing detached dockwidget

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#1483]
It is not possible (at least in macOS) to close a dockwidget window once it has been detached from the main BinaryNinja UI. In order to close it one needs to reattach it and then click on the X. In macOS the close button is disabled:

![close_button](https://user-images.githubusercontent.com/564972/69081706-8fff9b00-0a0c-11ea-987d-09a2ad410a3a.png)

**Comment by bpotchik** [comment]
Did you try using the command palette to hide the dockwidget?

**Comment by bpotchik** [comment]
Currently dockwidgets don't support close operations unless explicitly implemented. DockWidgets also inherit context menu items so you should be able to right click and select "Hide".

**Comment by bpotchik** [comment]
There was actually an issue with `getActiveDockHandler` where it would sometimes fail to return the active dock handler object. This caused some of the inherited actions above to not show up for python based dock widgets.  Also added the closed button for detached dock widgets and fixed the dock toggle behavior from the context menu of a dock title bar.

Fixed in 1.2.1956-dev.
