### ISSUE TITLE
Bug: No Script console

### ISSUE THREAD

**Issue by plowsec** [Vector35/binaryninja-api#1487]
Binary Ninja Version: 1.2.1921, 4ca675f1
Platform: Arch Linux

Hello,

I don't have a menu in "View" for opening the Python script console, and the CTRL+backtick does not seem to do anything. In the logs, I have the following errors:

```
Python is already loaded but is not compatible with the plugin loader. Python plugins unavailable.
Download provider: 'PythonDownloadProvider' not available!
```

I have a valid commercial licence, but am completely inexperienced with the software, so let me known if you need additional information.

Thanks!

**Comment by psifertex** [comment]
If you are  running python 3.8, it is not compatible with QT and pyside2 at this time. Unfortunately Arch switched a bit too early as many programs are still not compatible with 3.8. If you aren't running 3.8, see: https://docs.binary.ninja/guide/troubleshooting.html#arch-linux

To work around it you can either use the settings to change to the QT download provider (go to settings and search for download) and update to the latest dev branch  where we have a workaround that disables UI plugins but will otherwise still function (updates are also available under settings) or you can compile your own python 3.7 and specify that python version in the settings.

Additionally, we are not officially compatible with Arch, though it's usually possible to work around any issues. We recommend using an ubuntu  LTS VM or docker image to guarantee compatibility. 

For future support of arch, I'd recommend joining the channel in our support slack (slack.binary.ninja) called #unsupported-distros.

**Comment by psifertex** [comment]
If it does turn out to be Py3.8 I've created #1488 so you may wish to track that issue as well.
