### ISSUE TITLE
analysing chrome_child dynamic lib will cause binaryninja to die

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#1503]
![image](https://user-images.githubusercontent.com/5463104/71727410-1b29d880-2e75-11ea-9b17-e93b3f036faa.png)
chrome 73.0.3683.86 x64, and dll is chrome_child.dll
finished Open and load the pdb, ninja have worked a whole day and could not finish the ananlysis.

![image](https://user-images.githubusercontent.com/5463104/71758538-e735ce00-2edb-11ea-91f2-973485565eec.png)
win10x64 32G amd 64 thread

**Comment by frustreated** [comment]
nobody cares 
![006fbYi5gy1fem3av6c5xj307d07djrf](https://user-images.githubusercontent.com/5463104/71766176-03675880-2f38-11ea-8825-46c944b71eab.jpg)

**Comment by psifertex** [comment]
We care, several of us are still out of the office on holiday break. Give us some time. :-)

**Comment by frustreated** [comment]
thank u so much！really need your help

**Comment by psifertex** [comment]
Don't have time for a full reply right now, but very briefly, try this:

File / Open With Options
Change analysis mode to "Basic"
Change Max Function Analysis Time to something like, say, 5s (5000 ms)

Likewise you can play with the other analysis limits to get the analysis to complete more quickly. I will warn you however that the personal edition is only single-threaded and will always be slow for very large binaries. That said, the analysis should complete, though you might need a lot of RAM or a large swap file. You can also decrease the analysis cache size to help with memory utilization. That said, a relatively recent dev update decreased memory utilization and I haven't tested chrome since then so it's possible this is less of an issue now.

**Comment by frustreated** [comment]
> Don't have time for a full reply right now, but very briefly, try this:
> 
> File / Open With Options
> Change analysis mode to "Basic"
> Change Max Function Analysis Time to something like, say, 5s (5000 ms)
> 
> Likewise you can play with the other analysis limits to get the analysis to complete more quickly. I will warn you however that the personal edition is only single-threaded and will always be slow for very large binaries. That said, the analysis should complete, though you might need a lot of RAM or a large swap file. You can also decrease the analysis cache size to help with memory utilization. That said, a relatively recent dev update decreased memory utilization and I haven't tested chrome since then so it's possible this is less of an issue now.

thank U so much ,i use the **### Commercial** also ida is the newest 
ninja is really fast when the file is not very big than 30M maybe.
the pdb analysis time is a little long also ida will analize may be 2 hours.

I am going to try your advise. and really thank U so much!!

**Comment by frustreated** [comment]
![image](https://user-images.githubusercontent.com/5463104/71776011-9fd73c80-2fc4-11ea-8196-6fc9aa6e8e14.png)
i have to upload this picture that , after paid maybe 6 hours , and ninja successfully died.
analysis has be finished but pdb could not successfully loaded.

the args as following 
![image](https://user-images.githubusercontent.com/5463104/71776107-a5358680-2fc6-11ea-88d9-7d3f1ff13164.png)
![image](https://user-images.githubusercontent.com/5463104/71776111-b7afc000-2fc6-11ea-8778-c28173bd2ce6.png)
![image](https://user-images.githubusercontent.com/5463104/71776113-c5654580-2fc6-11ea-88e1-0412bf841e7f.png)

**Comment by psifertex** [comment]
Hmm, we've tested chrome builds before (it's one of our main "large file" test cases) but I don't know that we've loaded the PDB before. There might be some issues there since that many symbols might be pushing the limits of what we've tested. I'll test it and see if we can figure out where it's dying.

**Comment by frustreated** [comment]
if any convience , i can have a run with the test case. 
the newest ida also have some other wierd things to process the chrome_child pdb.

**Comment by frustreated** [comment]
parse the pdb will cause ninja to paused , also the newest ninja to analysis chrome_child.pdb
if capture needed i will post it .

**Comment by bb33bb** [comment]
i will going to have a try if it's not ok ,i will make it open again.
