### ISSUE TITLE
Startup failure Fedora 31

### ISSUE THREAD

**Issue by m0xxz** [Vector35/binaryninja-api#1522]
Getting the following message trying to launch Binary Ninja, after providing my license file:

```
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
```

**Comment by psifertex** [comment]
Unfortunately Fedora isn't an officially supported platform (we officially only support Ubuntu through various LTS releases and the latest stable: http://faq.binary.ninja/en/what-platforms-does-binary-ninja-run-on-66GRPbTBKdZuCqjqc) but we can usually work around it for other linuxes with the right combination of environment variables or libraries. This is /probably/ a conflict with an existing QT library or version mis-match. 

Given that, I'm going to close this issue, but we can probably help you out over in our slack (https://slack.binary.ninja/ in channel #unsupported-distros where several users running other linux variants can help provide better advice). Once we find a workaround, feel free to comment here and we can update our troubleshooting documentation where we list known fixes for other distros (https://docs.binary.ninja/guide/troubleshooting.html#linux).

I'll also try to do some quick testing as I've got time and setup a VM to test. If I figure out a solution I'll post it here as well.

**Comment by psifertex** [comment]
For what it's worth, I just had a chance to test a Fedora 31 install and it worked just fine. I did have to specify the Python3 path (we'll go ahead and add the Fedora python3 location to our default search path) but otherwise it worked fine. Are you by chance running one of the non-default desktop environments?

**Comment by m0xxz** [comment]
> For what it's worth, I just had a chance to test a Fedora 31 install and it worked just fine. I did have to specify the Python3 path (we'll go ahead and add the Fedora python3 location to our default search path) but otherwise it worked fine. Are you by chance running one of the non-default desktop environments?

Hey there, at the time I was using the default desktop env -- When I have an change this week I will see if specifying the python3 path solves the issue I was having.

Thanks for reaching out!

**Comment by psifertex** [comment]
Your issue isn't related to the python path -- the UI still loaded, it just complained about not finding python and I was able to set it in the settings. 

One other thing to try (besides just using an Ubuntu Docker image or Vm which should player nicer since that's our official platform) would be to create a settings.json to disable activeContent (on my phone now so don't have an example but the exact setting is on https://docs.binary.ninja/ )

**Comment by m0xxz** [comment]
To follow up -- I redownloaded a copy of Binary Ninja and it started right up. I am not aware of any changes on my end since the last time, though all is working well now.

Thanks for the assistance with trying to troubleshoot; I hope to see more Linux distros be supported in the future.

Happy Hacking!

**Comment by psifertex** [comment]
Glad it's resolved, reboot and reinstall are always the two easiest solutions. ;-)

Thanks for updating.
