### ISSUE TITLE
Repeated warnings on update about installing prerequisites 

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1545]
![5D8FBB19-5318-495F-A6B1-00CEBEBAC05B](https://user-images.githubusercontent.com/140215/76143618-f0abf580-6046-11ea-9db8-942cdc685c12.jpeg)

From Markus via slack.

**Comment by gaasedelen** [comment]
Bug: Everytime binja updates, it asks to intsall/reintall the above reditributable when it is already installed on the system.

Expected behavior: Binja does not prompt me to install this redistributable. 

Platform is Windows 8.1 x64, but I don't think the SKU is to blame, on Binja dev branch.

It wasn't doing this 6-12 months ago, but I only started updating binja again this week so I am not sure when this regression started.

**Comment by D0ntPanic** [comment]
This was fixed when updating to the VS2019 runtime in early June
