### ISSUE TITLE
Extract Indirect call's Targets

### ISSUE THREAD

**Issue by bin2415** [Vector35/binaryninja-api#1557]
Hi, is there any api to extract indirect call's targets?

Thanks!

**Comment by psifertex** [comment]
Yes, you'll want to use the `.possible_value` APIs: https://api.binary.ninja/search.html?q=possible&check_keywords=yes&area=default

The simplest way to do that is to find the MLIL instruction of a call and access the `.possible_value` attribute on the variable representing the register. If our data-flow system was able to calculate the range on the register it will be returned there. If you get `undefined` then it's likely the result of something like a virtual function call that isn't calculable within the existing function and requires inter-function dataflow which we don't automatically calculate due to path explosion.

**Comment by bin2415** [comment]
Great! Thx!
