### ISSUE TITLE
Support for Python on Cygwin

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#1560]
When I import binaryninja using Cygwin's python, it gives an "OS not supported exception".  Looking at _binaryninjacore.py, it appears that Cygwin-python's call to platform.system() returns ''CYGWIN_NT-10.0-18362" as opposed to a simple "Windows" or "Linux".  I managed to workaround this issue by adding a check for CYGWIN_NT on the Windows line (since it is indeed a Windows install):

Workaround in _binaryninjacore.py, change line 18 from
`elif core_platform == "Windows":`
to
`elif core_platform == "Windows" or 'CYGWIN_NT' in core_platform:`

With that change, I can run binja with the Cygwin python.

**Comment by psifertex** [comment]
That should be `elif core_platform == "Windows" or core_platform == 
"CYGWIN_NT"` as otherwise you're forcing it to always assume windows as the string is always there, but thanks for the heads up.

I've made the change to the API though I'm going to hold off on triggering a full dev build since you've got it fixed locally and I've got some other changes to the API coming later today anyway.

**Comment by resrever** [comment]
The platform is not "CYGWIN_NT"  It is "CYGWIN_NT-{windows version info}".  Perhaps parenthesis would make it clearer:
`elif (core_platform == "Windows") or ("CYGWIN_NT" in core_platform):`

**Comment by psifertex** [comment]
Ahh, my mistake. Thanks for catching that. I went ahead and adjusted it to be a `.find(..) == 0` since it should start with that string.
