### ISSUE TITLE
Inconsistent Variable Type in HLIL

### ISSUE THREAD

**Issue by Martyx00** [Vector35/binaryninja-api#1587]
When working with instructions and the API in case that the instruction operation is either `HLIL_VAR_DECLARE ` or `HLIL_VAR_INIT ` the variable is directly shown as `binaryninja.function.Variable` where in all other cases (like operation `HLIL_ASSIGN`) it is shown as `binaryninja.highlevelil.HighLevelILInstruction.HLIL_VAR` instruction (which I think is very good idea). The situation is shown in the below console snippet:

```python
>>> list(current_hlil.instructions)[0]
<HLIL_VAR_DECLARE: int64_t rax>

>>> list(current_hlil.instructions)[0].operands
[<var int64_t rax>]

>>> list(current_hlil.instructions)[1]
<HLIL_VAR_INIT: int64_t rsi_1 = *(arg2 + 8)>

>>> list(current_hlil.instructions)[1].operands
[<var int64_t rsi_1>, <HLIL_DEREF: *(arg2 + 8)>]

>>> list(current_hlil.instructions)[3]
<HLIL_ASSIGN: var_90 = arg2>

>>> list(current_hlil.instructions)[3].operands
[<HLIL_VAR: var_90>, <HLIL_VAR: arg2>]
```

Ideally I would say that the variable objects should behave consistently and wherever possible should be considered as `HLIL_VAR` objects. Unless, of course there is a reason to not have it implemented this way.

**Comment by D0ntPanic** [comment]
This is intentional. It mirrors all other forms of the IL when assigning directly to a variable and reduces redundant information in the expression trees. It is also done for type safety when constructing and accessing the instructions from C++. This change could only be made by making the destination of an HLIL_VAR_DECLARE and HLIL_VAR_INIT instruction take a full expression object, which would allow the type of the destination to be incorrect for the instruction. By taking a variable directly, it is enforced that the destination is always of the correct type. This pattern is true in all of the ILs, and it will not be changed here.
