### ISSUE TITLE
Database merging

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#163]
Real collaboration that doesn't suck and can be "undone".

**Comment by psifertex** [comment]
(We've talked about this a lot, but to add some more details here)

We expect that this will likely be implemented first in enterprise and it will support both online (while connected) synchronization as well as offline (so that changes done while not connected can be later merged with other changes). It's possible only online is implemented at first however.

**Comment by plafosse** [comment]
Added in v1.3.2079
