### ISSUE TITLE
Detection of stack arrays

### ISSUE THREAD

**Issue by verylazyguy** [Vector35/binaryninja-api#1637]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/7s4YBtT"  ><a href="//imgur.com/a/7s4YBtT">HLIL Inline String issue</a></blockquote>

makes it tedious to see each letter. Is there a good way to do this that I don't know about?

**Comment by psifertex** [comment]
Does this snippet work for it? 

It was meant for similar situations though I haven't tested it in HLIL like that. https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-string-annotator-py

**Comment by verylazyguy** [comment]
neat. I used it in MLIL and it made a comment that shows up in HLIL. Not a perfect solution but a great workaround for now. Thanks!

**Comment by psifertex** [comment]
Cool. Leaving the bug open since I think the right fix is actually creation of the array and then annotating these as array indexes which prevents optimization. My snippet would still be useful without an additional pass to simplify the array as well and I don't know if that's expected for a while or not. 

Oh, you could have also fixed it by setting the base type there as an array of the appropriate length I believe.

**Comment by plafosse** [comment]
As this is actually a problem in MLIL I've changed the description.

**Comment by bpotchik** [comment]
Fixed in `3.4.4133-dev`. This is accomplished with the `analysis.outlining.builtins` feature which is now enabled by default.
