### ISSUE TITLE
Include Wayland backend in bundled Qt?

### ISSUE THREAD

**Issue by tchebb** [Vector35/binaryninja-api#1692]
Qt has native support for Wayland, but Binary Ninja currently ships with a prebuilt Qt that doesn't have that platform enabled. I've been running BN on [Sway](https://github.com/swaywm/sway) with the following environment
```
QT_PLUGIN_PATH=/usr/lib/qt/plugins
QT_QPA_PLATFORM=wayland-egl
```
which forces it to use system Qt plugins and selects the Wayland platform.

I can report that BN launches and operates fine under Wayland. I have noticed no issues except for [this one](https://bugreports.qt.io/browse/QTBUG-81952), which only happens in very specific conditions (switching to a new menu while a submenu is open) and looks like it's on its way to being fixed in upstream Qt.

My trick of using system plugins is brittle, however, and only works because my system Qt version (5.14.2) happens to match the prebuilt one right now. It would be much nicer if the Wayland platform were just shipped with BN to begin with.

Qt [currently defaults](https://github.com/qt/qtbase/blob/e7ca98f40f83bb012002b69226d3c27c02271d31/src/gui/CMakeLists.txt#L36) to the X backend unless the user explicitly specified Wayland (using `QT_QPA_PLATFORM` or the `-platform` argument), so this change would not risk regressing users who are happy running BN via XWayland.

**Comment by psifertex** [comment]
We're currently building our own QT while we wait for QT6.2 to include stable M1 support out of the box and wayland isn't building for us on our current config. Most likely we'll be waiting until we are using the standard QT again and we can just ship the library.

**Comment by XVilka** [comment]
I should note, that with the latest Ubuntu, Fedora, etc releases Wayland becomes a default option.

**Comment by D0ntPanic** [comment]
Bundling Wayland with Binary Ninja breaks important functionality (pane management) on our most supported platform (Ubuntu 22.04), so we will not be bundling Wayland as of Qt 6.3.0. Qt's current Wayland support is not complete enough for Binary Ninja to work properly on Ubuntu. We will revisit Wayland support on future Qt releases.

**Comment by D0ntPanic** [comment]
We have worked around some of the problems and are able to now ship the Wayland client, but it is not enabled by default because of limitations. It is available starting in build 3503.

To enable Wayland support, run Binary Ninja with the following option:

``` bash
./binaryninja -platform wayland
```

Alternatively, you can set the `QT_QPA_PLATFORM` environment variable to `wayland`.

Wayland support in Binary Ninja is not complete, and has the following known issues:

* Panes cannot be dragged out into new windows. You must use the "New Window for Pane" action to move a pane into its own window.
* It is not possible to move panes between existing windows.
* In Gnome-based environments, the window decorations do not use the active theme, and are instead rendered using a Qt default.
* Font scaling settings may be ignored. You may have to manually adjust font sizes in the Binary Ninja Settings if you use font scaling.

It is recommended that Gnome users continue to use the X11 version, but users of other environments may have a better experience with the Wayland client, especially when using high resolution monitors with scaling.

The issues with panes are tracked by bug #3188
