### ISSUE TITLE
support for windows minidump

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1697]
Have current support for linux core files, but not windows minidumps.

**Comment by xusheng6** [comment]
Duplicate of https://github.com/Vector35/binaryninja-api/issues/653.

Also, as a status update, we already support loading a Windows dump file on Windows -- https://dev-docs.binary.ninja/guide/debugger/index.html#loading-windows-dump-files, #653 tracks adding cross-platform support to it so that we can load it on Linux/macOS as well
