### ISSUE TITLE
allow custom graph layouts

### ISSUE THREAD

**Issue by amimo** [Vector35/binaryninja-api#1729]
ghidra's graph view has a high level structure like the source code,
looks like region info or ast is used to compute the layout of the graph nodes.

here is a simple if-else cfg:
![image](https://user-images.githubusercontent.com/4100485/83131076-e2371c80-a111-11ea-9ef8-eb842e032d9e.png)

the if and else clause are indented just like the source code.

more complex cfg:
![image](https://user-images.githubusercontent.com/4100485/83131490-7dc88d00-a112-11ea-977d-8b0277d240bc.png)

all nested code block are proper indented.

i think it is a very cool feature, it will be nice if binja has one.

**Comment by psifertex** [comment]
Oh, that's interesting. I had no idea that Ghidra did that already. We've actually been planning on leveraging HLIL control flow objets to inform our graph layout for some time now, just hadn't made a ticket for it. We agree that would be a really nice feature and was already on our roadmap, thanks for filing!

**Comment by psifertex** [comment]
I'm changing this bug to track potentially allowing custom graph layouts, but we otherwise don't have plans to add this exact layout. We do have our own plan for grouping graphs based on HLIL but that's a separate feature. I'm renaming this "allow custom graph layouts" since that will be our intended solution to this.

**Comment by negasora** [comment]
Added in `4.2.6080-dev`
