### ISSUE TITLE
Text selection inside tokens

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2019]
Allow users to select substrings of tokens (and therefore copy substrings). Re: #1973 

Proposed design: If selection starts and ends within the same token, select a substring based on which characters were in the region. If selection covers more than one token, fallback to the original selection method of tokens only.

**Comment by yrp604** [comment]
This sounds good to me, just one note -- the proposed solution works because string literals are considered a single token. E.g. "The quick brown fox jumped over the lazy yellow dog" is all a single token. If for whatever reason you wanted to tokenize string literals further (split by space for example), then the proposed solution would run into issues.

**Comment by CouleeApps** [comment]
Implemented in 2.1.2454

**Comment by bpotchik** [comment]
Current implementation often goes straight into intra-token selection when clicking a token with the slightest movement of the trackpad/mouse. This makes it very difficult to simply select tokens for the purpose of following variable highlights. Should probably increase the drag distance before entering intra-token selection mode.

**Comment by CouleeApps** [comment]
The fix I'd expect would be to only activate char selection when there are 2 or more chars in the region.

**Comment by psifertex** [comment]
I'm not sure that's the right choice either -- it just makes the failure rate less common, but not impossible. Otherwise if you happen to single click (and very slightly drag) right on the margin between two characters you could still trigger it.

Requiring a drag-distance of some amount seems like the safest bet to me. Can probably play with 0.5char width or smaller to see what feels natural.

**Comment by CouleeApps** [comment]
The reason for reopening this was fixed a few months ago.
