### ISSUE TITLE
respect system proxy settings

### ISSUE THREAD

**Issue by evanpjensen** [Vector35/binaryninja-api#202]
New updater doesn't respect the windows system proxy.

**Comment by psifertex** [comment]
When you say "new updater" do you mean in a recent build? I don't think the updater code has changed recently, it likely never has respected the proxy.

**Comment by wontonSlim** [comment]
I misinterpreted the latest email and assumed the out of band installer included new update code.
In any case, today was the first time I noticed a failure reaching the update server due to proxy issues.

**Comment by psifertex** [comment]
No worries, thanks for clarifying. 

Because our core has to function without any QT libraries (in the case of headless operation), we can't rely on their proxy support unfortunately and we don't want to write and maintain cross-platform proxy detection code.

That said, when we implement our hidden preferences / advanced preferences capability for more obscure settings, we'll include a way to manually specify proxies. 

Blocked by #126

**Comment by bpotchik** [comment]
Fixed in build 1.1.1229-dev.
