### ISSUE TITLE
Function fails to translate between MLIL and HLIL

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2034]
Windows 10 2469-dev Personal

During auto-analysis I get a bunch of messages like: Function at 0x1800a328c has invalid HLIL translation.

And sure enough if I go to that function, asm, LLIL, MLIL all work fine. HLIL gives "Function is empty".

[ntdll.dll.txt](https://github.com/Vector35/binaryninja-api/files/5382225/ntdll.dll.txt)

**Comment by cetfor** [comment]
I've encountered this issue using the headless Python API, version 2.2.2487 (Release). The target is a 32-bit ARM ELF.

```
...
Function at 0x287a8 has HLIL condition that exceeds maximum complexity, omitting condition
Function at 0x22e80 has invalid HLIL translation
...
```

I don't have a sample I can submit, but I'll be on the look out for one I can.

**Comment by gkprow-runsafe** [comment]
This issue occurs fairly regularly in both the UI and headless modes when analyzing aarch64 bash from a RaspberryPI 4 running Ubuntu. I've attached that binary here.

As an aside, I'm curious if this issue has actually been occurring for some time but has only been noticed due to a recent change in log writing behavior.

[bash.txt](https://github.com/Vector35/binaryninja-api/files/5673883/bash.txt)

**Comment by D0ntPanic** [comment]
Fixed in build 3526
