### ISSUE TITLE
Segfault When Creating Enum Type

### ISSUE THREAD

**Issue by xpcmdshell** [Vector35/binaryninja-api#2041]
Binary Ninja reliably crashes with a segfault when creating the following enum type:

```
typedef enum SecExternalFormat : uint32_t {
	kSecFormatUnknown = 0,
} SecExternalFormat;
```

The type is parsed successfully when omitting the `typedef` and trailing `SecExternalFormat` identifier.

**Comment by plafosse** [comment]
Which version of Binary Ninja are you on?

**Comment by plafosse** [comment]
Nevermind I got a crash now. :P

**Comment by D0ntPanic** [comment]
Fixed in build 2483. Note that the specific definition here will generate an error (no longer a crash). Enumeration names do not have a separate namespace from typedefs in Binary Ninja, so it will get an error for a duplicate name. Changing one of the names or getting rid of the typedef will resolve this. Closing this as the crash is resolved.
