### ISSUE TITLE
de-optimized math replacements / idiom detection

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2043]
Compilers do lots of fun things to calculate modulo or division with shifts and multiplication. We need a new optimization pass which will replace these more opaque operations with simplified expressions.

See:

https://zneak.github.io/fcd/2017/02/19/divisions.html
https://github.com/hcs0/Hackers-Delight

And a previous plugin that simply annotates with a comment: 
https://github.com/cah011/binja-div

**Comment by psifertex** [comment]
Interesting clang examples: https://twitter.com/whitequark/status/1338709746619088896

**Comment by pr0xy-t** [comment]
Ghidra approach
[https://github.com/NationalSecurityAgency/ghidra/issues/4322](https://github.com/NationalSecurityAgency/ghidra/issues/4322)

**Comment by pr0xy-t** [comment]
This link is broken.
> https://zneak.github.io/fcd/2017/02/19/divisions.html  

https://archive.is/e99XI

**Comment by D0ntPanic** [comment]
Simplification of optimized division and modulus has been added in build 3.5.4311

Not all division and modulus code patterns currently simplify. The following issues track cases that are not yet handled:

#4362: Optimized modulus using a combination of divide and shifted multiply with masking of low bits
#4363: Optimized modulus using arithmetic of mixed integer sizes
#4364: Optimized division and modulus are not simplified on armv7
#4365: Indirect sign extension through variable for dividend in optimized divide
#4366: Unsigned shift of signed value during optimized signed divide that is only valid because of additional multiplication
#4367: Use of partially written variable during optimized divide

**Comment by mostobriv** [comment]
Is there any plans on extending this on other cases?

**Comment by plafosse** [comment]
If you have specific cases please share them there is no way to my knowledge to _solve_ this problem, so the best corse of action is to identify the most common failure cases and write rules to reverse them.

**Comment by mostobriv** [comment]
I've got a few cases of optimized ( `x / 1000`):

<img width="637" height="453" alt="Image" src="https://github.com/user-attachments/assets/7077dadb-bcf0-42a3-8053-3573d0c6ee5a" />

<img width="641" height="519" alt="Image" src="https://github.com/user-attachments/assets/a298049f-6bc5-490a-924b-95a35c9b484f" />

<img width="597" height="100" alt="Image" src="https://github.com/user-attachments/assets/d3ab5329-942b-4741-a684-52ddb68b5a84" />

i've got more in other binaries, but i'm afraid i can't share those publicly:

[bin.zip](https://github.com/user-attachments/files/32519306/bin.zip)

**Comment by plafosse** [comment]
Thanks for sharing! If you can just share the assembly of the missed div/mod that would still be helpful.

**Comment by mostobriv** [comment]
Sure, here is one, if i find another one, i'll send it to the comments as well

<img width="477" height="118" alt="Image" src="https://github.com/user-attachments/assets/9983323f-ca7b-483f-94d9-8f701c7fd935" />
