### ISSUE TITLE
Add a Configuration Option that Control Number of Opcode Bytes Displayed

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#2048]
In the various disassembly views, the second column is the bytes. It would be great to add a configuration option that adjusts the width of this column. Sometimes the op codes are longer than this column can currently display and the UI clips the end of the opcode and replaces it with ellipsis. This ellipsis ends up in the clipboard when copying this data. If there were an option for the user to adjust the number of bytes that are displayed, this would not be an issue.

**Comment by galenbwill** [comment]
There are two orthogonal issues here:
1. Allowing for the control of the maximum number of opcode bytes actually displayed.
2. Copying all of the elided opcode bytes to the clipboard when the selection includes an ellipsis in opcode bytes.

(2) should probably be split into a separate issue, since it can be fixed without affecting the display or adding a configuration option, and it could be considered a bug.

If (2) were addressed, would it make addressing (1) unnecessary?

**Comment by utkonos** [comment]
@galenbwill Sounds good to me. If 2 were fixed, 1 would be much less important. A solution of some kind for 1 could then just be a tooltip that shows the full set of bytes.

**Comment by psifertex** [comment]
convenient test: ```mov dword [esp+0xffffffff], 0xffffffff```

For what it's worth, the tooltip already does show the full set of bytes. 

<img width="788" alt="Screen Shot 2021-11-04 at 9 21 17 PM" src="https://user-images.githubusercontent.com/140215/140442473-15ab8444-6c2e-4ba0-aa7e-1a4d3eac4f8f.png">

As for the copy feature, this has been added for builds >= 3098
