### ISSUE TITLE
Move "Download Client" settings to more general "Network" settings

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#2079]
Have the ability to disable individual types of network access

**Comment by psifertex** [comment]
Enable/Disable network activity for:
- [ ] Plugin Manager 
- [ ] Changelog / Startpage
- [ ] Version Check
- [ ] Downloading channel list (different from automatic update checking that occurs even if not in preferences in the prior item)
- [ ] Expiration Check / Automatic license update
- [ ] Help/File a Bug opens browser with a URL
- [ ] URL Handler
- [ ] Other QWebEngine views? (Probably won't bother since plugins can always choose to do their own thing)

Other
- [ ] Proxy Settings
- [ ] Provider Selection
- [ ] PDB Automatic Download

This bug basically supersedes #517 and #1825 since we'll implement all of these changes at the same time.

**Comment by jeffli678** [comment]
related to: https://github.com/Vector35/binaryninja-api/issues/2078, https://github.com/Vector35/binaryninja-api/issues/1825

**Comment by jeffli678** [comment]
it would also be nice to have a "test proxy" functionality next to the proxy setting. Android Studio is one example that offers it

**Comment by CouleeApps** [comment]
This is implemented to the extent we have control (can't do QWebEngineViews via https://bugreports.qt.io/browse/QTBUG-66601) in build 2.3.2805
