### ISSUE TITLE
High level language simple error

### ISSUE THREAD

**Issue by TheREK3R** [Vector35/binaryninja-api#2128]
Binary Ninja Version: 2.2.2487 Personal, e0eb0a77
Platform: Debian GNU/Linux bullseye/sid

I will link a file to this if possible, if not I will paste the base 64. 

Essentially my problem is that the first function takes a simple branch (compare var and set equal). This is part of a small intro challenge for my university ctf club. Binary ninja does not recognize this at all in high level language mode, and also refuses to take the path in the debugger. Both ghidra and ida have no problem identifying this if statement.

https://drive.google.com/file/d/1KyTGeMz_A3kW1vxdzX4wLGvjKRrUMgVu/view?usp=sharing

**Comment by psifertex** [comment]
This is not a bug. The function has a vulnerability which makes data that is otherwise fixed at zero (at stack offset `rbp-0xc`) able to be overwritten. Sadly, BN cannot model all of the potential state like `puts` can overwrite previous values on the stack. 

If you want to change this behavior, go to assembly and right click on address `0x4006a1` and choose `Patch / Convert to NOP`. This removes the line that writes a value to that location and will make BN treat it as uncertain. Then it won't optimize away the comparison that under normal execution could indeed never be reached.

**Comment by psifertex** [comment]
There is a feature being worked on in https://github.com/Vector35/binaryninja-api/issues/2074 that will also help this situation. I'm probably just going to close this one as a duplicate of that since that will also probably help make it more clear when something like this is happening.
