### ISSUE TITLE
Large function lists cause freezes

### ISSUE THREAD

**Issue by artemdinaburg** [Vector35/binaryninja-api#216]
Binary Ninja for OS X  (latest version, running on OS X 10.11.3) freezes when opening an ELF shared object. The file is a bit too large to upload here (11Mb) but I can provide you with a link or get it to you some other way. 

<img width="706" alt="binja_hang" src="https://cloud.githubusercontent.com/assets/1051838/14372446/ba34a1e0-fd0e-11e5-806d-8e0d2155a4cb.png">

**Comment by artemdinaburg** [comment]
Update: after about an hour it unfroze; so it looks like its just hitting a pathologically slow case.

**Comment by psifertex** [comment]
A link would be great -- performance is one of our important goals.

**Comment by artemdinaburg** [comment]
Turns out it compressed pretty well, attaching as github attachment.

[NRFIN_00026.so.tar.gz](https://github.com/Vector35/binaryninja-docs/files/209625/NRFIN_00026.so.tar.gz)

**Comment by psifertex** [comment]
Thanks. Investigating now.

**Comment by psifertex** [comment]
We've fixed the immediate bug that was caused with a large number of functions in the list. It opens much more quickly now. In the process of doing that, we found one new big -- namely removing from the function list is also slow for large lists. That bug is still unfixed though shouldn't impact you on this binary.

The other bug this binary exposes is #5.

Do you have the compiler flags you used for this binary? We've observed the relocations writing to the text segment on occasion before, but it would be nice to know which flag triggers it so we could test it more easily.

**Comment by psifertex** [comment]
Note that the fix described above will be coming in the next beta build after `289`.

**Comment by plafosse** [comment]
Renaming to reflect actual problem

**Comment by D0ntPanic** [comment]
Fixed in dev
