### ISSUE TITLE
Copy pasting out of python console copies wrong value if value is address

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2232]
2598-dev Windows 10

Copying an address from the python console appears to copy the text at the location. I expect it to copy the string literal I've highlighted.

![console-copy-paste](https://user-images.githubusercontent.com/8716677/104828770-a0cebb00-5821-11eb-9a26-73185f17e396.gif)

**Comment by plafosse** [comment]
The problem is that navigation is stealing the focus on single click. Current thought is to navigate when on mouse button release if there is no selection.

**Comment by bambu** [comment]
I personally would prefer to double click instead of single click. There have been more than a few times that i go to copy something that is/looks like a valid address or click into the console at a spot that has something that has an address and navigation has gone somewhere completely different that what I am working on.

**Comment by psifertex** [comment]
We debated that, but we should probably change the log window behavior as well if we do that. And browsers seem to handle single-click behavior just fine while also allowing selection so it seems like there's a way to make it smooth. But I wouldn't say we've totally ruled out double click either.

**Comment by psifertex** [comment]
Resolved (with single click for now, would be easy to change later) in 2608 and newer.
