### ISSUE TITLE
Feature Resquest: Show API calls in the log.

### ISSUE THREAD

**Issue by Ricx8** [Vector35/binaryninja-api#2260]
It would be nice to add an option that once enabled it shows the API call that were made in the UI. 
For example:
  If I right click in a value and click "Display as... > Binary" It would show the API call that did that.

A feature like this would make it better for developers to understand the API better. It will also allow people to make scripts more frequent since it avoids the need to go though all the Documentation only to understand how to do a simple task.

In the VFX industry, companies like Maya from Autodesk implement this. Basically all the things made in the UI has a respective function in mel/python so they are able to show it. In big projects this is a very useful feature since it can help to the automation of the work.

I don't know if this is possible. If it is and is there anything I can help to make it happen I can take hour to develop it I just need to know if it is possible for me to do it only with this repository.

**Comment by psifertex** [comment]
We've considered doing this for actions in the action system though that's not the same as the raw APIs. It would let you know how to trigger the same action via a script though which probably achieves the same result. We've wanted to do that as well since we could log events and if customers want to submit telemetry about how they're using the product to make it better they could use that to opt-in as well. 

Doing via the raw APIs probably isn't feasible but I will talk to the rest of the team since it would be nice to have.

**Comment by Ricx8** [comment]
Thanks! and like I said, If you need someone I would be happy to help"

**Comment by psifertex** [comment]
Sadly, this isn't a change that could be done in any of the open source sides, would require work done in the core. That said, if we do implement and need testers and help, will definitely let you know.

**Comment by psifertex** [comment]
So we've talked about this one as a team and we've decided we will not be making this change because of the questionable benefit and potential performance implications. That said, I'm going to be creating a separate issue that will be tracking the action system logging I mentioned above.

Ultimately if there is documentation missing or things you couldn't find how how to do, please file those as separate issues so we can update the associated [api documentation](https://api.binary.ninja/) and [user documentation](https://docs.binary.ninja)
