### ISSUE TITLE
Ship QtQuickControls with PySide2

### ISSUE THREAD

**Issue by defunctio** [Vector35/binaryninja-api#2289]
Including QML's QtQuickControls for utilization with QtQuickWidget would be a nice to have.

**Comment by defunctio** [comment]
and QUiLoader from PySide2.QtUiTools

**Comment by psifertex** [comment]
FYI, no promises but there's a chance we end up using QML instead of HTML reports and removing the qwebengine and being able to go straight to qt6 soon. If we do that 1) all UI plugins would need to be updated because qt6/pyside breaks everything, and 2) you'd be getting all these controls for sure sooner rather than later. Still some testing to be done to know for sure, but just letting you know.

**Comment by D0ntPanic** [comment]
Qt Quick will not be usable in future builds, as it conflicts with our use of Qt Widgets in Qt 6. It is being removed from availability in C++ UI plugins as well. It is not planned to add these until Qt does not force use OpenGL in order to use Qt Quick in a Widgets application.
