### ISSUE TITLE
Incorrect MLIL variable reuse

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2304]
2672-dev Win10 Personal

![image](https://user-images.githubusercontent.com/8716677/110274885-bb512500-7f84-11eb-97ed-1dcad0a69374.png)

At 5, you see a size being loaded from the 4th parameter, then compared against 0x100 at 8.
Then at 16, this variable is reused for another load from a stack local. This variable is compared against the integer value KEY.

These are different variables, but MLIL is aliasing them to the same thing. This isn't _too_ bad in MLIL, but then when I look at HLIL I see `if (key_sz.d u> 0x100 || (key_sz.d u<= 0x100 && keystore_handle s> 0 && key_sz.d != 'KEY'))` which is not correct.

**Comment by plafosse** [comment]
Could you possibly share the binary? Or at least the entire function in SSA form?

**Comment by yrp604** [comment]
Yep, same attached bndb as this issue:

https://github.com/Vector35/binaryninja-api/issues/2307#issue-825386754

**Comment by rssor** [comment]
In this case, the `key_sz` variable was not being split because of the inferred arguments to the `printf` call at `0xe0322a8`, since the value in `x1` at that call site could have come from both definitions, resulting in us assuming they are the same variable/type.

In general when faced with a variable behaving like this, switching to SSA form and finding a phi that both versions go into will lead you to the use that is suppressing the variable split. It's usually just a matter of us not having enough information yet to conclude that it's safe.

Using call type overrides to fix up the printf call site manually fixes the issue.
