### ISSUE TITLE
opening wide functions for the first time should center on the start address

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#231]
Clicking on a function always takes you to the top left of the function view window. If functions are particularly "wide", this can mean this view is entirely empty and you need to scroll right to find the functions first basic block.

Clicking on a function window from the list should always take you to a view where you start at the functions first basic block.

**Comment by psifertex** [comment]
It's slightly more complicated than that -- if you were previously looking at a different spot in a function, jumping back to that function takes you to the same spot you were looking at. For example scroll to where you want to look and then double click another function in the side-bar, then back to the first. It should take you back to where you were looking in the first function.

That said, definitely agree that upon first opening a function if there isn't a saved location it should take you somewhere smarter.

**Comment by psifertex** [comment]
Actually, now that I look at it more closely, we should do this already in most instances. I suspect maybe what you're seeing is side-effect of the auto-analysis not completing yet and so our attempts to find a good place to start in the function fail. Ironically, because of the behavior I described above -- even if you navigate to that function again after auto analysis completes (as an aside, navigating to any function automatically moves it to the top of the auto analysis queue), because you had a previous view (off to the side), it saves it.

**Comment by yrp604** [comment]
Makes sense, thanks.

**Comment by psifertex** [comment]
Hmm, actually, when I just tried it (xnu kernel was a good suggestion), the view loaded in the upper left, but when I clicked away to another function and clicked back it did actually work correctly for me. Can you double check and see if maybe you were navigating within the view and then switching away/switching back which might have caused it to save your new view?

**Comment by yrp604** [comment]
Yes, I can replicate this behavior. Load the kernel, find a large function (PE_parse_boot_argn). Open the window, get bank screen. Navigate away, come back and get first basic block this time.

So, I guess the bug is I expect on first click to see the first basic block. Subsequent ones work as expected.

**Comment by D0ntPanic** [comment]
Fixed in dev
