### ISSUE TITLE
selecting a function comment produces invalid data references

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2374]
<img width="1224" alt="Screen Shot 2021-04-14 at 3 23 41 PM" src="https://user-images.githubusercontent.com/140215/114767245-65b32980-9d35-11eb-8185-3c090f71b7fa.png">

**Comment by jeffli678** [comment]
The nature of this issue is the xref query is based on address, not token. And selecting a function name (at the start of the graph) shows all the outgoing data refs of this function. So there are two possible improvements here: 1). filter based on the selected token to avoid showing xrefs when it should not; 2). decide if we really show all outgoing data xrefs when a function is selected

**Comment by CouleeApps** [comment]
This was an issue with function comment lines never having their address set, and defaulting to 0. Fixed in 2.4.2900-dev.
