### ISSUE TITLE
Binaryninja commits suicide when partition is full

### ISSUE THREAD

**Issue by jephthai** [Vector35/binaryninja-api#2462]
**Describe the bug**
I had not run binary ninja in awhile, and when it started it downloaded a new version.  While examining a binary, my partition filled up.  At some point, I quit, and when I started binja the next time, it ran, but popped up an error message about being unable to overwrite the `binaryninja` executable.  After quitting later, and attempting to restart, I found that the binary was gone. 

I do not know how to get a copy of the right binary now.  I tried copying the `binaryninja` binary from the demo, hoping it would recognize my configured license, and update to a good version.  But that did not work.  The download link I got when I last updated my license has expired, so I can no longer download a working copy.

**To Reproduce**
I cannot reproduce this bug, because binaryninja has deleted itself.

**Expected behavior**
I would have expected binaryninja not to delete itself until it had successfully unpacked the replacement binary.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Version 18.04

**Additional context**
I would like to know how to at least get a working licensed copy back so I can run it, but I thought I'd report this as a bug because it's a pretty frustrating behavior.

**Comment by jeffli678** [comment]
If you license is still valid, you can do through https://binary.ninja/recover/ to get the latest version of BianryNinja.

**Comment by jephthai** [comment]
Oh hey, thanks!  That works, and I have it back up and running now.  I appreciate it!

**Comment by psifertex** [comment]
Unfortunately the way our installer works is by moving itself in place on top of the old version -- this makes restart times with updates much faster on Ubuntu and MacOS (Windows can't do this and has a second-stage updater that runs after restart that is much slower) but it does have the downside that it's possible for an install to be corrupted on update. 

Because the only time you can have an auto-update run is when you have a valid license (and thus the "download the latest dev or stable" recovery link Xusheng pointed to above will work) we tend to consider these low-priority issues because there's just too many ways that files can become corrupted/interrupted/etc and it's not worth the high level of effort to develop and test all the possible failure scenarios (bad network? file system fills up, file system becomes read-only, bad memory flips a bit in a file, after verifying the download and attempting to do the overwrite the file system fails half-way, etc) when the fall back is fast and easy.
