### ISSUE TITLE
Keybindings to unfocus focused things

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#2574]
Examples:
- Hit `t` to focus the fancy new types sidebar. Now how do I get focus back to the main IL/disassembly view? Esc starts navigating back in the _main_ view rather than first changing focus.
- Hit `t`, then `Ctrl+F`, to search for types. Now how do I get focus back to the actual types?
- Hit ` to open the python console. Now how do I get back to the main IL/disassembly view (without closing the python console)?

**Comment by psifertex** [comment]
Thanks -- this is on my personal wish-list too, meant to file it. For the second case there is a work-around. I've been mapping the specific panels to CMD-1 instead of the bookmark hotkeys. That lets me have a global "focus the specific sidebar panel I want". That said, there is another minor glitch with the focus where once you focus the sidebar you have to hit tab once to focus the inner widget. The xref panel already has code to handle it, just needs to be added to the other panels as appropriate so you can immediately do stuff like up and down (though ctl/cmd f does work)

**Comment by psifertex** [comment]
The actual workflow here I think is "hotkey to focus the main graph". That will solve all of these cases other than the second which as I said, a dedicated "focus this panel" hotkey fixes.

**Comment by D0ntPanic** [comment]
Added action with default key bind of Ctrl+M/Cmd+M to focus the main view from anywhere. This should allow the user to navigate by keyboard from any state.

Added in build 3182.
