### ISSUE TITLE
remove_auto_segment does not persist 

### ISSUE THREAD

**Issue by endeav0r** [Vector35/binaryninja-api#2601]
**Binary Ninja Version**
2.4.2950-dev

**Describe the bug**
When I call bv.auto_remove_segment, save my bndb, and open it back up, the removed segment reappears.

Additionally the removed segment remains in the feature map, even after refreshing the feature map.

**To Reproduce**
1. Open a raw binary with “Open with Options.”
2. Manually put all the parts of the raw binary where they need to be with add_user_segment.
2. Remove the original segment with auto_remove_segment.
3. Save bndb
4. Close Binja
5. Reopen bndb

**Expected behavior**
The original segment is gone.

**Observed Behavior**
The original segment re-appears.

**Screenshots**
N/A

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2950
 - OS: Ubuntu 20.04
 - Version [e.g. 20.04]

**Additional context**
Your issue template asks for binary ninja version twice :)

**Comment by bpotchik** [comment]
'auto' segments are created by the loader. When reopening a file or database the loader recreates the auto segments. This is why the API `remove_auto_segment` does not persist.

With the new MemoryMap API and Segment Model, we now provide a mechanism to disable segments. The new segment map, with the disabled segment persists as well through save/load. For example:

Show the current memory map and names for each object:
> print(bv.memory_map) 

Disable a segment by name:
> bv.memory_map.set_memory_region_enabled('origin<ELF>@0x9028', False)

Fixed in `4.2.5758`.
