### ISSUE TITLE
Save analysis to BNDB

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#268]
We need to save the results of our analysis to the BNDB.

**Comment by D0ntPanic** [comment]
Analysis data is now saved to the database, but we do not yet have code to generate IL only on demand.  Because of this, the binary will still analyze all functions when loading a database.  However, since the important details of the analysis is saved to the database, going to any function in a loaded database will have the correct analysis immediately and will get ready for interaction on the priority queue.  In the future, when true on-demand analysis is implemented, the binary will not need to analyze all functions on startup except when updating to a new analysis version.

Cross references are not yet saved to the database, but will be in the future. They will be regenerated automatically when loading a database.
