### ISSUE TITLE
Screen drawing issue with command palette and feature map

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2709]
**Binary Ninja Version**
2.4 dev

This could be a Qt issue. Feature map is not redrawn after the Command Palette is cancelled
![image](https://user-images.githubusercontent.com/10556585/137492035-5a193582-598b-4448-bbc6-4578a7b3a7fd.png)

**To Reproduce**
1. Set Feature map in horizontal orientation
2. trigger command palette 
3. hit `Esc`

**Comment by fuzyll** [comment]
This is much less of an issue on 3.4.4271, but still kind of weird. The behavior now is that the contents of the command palette are 'ghosted' on top of the feature map very faintly.

**Comment by fuzyll** [comment]
It turns out that, if you did not set the feature map colors yourself in a theme, we used an alpha of 225 to "mix" an existing theme color with the background. Unfortunately, this appears to have had the side-effect of not completely drawing over other controls when the window reflowed (e.g. a sidebar widget closing).

I have now mixed the colors into a solid, so builds >= 4.0.4878-dev should no longer see this effect happening on themes that rely on the defaults.
