### ISSUE TITLE
Allow the user to disable autodetection of function types from mangled names

### ISSUE THREAD

**Issue by XMPPwocky** [Vector35/binaryninja-api#2763]
**Is your feature request related to a problem? Please describe.**

Yes- this is primarily motivated by a desire for a convenient workaround for #2757 and possibly similar issues.

Would also come in handy when encountering obfuscated binaries which attempt to mislead analysis by providing mangled names which do not match the actual function type at all.

**Describe the solution you'd like**
In the "Open with Options" UI, provide a checkbox, default-checked: "Automatically set function types from mangled names". When checked, behavior is the same as it is today. When unchecked, Binary Ninja will not use name mangling information to set function types.

Expose the same as an option for `BinaryView.get_view_of_file_with_options`.

**Describe alternatives you've considered**
The main alternative would be fixing #2757; however, this may be difficult because name mangling does not differentiate between static and non-static methods. However, this feature would still be useful when encountering obfuscated binaries which use name mangling as an anti-analysis technique.

As a user, it may be possible to unset the type of all imported functions through the API and then rely on analysis alone to redefine them; this is somewhat unreliable, though, and fragile.

**Comment by raymontag** [comment]
I would like to propose an alternative solution here. For me, the demangled function signatures worked great in most if not all cases. But as already described in #2757 it can happen that the `this` parameter is just missing. An alternative solution could be to add an option to the context menu to add this parameter based on the class/namespace. Because my main problem is, that it is just inconvenient to open the function signature manager and add a `struct foo::bar* this` by hand for every analysed function. Maybe it would even be possible to create structures for class analysis on the fly.

**Comment by plafosse** [comment]
We've implemented a setting to allow you to disable recovering types from mangled names. `analysis.extractTypesFromMangedNames`  As of 3.2.3746
