### ISSUE TITLE
comments are badly misplaced in linear view

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#2792]
**Binary Ninja Version**
Version 2.5.3129-dev (Build ID 9038e9f1)

**Describe the bug**
A comment placed on an instruction appears somewhere that doesn't make sense.

**To Reproduce**
From some quick tests it seems like this happens in a broad range of circumstances, but here's a specific way to reproduce.

1. Open [this file](https://github.com/Vector35/binaryninja-api/files/7740127/what.zip) and go to `_test`.  It decompiles as follows:
```
00003f50      if (arg1 == 0)
00003f5c          _bar()
00003f54      else
00003f54          _foo()
00003f6c      return 5
```
2. Add a comment at address 0x3f54.
3. Go to linear HLIL view.
4. Huh??
```
00003f50      if (arg1 == 0)
00003f54          // test comment
00003f5c          _bar()
00003f54      else
00003f54          _foo()
00003f6c      return 5
```

**Expected behavior**
The comment should be after `else` or `_foo()`.

**Version and Platform (required):**
 - Binary Ninja: Version 2.5.3129-dev (Build ID 9038e9f1)
 - OS: macOS
 - Version 11.6

**Additional context**
This is not the same as #2728, which is about comment placement not being sufficiently granular.  In this case the placement is just wrong.

**Comment by CouleeApps** [comment]
This has been addressed as of 2.5.3158-dev and should hopefully be usable again. Notably, comments should no longer be misplaced in a block when there are large jumps in the address (eg inside a conditional or switch). Additionally, addresses which appear in multiple disjoint places in HLIL will have the comment applied to all of those places. This is still suboptimal, but at least now the comments will show up where they're supposed to.

There's a longer-term Hard Problem to solve for this to be perfect, as mentioned in #2728 / #1598, of trying to serialize consistent locations in HLIL instructions (and MLIL, LLIL) so that comments don't move or disappear when analysis changes. I'm not sure if something like that is possible yet, but this specific issue should be fixed.
