### ISSUE TITLE
Process Icon Missing on Ubuntu's Dock

### ISSUE THREAD

**Issue by h0nus** [Vector35/binaryninja-api#2795]
Binary Ninja Version: 2.5.3136-dev Personal,  eae2de0
Platform: Ubuntu 20.04.3 LTS

Even if i start it from cli (./binaryninja) or from a custom .desktop file, no icon will show on running process.
Is that a bug from my clean os configuration ? or icon themes? or maybe because it's dev branch?

![image](https://user-images.githubusercontent.com/23401728/146915583-38be6b23-7636-409f-b024-55071ed2ccc3.png)

As you can see first one is my .desktop file
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=BinaryNinja
Exec="/home/user/.local/share/bninja/binaryninja" %U
Icon=/home/user/.local/share/bninja/docs/img/logo.png
Categories=Application;Security;
```

while the second one is just the process running and it won't show up.

Location of installation is: `/home/user/.local/share/bninja`

Other than that, i'm loving your product!

**Comment by psifertex** [comment]
You can see where I tweaked the linux-setup.sh script:

https://github.com/Vector35/binaryninja-api/blob/dev/scripts/linux-setup.sh

So that it automatically reloads: https://github.com/Vector35/binaryninja-api/commit/0e10983e83fbd5980aa4d2aed06057c3676bf402#diff-3a9e5ff14394d4155c7ec8fde0afde780e19b5ec6b96cea99b7a8148c7735071

Note that script is already available in the `scripts` folder -- does that help when  you run it? I do see the appropriate icon when I use it: 

<img width="1673" alt="Screen Shot 2021-12-21 at 1 44 09 PM" src="https://user-images.githubusercontent.com/140215/146982026-e9645aa7-5c83-4e30-ad4f-21e960287538.png">

**Comment by h0nus** [comment]
Yep! worked like charm! thank you so much, didn't even know this script existed!
Thanks again! <3
