### ISSUE TITLE
stuck on "loading" of some functions

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-api#286]
https://gist.github.com/7f685239e314f8d353f8c873e3d64519

"main" is stuck on "loading" and the disassembly is never shown

![!img](http://i.imgur.com/8qhECcL.png)

**Comment by crowell** [comment]
looking at my cpu usage, looks like the analysis is just totally messed up and is infinite looping on me here...

**Comment by psifertex** [comment]
Thanks for the sample. There is one big we know about that is under way that results in loading behind shown even after a function has been identified and that will get picked up by another bug fix in progress. 

This sounds like it's something different with the CPU spinning so we'll take a look in a debug build and see if we can root cause it.

**Comment by D0ntPanic** [comment]
This is caused by endless auto analysis updates from the jump table detection.  Created a minimal binary that exhibits the issue.

[jump_loop.zip](https://github.com/Vector35/binaryninja-api/files/344297/jump_loop.zip)

**Comment by D0ntPanic** [comment]
Fixed in dev
