### ISSUE TITLE
Headless Install fails on Ubuntu 18.04, python3.6

### ISSUE THREAD

**Issue by rchildre3** [Vector35/binaryninja-api#2907]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233 Headless
- OS: Ubuntu Linux
- OS Version: 18.04

**Bug Description:**
`install_api.py` fails to find `dataclasses` compatibility shim when using Ubuntu 18.04 default Python 3 implementation (Python 3.6)

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. `download_headless.py`
2. unzip
3. `linux-setup.sh`

Note: the import error is hidden in `validate_path` as the code assumes all `ImportError`s are because the API package is not installed but inspecting the `ImportError`'s attributes shows `dataclasses` module unable to import

**Expected Behavior:**
The `dataclasses` compatibility shim is imported.

**Comment by fuzyll** [comment]
Hey, sorry about that. In our pre-release testing we did `pip install dataclasses` to install the workaround package for 3.6 and this seemed to work. The actual `dataclasses` functionality is a python 3.7 thing. We probably should add this to our documentation, so thanks for pointing this out.

If this doesn't work for you, please let me know and I can handle it as a support request. But, we're planning to drop Ubuntu 18.04 as a supported platform by our next release. So, this is unlikely to be fixed just to support an aging platform reaching end-of-life.

**Comment by rchildre3** [comment]
Fair enough, but that does raise some more questions

1. As mentioned can the minimum requirements be documented for:
    1. Python interpreter
    2. pip dependencies (if any)
    3. Native dependencies (had to add `libdbus-1-3` to my Dockerfile)
2. Is there a way for users to remain on the `2.x` releases or are they expected to move to the `3.x` branch?
3. The for the API could be bolstered in `validate_path()` to check that the caught `ImportError` is actually coming from missing the `binaryninja` module and not some submodule (like `dataclasses`)
4. If the `dataclasses` module used for testing came from the PyPI backport, what functionality does [the shim provided in-tree](https://github.com/Vector35/binaryninja-api/blob/6812c97/python/dataclasses.py) provide?

**Comment by psifertex** [comment]
This script is merely a helper that is not required. Simply setting your python path environment variables or manually making a PTH file is also sufficient for headless usage. 

The core and API are tested and expected working in whatever python is supported in the official Ubuntu support. So the dependencies are rather indirect as a result based on that:

https://binary.ninja/faq/#supported-platforms

We are dropping 18.04 in the next stable release and migrating our build infrastructure to 20.04 so we do not expect to maintain support for 18.04 for long in future dev releases. Note that this is at least partially true because Py 3.10 is starting to be standard in some distros and has an unfortunate dependency chain between python and QT that makes compatibility with both Ubuntu 18.04 and Py 3.10 problematic. That's one reason we are looking forward to ending 18.04 official support.
