### ISSUE TITLE
bndb missing strings

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2942]
Binary Ninja Version: 3.0.3233, e250d0a3
Platform: Ubuntu 20.04.3 LTS

Steps to reproduce:
1. Open a binary in binaryninja gui
2. Observe that the analysis found strings (gui or python console bv.get_strings())
3. Save the bndb object to disk
4. Open the bndb from #3 in the gui. Observe that the gui strings list is empty.  Python console bv.get_strings() -> [].

It appears that strings are NOT being saved to the bndb object.

**Comment by hanssl** [comment]
https://github.com/Vector35/binaryninja-api/issues/2796#event-5946221757

**Comment by CouleeApps** [comment]
Looks like this is due to a few things:
1. Strings are not stored in the bndb 
2. When loading a freshly saved bndb, the analysis cache is still valid so analysis (including string searching) is not run

Workaround for now: when the strings don't show up, use Command Palette -> Reanalyze to force reanalysis of the binary, including strings.

Proposed fix steps: either store strings in the bndb or run string analysis on open even if the rest of analysis is completed already (via cache).

**Comment by D0ntPanic** [comment]
Fixed in build 3257
