### ISSUE TITLE
Tags During Analysis Difficult to Use

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#2947]
Trying to used tags interactively during analysis is nearly impossible. The selection becomes deselected, and also jumps around as the list is updated.

**Comment by CouleeApps** [comment]
Couple points here:

The selection becomes deselected:
- Tag type selections seem to always be deselected when there are updates. That's a bug.
- Auto tag selections are deselected as analysis updates, this is probably due to the old tags being cleared and recreated during analysis. Not sure of a good solution to this.

The list jumps around:
- The list tries to stay scrolled at the same position by y position. This could be changed to stay at the same position by content visible (ie scroll down if the thing you're looking at moves down).

**Comment by bpotchik** [comment]
Fixed in `4.3.6462-dev`.
