### ISSUE TITLE
Intrinsics with wrong output

### ISSUE THREAD

**Issue by xire-** [Vector35/binaryninja-api#2963]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3253-dev Personal
- OS: MacOS
- OS Version: 12.2

**Bug Description:**
Intrinsics with a register output don't generate the correct LLIL, the register used as output seems to be random (or no register at all?). 
I created a [minimal architecture plugin](https://gist.github.com/xire-/b6dab392f682d19bb2bc655f345ce459#file-intrinsics_bug-py) that reproduce the bug for me.

**Steps To Reproduce:**
1. Create new binary file and fill the hex view with some random bytes
![Screenshot 2022-02-14 at 11 25 11](https://user-images.githubusercontent.com/1334668/153846601-252fe637-cd51-4611-a753-5823d961dda5.png)
2. Make a function with Test Intrinsics architecture
3. Change to LILL view
4. Every `test_intr()` is assigned to a random register or no register at all
![Screenshot 2022-02-14 at 11 30 01](https://user-images.githubusercontent.com/1334668/153847427-ef48bb17-5853-4902-9456-fb940a31d290.png)

**Expected Behavior:**
`test_intr()` is always assigned to R0.

**Additional Information:**
While doing research on how to write an architecture plugin I [found someone else](https://github.com/whitequark/binja-i8086/blob/5f7c6efe86c50c3c58d10402cf35cb70f1b989b2/mc/instr/in_out.py#L51) that had the same problem and found a workaround. Unfortunately the workaround doesn't work anymore on 3.0 (API changes?)

**Comment by yrp604** [comment]
`il.intrinsic()`'s first argument is a list of register numbers, not il registers. This can be recovered via `bv.regs['R0']` in your example, and for R0 is 0. If you update the code to be `il.append(il.intrinsic([0], 'test_intr', []))` it will work as expected, though I suspect there is a better way to resolve the register index.

In general when you get non-deterministic output like that it will be due to passing a pointer where an index is expected and the type system not warning loudly enough.

**Comment by rssor** [comment]
This is a bug in the type annotation — the outputs should not be ILFlags/ExpressionIndex but RegisterType/FlagType.

**Comment by CouleeApps** [comment]
After 3.0.3270, the `intrinsic` function supports passing registers directly as a string like `il.intrinsic(['R5'], 'test_intr', [])` (instead of `il.reg('R5')` as you did in that example).
