### ISSUE TITLE
string cross-references don't include pointers in the data segment

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/binaryninja-api#303]
At the moment, its currently not possible in the beta version of Binary Ninja to view cross references to a string from the strings menu. This makes it very hard to track where strings are being used so that proper analysis of the corresponding function can be undertaken. Support should be added in so that it is possible for people to search for cross references to a string from the strings menu which would allow people to better analyse programs loaded into Binary Ninja.

**Comment by psifertex** [comment]
We do have string cross-references in the string view. When you select a string, any cross-references are shown in the lower-left.

There are three things that will impact though:

The first is that we search for strings similarly to `strings -a` so we find strings even if we don't necessarily identify a cross-reference to them in the code and there thus won't be any references in that instance, nothing to do about that one. 

Another related issue (which I've re-named this bug to be for since we've known about it, but I don't see an existing bug) is that we only find string cross-references in code as we're doing our recursive descent through the binary. Any pointers to strings that are themselves in the data segment aren't identified as cross-references ultimately to the string. 

Finally, there's a bug which I just found looking into this is that xrefs are updated for a string reference /after/ you navigate away from it. So if you click a string, then hit up or down, you'll see any potential refs for the one you intended. I've filed that separately under #304. This should be easy to fix.

**Comment by buildandcrash** [comment]
When you double click on the item of "string cross-references" that are shown in the lower-left it will take you somewhere in the same ListView of all strings but not to the code where it referenced from.

**Comment by nallar** [comment]
This is still an issue in the latest development version.

It makes working on binaries with indirect access to strings very awkward.

I thought it was working at some point but may have imagined that...

**Comment by Arcnor** [comment]
Adding my voice to this issue, string references inside the data section doesn't seem to be working at all.

**Comment by plafosse** [comment]
As of build 1.1.1385 we have the ability to create and display cross references from data. The current system works by adding a data cross reference for each DataVariable of type PointerTypeClass to the location that it is pointing at. This however isn't a complete solution as there are still frequently pointers that we don't recognize as such. I've created a new outstanding issue #1189 to track whats left to do.
