### ISSUE TITLE
binaryninja.Architecture.get_instruction_text should check it's argument's type

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#313]
`>>> import binaryninja`
`>>> binaryninja.Architecture["x86"].get_instruction_text([], 0)`
`(['pop     ', 'ebx'], 1L)`
`>>> binaryninja.Architecture["x86"].get_instruction_text({}, 0)`
`(['jpo     ', '0x7f'], 2L)`
`>>> binaryninja.Architecture["x86"].get_instruction_text(0x90, 0)`
`(['xor     ', 'dword ', '[', 'esp', '+', 'esi', ']', ', ', 'esi'], 3L)`
`>>> binaryninja.Architecture["x86"].get_instruction_text("\x90", 0)`
`(['nop     '], 1L)`

Is probably not an expected behavior.

**Comment by plafosse** [comment]
It is not general practice to check the types of each parameter passed into a function in python.  Yes this issue could be fixed by checking for str but we don't want to make this a requirement for all APIs. The docs (which may not have existed when this bug was created) specify that this parameter should be a string. I think think this should suffice.
