### ISSUE TITLE
remove "prefer" settings that no longer work due to save default layout

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3160]
See the comment on https://github.com/Vector35/binaryninja-api/issues/3154#issuecomment-1143116984

**Comment by jonpalmisc** [comment]
At a surface level this seems like a simple change, but it is complicated by a few things:
- Some of these preferences, namely `ui.view.graph.preferred` are not strictly irrelevant with the advent of layout saving. The formerly named setting is used in navigation code and is still relevant to an extent, which will require discussion on how these settings can be properly sunset.
- Other settings such as `ui.view.{graph,linear}.il` which set the default IL for a view are made irrelevant only if the user has a default layout. Until a default layout is picked, they are still used. Defaults need to be picked.

Needs more investigation and needs more discussion before making changes.

**Comment by psifertex** [comment]
In the meantime let's set an intermediate milestone of documenting that those settings "may not produce the desired effect if the user has saved a new default layout" which at least lets people know there might be an issue.

**Comment by bpotchik** [comment]
The prefer settings with current behavior are as follows:

`triage.preferSummaryView` - This works now. See #3154 
`ui.view.graph.preferred` - Required to dynamically determine linear vs graph view priority interface
`ui.view.linear.il` and `ui.view.graph.il` - Required for initial view state when opening new files
`ui.sidebar.openOnStartup` - Nothing appears to currently override this default setting.

I've updated the settings documentation to reflect the precedence where necessary.

Fixed in `3.1. 3757-dev`.
