### ISSUE TITLE
Save clean BNDB

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#317]
Also probably need a save BNDB w/o undo history.

**Comment by th0rex** [comment]
I don't know how much work this would be for you guys, but it would be nice if there would be any way to achieve this. I asked yesterday on slack about this and since then my database size has more than doubled (at 1.3GB now). I'm kind of afraid that there might be some other bug with big databases, which would make the database useless and me having to start over from scratch.

**Comment by plafosse** [comment]
This was added a prior to v2.1
