### ISSUE TITLE
Console input field should not navigate submission history when editing unsubmitted multi-line input

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3179]
**What is the feature you'd like to have?**
When editing multi-line text that has not yet been submitted, the console input field should not allow navigating input history with the up/down arrow keys.

**Is your feature request related to a problem?**
When editing multi-line input, it's way too easy to accidentally lose everything you just typed by pressing the up/down arrow keys one too many times and unintentionally navigating history. When doing lots of interactive scripting, this quickly gets frustrating.

**Are any alternative solutions acceptable?**
Alternatively, the input field could be changed to only ever navigate history with Ctrl + arrow keys or something. I imagine that would be easier to implement but (maybe?) slightly less intuitive in the single-line case.

**Comment by psifertex** [comment]
We don't plan to change this behavior however we _have_ fixed the problem of data being lost. Now when you navigate back down your previous input is saved therefore I'm considering the root cause solved. Not sure when this was fixed, I believe in the last stable or two due to some changes in multi-line input but it could have been a while ago.

**Comment by psifertex** [comment]
Actually, I'm going to mark it as solved and move to this release with the rename of the intended fix so it's more clear what changed.
