### ISSUE TITLE
Tags Sidebar is unusable during analysis

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3190]
**Version and Platform (required):**
- Binary Ninja Version: 2.4.2487-dev (if version is stable, please also test the latest development build via the "Update Channel" option)
- OS: [e.g. Ubuntu Linux]
- OS Version: [e.g. 20.04]
- CPU Architecture [e.g. x64 or M1]

**Bug Description:**
Please provide a clear and concise description of what happened.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to...
2. Click on...
3. Scroll down to...

**Expected Behavior:**
Please provide a clear and concise description of what you *expected* to happen.

**Screenshots:**
If applicable, please add screenshots here to help explain your problem.

**Additional Information:**
Please add any other context about the problem here.

**Comment by CouleeApps** [comment]
Do you have any more details? Does this happen with/without plugins on any files in particular? Does it happen on any file/every file/specific architectures?

**Comment by psifertex** [comment]
This is mostly fixed in builds >= 3655. 

There's one small issue which I'm going to file separately and track in another issue which I'll link here. Specifically, when tags are updating you cannot use the up/down arrow keys to navigate to the next item on the list. However you can use the mouse still meaning the impact is now low.
