### ISSUE TITLE
Missing C++ API for Type Libraries

### ISSUE THREAD

**Issue by SmoothHacker** [Vector35/binaryninja-api#3205]
**What is the feature you'd like to have?**
A C++ API for Type Libraries, similar to what's currently available in the [Python API](https://github.com/Vector35/binaryninja-api/blob/dev/python/typelibrary.py).

**Comment by fuzyll** [comment]
We don't have a C++ API available, but we _do_ have a C API for interacting with it: https://github.com/Vector35/binaryninja-api/blob/30d84ee263fea44a7fa686d86d1934e4782f8aaa/binaryninjacore.h#L5025-L5086.

I apologize: We don't currently have this documented anywhere, but you should be able to look at the Python API as an example of how to interact with it.

Keeping this open, though, because we really should have a C++ API.

**Comment by CouleeApps** [comment]
This has been completed as of 3.2.3890-dev.
