### ISSUE TITLE
`?` at the end of a python command doesn't work for properties

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3246]
**Version and Platform (required):**
- Binary Ninja Version: 3.1-dev

**Bug Description:**
type `bv.functions?` in the python console. This will spit out an error instead of the docstring.

**Comment by galenbwill** [comment]
Similarly, for properties with primitive types, it will print the docstring of the primitive type:
```
>>> current_function.start?
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4
0x100fb5e9c
```

**Comment by CouleeApps** [comment]
Couple of things here:
`bv.functions?` returns an error if you don't have a bv... that's not really a bug considering bv is None
`bv.functions?` states `No documentation found for b'bv.functions'` because `FunctionList` has no docs. Maybe we want this to resolve `bv.functions?` to `BinaryView.functions?` which gives docs on the method on the actual class itself. 
Similarly, what Galen said about `current_function.start?` applies. We may want to resolve that to `Function.start?` which does give the correct docs.

So my guess for how to implement this is: have `bninspect` cut off the last property, then evaluate the source and query documentation about the property on the source's _type_, not the _instance_.
