### ISSUE TITLE
Sync cursor between views

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#332]
It would be extremely helpful to be able to get the file offset that corresponds to a given function or instruction in addition to its virtual address.

**Comment by plafosse** [comment]
I believe what you want is the ability to have your cursor sync'd between views.  So currently you can go to the `hex editor` pane and look at it with the `Raw` view, which will show file offset rather than virtual addresses. The issue though is that we don't yet support syncing your cursor between the different views. I am going to edit your title and mark as an enhancement.  Let me know if you had something else in mind.

**Comment by bdarmofal** [comment]
No, I was asking for a mechanism to get the file offset for the current instruction from a Python script.

**Comment by plafosse** [comment]
This is a dupe of #24
