### ISSUE TITLE
add convenient getter/setter for function symbol names from python API

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#334]
I haven't been able to find a mechanism to read or write function names / labels from a Python script.  Please add one.

**Comment by psifertex** [comment]
There is one -- was just replying to your email, but this is a better place to document it anyway, so thanks for filing it. 

I first should note that your question made us look at the current process and realize it's far more cumbersome than it could be and we plan to create some python helpers (likely getters and setters on `function.name` that handle it for you). Here's the current method:

```
import binaryninja
bv = binaryninja.BinaryViewType['Mach-O'].open('/bin/ls')
bv.update_analysis_and_wait()
address = bv.functions[0].start
name = "firstFunction"
longname="this is the first function"
symbol = binaryninja.Symbol("FunctionSymbol",address,name)
bv.define_user_symbol(symbol)
```

Also, as a reference, valid symbol types are:
```
    0: "FunctionSymbol",
    1: "ImportAddressSymbol",
    2: "ImportedFunctionSymbol",
    3: "DataSymbol",
    4: "ImportedDataSymbol",
```
(those are also available via binaryninja.FunctionSymbol instead of the string in the first argument to Symbol)

Anyway, I'm going to leave this ticket open but rename it to track the creation of the easy getters and setters.

**Comment by psifertex** [comment]
Also, to retreive the current name, it's just:

```fn = bv.functions[0
fn.symbol.name```

That will probably be accessible via ```fn.name``` once we close this ticket with the new method.

**Comment by psifertex** [comment]
I added some small helpers to make this process easier (https://github.com/Vector35/binaryninja-api/commit/b6b76645f0a5e7e631363c4b4ae6383993669abf). Note that you won't be able to pull all the changes from that dev branch and have it work with the latest beta, but if you want to just cherry pick that specific commit into your local `__init__.py` you are more than welcome to do so, or you can wait for the next update.

With the new code, there is now just a `function.name` that you can get the current function name with, or set a new name with. If you want to delete a user name, just set it to `None` and it will revert back to the auto-analysis symbol instead.
