### ISSUE TITLE
Aggressive return value optimization

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3348]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3469
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Steps To Reproduce:**
1. Open attached executable in BN
2. Wait for analysis 
3. Goto `sub_18003eb30`
4. See that `sub_1800315b0`'s return value does not used. 
5. Also see that `memset` at `0x18003ebfc` is ignored at HLIL & Pseudo-C. It is visible in < HLIL.

![Capture](https://user-images.githubusercontent.com/109607896/182560337-384310a1-1601-412d-9b88-d9b9e175eb95.PNG)

I think it is notable that before analysis, `sub_1800315b0`'s return value is used in HLIL & Pseudo-C. Maybe it is because `sub_1800315b0` always returns `data_1805c6d28` and `sub_18003eb30` always uses `data_1805c6d28 + 8` which is `data_1805c6d30`. So, decompiler simplifies it, but I guess it is a bit aggressive.

[file.zip](https://github.com/Vector35/binaryninja-api/files/9249389/file.zip)

**Comment by bpotchik** [comment]
Fixed in `3.1.3623`.

I've added a new analysis setting to control whether return value propagation occurs for constants. Disabling the `analysis.experimental.returnValuePropagation` setting should yield the expected results.

For the provided sample:
![3348_before](https://user-images.githubusercontent.com/29309548/184217049-27937c46-8049-4401-a713-4af489ce08d2.png)
![3348_after](https://user-images.githubusercontent.com/29309548/184217064-891bec66-9c45-4eca-8811-2b42f3933ca1.png)
