### ISSUE TITLE
Ability to move memory map to a generally wider area

### ISSUE THREAD

**Issue by jrozner** [Vector35/binaryninja-api#3488]
**What is the feature you'd like to have?**
The ability to move the memory map into a generally wider area.

**Is your feature request related to a problem?**
The left rail is usually not very wide because most of the content in it is fairly narrow and you want the main area to have the majority of the space. The memory map is very wide because of the many columns in the table. This usually requires dragging it wider to look at then bringing it back to the normal width to actually use Binja.

**Comment by fuzyll** [comment]
Honestly, we should probably just move it to a regular pane and remove it from the sidebar. It's pretty awkward living over there. Tagging #3425 as we should tackle this when that issue is resolved.

**Comment by fuzyll** [comment]
Assuming the build doesn't fail on Windows because of some C++ thing I did, this should be done and available on builds >= 3.6.4620-dev now.

I know the comment above said I thought we should remove it from the sidebar, but that's not what we decided on implementing. It now exists as both a sidebar and a pane item, just like Strings view and the new Type Browser.
