### ISSUE TITLE
Merging variables made return value lost

### ISSUE THREAD

**Issue by matthewfarrellex** [Vector35/binaryninja-api#3512]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3742-dev
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
I've merged hEnc and rbx_4 and fopen lost its return value.

**Screenshots:**
Before:
![before](https://user-images.githubusercontent.com/98181390/194938397-e016ccb0-7a6e-4c81-bcde-181a6f144a30.png)
After:
![after](https://user-images.githubusercontent.com/98181390/194938409-80f93446-6cb8-4f60-a508-7367dbb9be1d.png)

**Additional Information:**
`fopen` function type: `int32_t* fopen(char const* FileName, char const* Mode)`

File: 
[file.zip](https://github.com/Vector35/binaryninja-api/files/9748439/file.zip)

**Comment by psifertex** [comment]
What offset is this? 

Also, was the other variable in the "possibly unsound" section? If so, that's entirely possible that's expected behavior though I don't know enough about that system to know for certain why it would looking at just this snippet. 

Also, I don't know if it matters but did you try merging from the other direction? IE, merging hEnc into rbx_4. As I said, I haven't used that feature a whole lot yet since it's so new so I'm still learning about it. :-)
