### ISSUE TITLE
Convert to Nop (x86, windows) broken

### ISSUE THREAD

**Issue by Kharos102** [Vector35/binaryninja-api#3555]
Binary Ninja Version: 3.2.3782-dev Personal, cd26bdb3
Platform: Windows 11 Version 2009

Trying to convert a jmp to nops.

Expected behavior: Convert 5 bytes from the jmp operation into NOPs

Actual behavior: Seems to affect 7 bytes instead or something, messes with disassembly

![after_patch](https://user-images.githubusercontent.com/16039802/196609113-a476f1fe-0b4a-4a02-afbb-933a9b4a65b5.png)

![before_patch](https://user-images.githubusercontent.com/16039802/196609108-b9165223-03e4-40ff-9c6f-bd38040e950d.png)

**Comment by psifertex** [comment]
Something looks off about that binary. Is it 32bit or 64bit? The address for the jmp looks like BN thinks it's 64bit but the instructions are all pure 32bit. I suspect you're seeing a bug as a result of a different default arch and the arch of that function. Can you share the binary? Patching jmps normally works fine on both 32bit and 64bit.

**Comment by Kharos102** [comment]
It appears 32bit, all register access follows 32bit and the Triage shows 32.

Heres the link to the binary (password is "infected" without quotes), note this is a sample of GrandCrab malware so keep that in mind and don't run it.
[grandcrab_malware(infected).zip](https://github.com/Vector35/binaryninja-api/files/9831777/grandcrab_malware.infected.zip)

**Comment by psifertex** [comment]
Ahh, ok, so the issue here is that bit of code is dead code and it's never going to be run and is just obfuscation. However, it partially overlaps with other real code. Note how both of the JNE and JE above will _never_ result in you falling through to the JMP instruction. 

However, if you try to patch BN, and it overwrites all five bytes of the JMP instruction you're also overwriting some other instructions that you don't want to patch. So it's not a bug, just a result of BN doing what you ask it to having unintended side-effects.

I would just ignore it, but if you need to fix it, just patch the previous JE to JMP instead since that more closely follows what the actual execution would always do. You need to make sure you choose the right JMP encoding so using something like:
`jmp short $+5` 
will get you:
![Screen Shot 2022-10-20 at 2 52 59 PM](https://user-images.githubusercontent.com/140215/197033532-fc84458b-777d-4494-8bfa-6cc2043be298.png)

**Comment by Kharos102** [comment]
Oh the confusing part is Binary Ninja showing multiple instructions using the same opcode, how is this not a bug though?

It uses the same opcode to show jmp and pop eax and also the last jmp eax, i'd assume its wrong to show multiple instructions based on the same hex bytes and not even show a warning about it?

**Comment by psifertex** [comment]
This not a bug that's a feature! That's something other tools _can't_ handle but it does happen in real-world obfuscations and both paths can be taken. 

Both are equally valid and correct possibilities. Well, in this case they're not both possible only because of the conditional branch pair above, but generically this is actually a real advantage BN has over most other tools that can't handle that.

**Comment by Kharos102** [comment]
True, I think my only complaint is it wasn't obvious it was doing this, maybe I'm too used to other tools where they don't :P

**Comment by psifertex** [comment]
Yeah, I wouldn't be against some sort of visual indicator but it's a bit tricky because it would only apply to disassembly and I'd have to think about a way to do it that isn't distracting and actually gives people information versus just being distracting without being intuitive.

**Comment by Kharos102** [comment]
There's already a question mark on the original JMP to tell me the JMP target is invalid, probably accurate to add the same question mark to instructions that come from the same bytes?

TY for the realization on this though
