### ISSUE TITLE
`BinaryView::GetDataReferencesFrom()` always empty?

### ISSUE THREAD

**Issue by cblichmann** [Vector35/binaryninja-api#3559]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3469 / 3.2.3782-dev
- OS: Debian
- OS Version: Bookworm
- CPU Architecture: x64

**Bug Description:**
In the BinExport C++ plugin, I'm trying to use `BinaryView::GetDataReferencesFrom()` to obtain data references from a given virtual address. Specifically, to implement proper support for exporting switch jump tables.
However, even when iterating over _all_ instructions in a binary, `BinaryView::GetDataReferencesFrom()` always returns an empty vector. `BinaryView::GetCodeReferencesFrom()`, however, has both code and data references (with no way to easily distinguish the two).

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
```c++
// Pseudo C++
for (const auto& func : view->GetAnalysisFunctionList()) {
  for (const auto& bb : func->GetBasicBlocks()) {
    uint64_t last = 0;
    for (uint64_t i = bb->GetStart(); i <= bb->GetEnd(); ++i) {
      uint64_t insn = i;
      if (bb->GetInstructionContainingAddress(insn, &insn)) {
        if (insn == last) {
          continue;
        }
        last = insn;
        std::vector<uint64_t> data_xrefs = view->GetDataReferencesFrom(insn);
        if (!data_xrefs.empty()) { /* log here,e tc. */ }
      }
    }
  }
}
```

**Expected Behavior:**
I expect each address to have the same data references that I can see in the UI.

**Screenshots:**
N/A

**Additional Information:**
Tested on both stable and dev.

**Comment by xusheng6** [comment]
This is actually expected behavior. It could be a little bit confusing, though (I still sometimes get confused despite I had worked on this a lot). 

In Binary Ninja, a code reference means a reference made **FROM CODE**. Its destination could be some other code, or a data variable. **But they are both called code refs since the origin is code**. For data reference, it must be coming from a data variable, and its target could be either code or data.

In your case, you are trying to get data refs from code, which is typically empty, since data refs are originated from data variable, but you are passing in the address of an instruction. There could be some exceptions that, there happen to be a data variable at the address of the instruction you passed in, and it will return an non-empty list. Nonetheless, that is NOT what you are looking for. 

To achieve your goal, you should be using `GetCodeReferencesFrom`. You will get a list of outgoing references made from the queried instruction. There will be both references to code and to data. To distinguish them, you can check whether a function or data variable exists at the returned address.

**Comment by cblichmann** [comment]
Alright, that makes sense and is actually the way I implemented this in BinExport now.
May I humbly request you add a comment in the BinaryNinja API header for this? :-)

**Comment by psifertex** [comment]
That's a great suggestion. I'll add them to both Python and C++ right now.
