### ISSUE TITLE
Show icon in Linux tray

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#361]
Binary ninja is a [?] box in my system tray. Need that icon!

**Comment by psifertex** [comment]
Note for later: http://doc.qt.io/qt-5/appicon.html

**Comment by lucasduffey** [comment]
Your Icon and Exec might have a different path

```$HOME/.local/share/applications/binary_ninja.desktop```
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Binary Ninja
Icon=/opt/binaryninja/docs/images/logo.png
Exec=/opt/binaryninja/binaryninja
StartupNotify=false
StartupWMClass=Binary Ninja
OnlyShowIn=Unity;
X-UnityGenerated=true
Comment[en_US]=Reverse Engineering
```

**Comment by psifertex** [comment]
There's a setup script in dev that creates a desktop entry to wherever you've extracted binary ninja and also adds the file association and URL handler. Look for `linux-setup.sh` inside the `binaryninja` folder after you updated to the latest dev. It's just a prototype at this point, will eventually build that functionality into the UI via a menu option or via an installer at start, but hopefully this helps until then.

**Comment by psifertex** [comment]
Moved to the public repo so it's easier for folks to submit PR if they desire:

https://github.com/Vector35/binaryninja-api/blob/1ae01b140d99f07c86c9f56374e26a062ff34c0c/scripts/linux-setup.sh

Note that there's one known bug with it now -- setting the icon for the `application/x-binaryninja` mime type doesn't appear to be working, but otherwise it should work fairly well.
