### ISSUE TITLE
Ability to register context specific sidebar widgets

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3637]
**What is the feature you'd like to have?**
There are certain scenarios where it makes the most sense for a plugin to display info in a sidebar widget. However, if that info is View Type specific and useless/unrelated in every other view, that widget now sits eating up valuable space.

This also applies to global area widgets w/ the debugger, which have to be dynamically hidden and shown.

Some way to register a sidebar widget with an `(bool(void))isValid` equivalent, or at least a way to dynamically register and deregister widgets, would be invaluable.

**Comment by fuzyll** [comment]
Assuming I understand this issue as-reported, I think my answer is that this should be "wontfix". I don't think we should get into the business of trying to re-arrange our UI based on what we think the current BinaryView should have available. We already have some small issues with UI consistency, and this feels like additional work

As an example of how other software handles this, VS Code will still show me the Docker plugin in the left-hand sidebar even if my project has no `Dockerfile`s and does nothing with Docker.

As long as we don't give the user the false idea that they are able to, for example, debug a `.jpg` that's open in a hex view, I think this is fine. The debugger UI should just have things grayed out or otherwise show that "you can't do this for the current BinaryView". If we _do_ have any issues like this, people should file them and we should definitely fix those specific cases.

Feel free to discuss this with me on Slack if you feel differently. I'm happy to consider other cases or information. But, for now, I'm going to close this.

Thanks!
