### ISSUE TITLE
Automatic Updates broken, Apparently 3.2.3829-dev is the latest build (Incorrect)

### ISSUE THREAD

**Issue by Kharos102** [Vector35/binaryninja-api#3648]
Binary Ninja Version: 3.2.3829-dev, 6eed0328
Platform: Windows 11 Version 22H2

My Binary Ninja instance seems to think 3.2.3829-dev is the latest and refuses to automatically update.

See screenshot showing newer builds available, yet 3.2.3829 is listed at the top and probably tricking binary ninja from detecting newer builds

![binja_update](https://user-images.githubusercontent.com/16039802/200909319-9e485792-d033-45eb-acdc-4b6d4a743561.png)

**Comment by negasora** [comment]
The latest version is always shown as the first item in that list - are you sure it's not just slow?

**Comment by Kharos102** [comment]
How long should I wait, its been open for 5+ minutes then I closed it an re-opened, still no change..

**Comment by Kharos102** [comment]
I forced it to update to 3.2.3030-dev, then re-enabled the "Update to latest version automatically", it still refuses to update to the latest

**Comment by negasora** [comment]
Are there any errors in the log?

**Comment by Kharos102** [comment]
Oh btw this repros, I managed to update to the latest by switching to release branch, then back to dev branch at 3830-dev then enabling latest updates.

Once on the latest, if i revert to 3.2.3829-dev and try to enable the "Update to latest version automatically", it refuses to automatically update

**Comment by ccarpenter04** [comment]
I've also been having issues with the update functionality on the dev branch since 3.2.3829. It never detected there was an update until I manually ran the check for update function, restarting it and such didn't trigger it to realize an update was available.

**Comment by Kharos102** [comment]
Ah I see the issue, that "Automatically Check Updates" setting in Network there is *not* set, even if automatic updates is set in that little channel preferences window!

**Comment by Kharos102** [comment]
In the case of enabling the setting directly in the settings menu you've shown, that way does work.

**Comment by ccarpenter04** [comment]
I've had auto-updates working historically for a while, no issues, but that checkbox was unselected for me as well when I just went to check my settings... so weird since I haven't gone into there in ages.

**Comment by psifertex** [comment]
I wonder if there's some plugin changing that setting accidentally? I'll double check our changes but I don't recall anything near there.

**Comment by ccarpenter04** [comment]
3.2.3829 was the last version that was auto-updated to, to update to 3831 and now 3834 I had to manually run the check for updates/

**Comment by negasora** [comment]
Fixed in 3.2.3840-dev

**Comment by psifertex** [comment]
Just as a small update to close the loop, thanks very much for filing this issue.  It turns out it was an unintended effect of another setting / bug that was meant to prevent our internal development builds from updating but we uncovered an issue with the buildid on windows not being set as expected which meant users on windows were unintentionally having that setting enabled. So the above fix corrects the buildid which means future builds won't have this behavior and users stuck on that version can either:

1. Use the release branch first to switch and then to latest dev as you described
2. Use the [recovery](https://binary.ninja/recover/) page to get the latest dev download links to get a version without that issue
