### ISSUE TITLE
Can't compile API on Mac mini M1

### ISSUE THREAD

**Issue by jlnsrk** [Vector35/binaryninja-api#3669]
**Version and Platform (required):**
- Binary Ninja - API
- OS: MAC OS X 
- OS Version: 13.0.1
- CPU Architecture M1

**Bug Description:**
When trying to build the api I get this linker error:
"_BNLoadSettingsFile", referenced from:
      BinaryNinja::Settings::LoadSettingsFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, BNSettingsScope, BinaryNinja::Ref<BinaryNinja::BinaryView>) in libbinaryninjaapi.a(settings.cpp.o)
ld: symbol(s) not found for architecture arm64

**Steps To Reproduce:**
I followed the example in the readme with this exception for configuration:
cmake -S . -B build -DBN_API_BUILD_EXAMPLES=ON -DHEADLESS  

**Expected Behavior:**
The compile succeeds.

**Additional Information:**
I don't think there is more relevant information.

**Comment by psifertex** [comment]
What version of Binary Ninja are you running? You need to have a version of the core that matches the version of the API.

**Comment by xusheng6** [comment]
This is likely caused by a mismatch between the API version and your core version. You can either update your binary ninja to the latest dev, or checkout your API repo to the commit that is used to build your core. To find the commit, find a `api_revision.txt` file in your binary ninja folder. And there is a commit hash in it. 

This would be solved by #3385

**Comment by jlnsrk** [comment]
This likely my issue, I appreciate the fast help!
