### ISSUE TITLE
"Import Header" should autofill or hard-code -DBN_TYPE_PARSER

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3693]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3872
- OS: macOS

**Bug Description:**
Export/Import headers currently doesn't round trip perfectly. Getting it to work required guessing -DBN_TYPE_PARSER was needed to make it work.

**Steps To Reproduce:**
1. Export Header
2. Import Header

**Comment by CouleeApps** [comment]
This is what the "Use Builtin Macros" checkbox does. Is there something else you expected to happen?

**Comment by cxnder** [comment]
That may be worth documenting somewhere / having checked by default as it doesn't even show an error on a failed import

**Comment by CouleeApps** [comment]
The checkbox has been renamed to "Define Binary Ninja Macros" and now automatically checks/unchecks depending on if the given header was exported from Binary Ninja (specifically, it looks for `BN_TYPE_PARSER` in the first 2kb of the file). Additionally, both checkboxes were given tooltips explaining their functionality. Hopefully this should make your workflow less confusing.

Fixed in dev 3.2.3931
