### ISSUE TITLE
Exports list is triage view isn't updated after PDB is applied

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3709]
**Version and Platform (required):**
- Binary Ninja Version: 3.2 dev

**Bug Description:**
Exports list is triage view isn't updated after PDB is applied

![image](https://user-images.githubusercontent.com/10556585/205116676-40dd96f6-640b-4250-88c2-d4c9753fc7dc.png)

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the included file
2. Go to Triage view
3. Check the exports list for symbols marked "ordinal_XXX"
4. Navigate to the export and see that it has a symbol

[mfc42u.dll.zip](https://github.com/Vector35/binaryninja-api/files/10134559/mfc42u.dll.zip)

**Expected Behavior:**
The exports list should show the updated name of the symbol

**Comment by CouleeApps** [comment]
Looking further into this dll, it seems like things get a little spicy:

- The PDB loader does not remove the extra ordinal symbols when it loads, so you get 2 symbols at those addresses (one with the name, one named ordinal_1234)
- Even if you remove the duplicates, some addresses (namely 0x1002e0a0) have two ordinals specified (266 and 6464)

The first issue is already dealt with on a branch to be merged soon, but the second is a bit more of a problem, since symbols don't have the concept of "Many Ordinals."

**Comment by CouleeApps** [comment]
Fixed via https://github.com/Vector35/binaryninja-api/commit/5680b8c36285a9a6011412bba0363e156cf4d7f6
