### ISSUE TITLE
Binja misses function call in HLIL output

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3718]
* Binary Ninja Version: 3.2.3895
* OS: Windows 11, x64

**Steps To Reproduce:**
1. Open attached binary
2. See _start in HLIL and disassembly
3. See that there is a call to `sub_140001000` in disassembly but it missed in HLIL

**Expected Behavior:**
I expect it to show me function call to `sub_140001000` in HLIL output.

**Additional Information:**
Binary: [ConsoleApplication1.zip](https://github.com/Vector35/binaryninja-api/files/10175388/ConsoleApplication1.zip)

**Comment by plafosse** [comment]
The reason this is done is because the function in question has zero side effects. HLIL is functioning much like how a compiler would throw that same function away. If you'd rather this not occur you can use this option:
![image](https://user-images.githubusercontent.com/10556585/211568178-4b3f840d-b495-4626-948f-d83069ff66e9.png)
