### ISSUE TITLE
Token for array does not reference element at index, but instead the start of the array

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3746]
**Version and Platform (required):**

- Binary Ninja Version: 3.2.3923-dev Personal (Build ID 9dd91d0a)
- OS: Windows 11
- OS Version: 10.0.25267.1000
- CPU Architecture: x64

**Bug Description:**

It seems that arrays under some circumstances don't get xrefs for non-zero indexing assignments.

**Steps To Reproduce:**

1. Open this BNDB: https://drive.google.com/file/d/1klCDVsnbDyUWCv1rGRm9mZ8Hjj4Luofu/view?usp=sharing
2. Navigate to `S1CommandQueue::handlers`.
3. Note that it has a reference from `sub_7ff7d5dae620` (assignment to index 0).
4. Note that the various functions below that one don't result in xrefs despite assigning to various non-0 indexes).

**Expected Behavior:**

Every indexing assignment into `S1CommandQueue::handlers` should ideally result in an xref.

**Comment by CouleeApps** [comment]
From the given BNDB, it seems like xrefs are actually being created to the referenced offsets, but the xrefs view is only showing them for the first index in the array because the token in HLIL is referencing the start of array. If you click the line (not the token of the variable) of one of the other functions referencing offsets, you can see outgoing references to the later entries in the array, and if you click those entries in the array, you can see the incoming references from the function.

Given that, I'm not sure which of the following following needs to be fixed:
- The xrefs window showing the base address of the array even when you click a reference to a later element
- The base of the array not getting an xref when a later element is referenced

**Comment by CouleeApps** [comment]
It seems to me like the underlying issue here is the first point mentioned above, or more specifically:

The token for `S1CommandQueue::handlers` in `S1CommandQueue::handlers[0x9e4c]` is referencing `S1CommandQueue::handlers[0]` because it is a reference to the array itself and not the element in the array. We should look into either making the `S1CommandQueue::handlers` reference the element in the array or making the xrefs for that token include the xrefs in the line (that reference the element).

**Comment by plafosse** [comment]
Could you take that file out of your trash 🙃 
<img width="381" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/cc2cc3ef-2c40-4e18-968c-5e3620d92283">

**Comment by alexrp** [comment]
Oops, didn't realize that file was still linked to this issue. It should be back.

**Comment by psifertex** [comment]
No need to keep it around, we've archived it internally: `despise contemporary essay ambiguous`

**Comment by cxnder** [comment]
Resolve in **builds >= dev 3.5.4375**

Selecting the array token itself in HLIL or directly on the datavariable will show xrefs for the entire array:
![image](https://github.com/Vector35/binaryninja-api/assets/55725881/2758a438-9031-40c5-a1bb-681f99eea1a4)

Selecting _specifically_ the index in HLIL or on the DataVariable will show xrefs to just that index
![image](https://github.com/Vector35/binaryninja-api/assets/55725881/4b9e6231-416f-4927-95d3-bf2303f294b1)
