### ISSUE TITLE
support rebasing binaries

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#38]
Because ASLR is a thing

Also, should support basemodule+offset

**Comment by artemdinaburg** [comment]
Just wanted to +1 this since I was about to post the same request :)

**Comment by psifertex** [comment]
Yeah, this is also important for people loading raw ROMS that are dumped from something at an offset. There have been a few requests for this, definitely a bit higher priority.

**Comment by mitjakolsek** [comment]
I'd also like to see an option to automatically rebase to address 0 - when analyzing an app that you relaunch many times with ASLR, this makes it easy to copy-paste the offset from image base from/to WinDbg, which can show addresses as ImageName+offset.

**Comment by anon8675309** [comment]
Was about to ask this question too.  It'd also be nice to actually see what Binja is currently using as the base address.  Use case: I just hit a breakpoint at EXE_BASE+0x1334.  Take Binja's base address, add 0x1334, press "g", enter address, actually be able to use Binja to look at the code.  Currently Binja is unusable because of this (I have no useful symbols in this EXE).

**Comment by psifertex** [comment]
Sorry anon8675309, missed your comment until now. The easiest way to see the current base address is to switch to linear view view and scroll to the top (though that feature has only been in the dev branch until recently). You can see the mappings from file sections to memory addresses there.

**Comment by bpotchik** [comment]
Initial support for rebasing is complete. Support exists for relocatable ELF, Mach-O, PE, and raw files. The feature is available in headless and the UI via 'Open with Options'. The UI portion is functional, but not complete.
