### ISSUE TITLE
can't "lock to launcher" in ubuntu

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#384]
If binja has beed locked to launcher in ubuntu, but isn't currently running - clicking binja on the launcher to open the application will not work.

This might be tied https://github.com/Vector35/binaryninja-api/issues/361

**Comment by psifertex** [comment]
As a temporary work-around, have you tried creating a launcher instead of pining the app?

We've tried to avoid having an installer on Linux but it looks like that will be unavoidable for some of these issues. It's a lot of work for little gain though that can be mostly worked around so I suspect it'll be lower priority behind other items for a while.

**Comment by lucasduffey** [comment]
yeah that works. For ubuntu 16 LTS:

sudo apt install gnome-panel

gnome-desktop-item-edit --create-new ~/.local/share/applications/binaryninja.desktop # and then open the "binary ninja" launcher in that same directory that you just created and pin it

**Comment by psifertex** [comment]
This is resolved since the integration and updates of the linux-setup script that creates a desktop file that can be added to the favorites.
