### ISSUE TITLE
Implement MIPS floating point branch instructions

### ISSUE THREAD

**Issue by abitalive** [Vector35/binaryninja-api#400]
Please implement support for the following MIPS floating point branch instructions.

bc1t
bc1tl
bc1f
bc1fl

**Comment by plafosse** [comment]
Any chance you can provide a binary with these instructions?

**Comment by pjgat09** [comment]
[MIPS_FP_branches.zip](https://github.com/Vector35/binaryninja-api/files/1254157/MIPS_FP_branches.zip)

Go to 0x9b60 and decode there. 0x9C98, 0x9CC0, and 0x9Ce8 are a bc1f. 0x9D10 is bc1fl.

Even if the IL isn't fully supported is it possible to get BN to show the branching correctly instead of it not decoding the instruction at all?

**Comment by plafosse** [comment]
This was fixed sometime in early 2018.
