### ISSUE TITLE
BN does not render `int128_t` data in linear view

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4059]
Binary Ninja Version: 3.4.4090-dev
Platform: Windows 11 Version 22H2

It can be reproduced by defining a `int128_t` variable in anywhere in data section.

![128t](https://user-images.githubusercontent.com/109607896/222434034-972eeb68-f058-4640-8c59-f741c3257025.png)

**Comment by fuzyll** [comment]
As far as I'm aware, it *should* just be rendering.

Also, the reason this hasn't been fixed yet is because the code uses `int64_t`s to pass the data around internally and...as you might imagine, 128 bits don't fit inside of that, so this is not, in fact, the 5-minute change I expected it to be when I looked at it last week. 🙃

**Comment by D0ntPanic** [comment]
This was true for any data type that doesn't have a valid data renderer (including any integer type greater than 8 bytes or not a power of 2 in size). Fixed in 3.6.4749.
