### ISSUE TITLE
Duplicate Symbols

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#4109]
I'm seeing this mostly on `ExternalSymbols`. Screenshot below is demonstrating that `BNGetSymbolsByRawName` seems to be fine, so I believe it's a core symbol table issue (the internal mapping by address).

![image](https://user-images.githubusercontent.com/7171118/225095855-b9d22614-5ac6-4ad7-9d69-ddcbf734ba82.png)

**Comment by KyleMiles** [comment]
Example binary:
[babys_first.elf.zip](https://github.com/Vector35/binaryninja-api/files/10973130/babys_first.elf.zip)

**Comment by xusheng6** [comment]
Related to https://github.com/mandiant/capa/issues/1504

The underlying reason for the current behavior is actually #4417. For some reason, we defined two ExternalSymbols at 0x4048. So we are seeing two after we build the cache. For the first line, we are only getting one result because trying to retrieve a symbol by name without the symbol cache only returns the first match.

**Comment by xusheng6** [comment]
The reason that we are defining the same symbols twice is that the symbol is define in two symbol tables. We just fail to properly detect that the symbol exists and reject the addition of the second one

**Comment by xusheng6** [comment]
Fixed in dev 3.5.4418
