### ISSUE TITLE
Problem with `__builtin_*` when address space is completely allocated

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4241]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4242-dev, 2e3a4286
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

**Bug Description:**

What does it mean that I have a non-code call target? It's not in the code of this function. Where is it?

My ROM goes up to `0x13f46d`. My RAM starts at `0x13f46e` and goes up to `0xffffffff`. This address is indeed non-code but where does it come from?

**Additional Information:**

![Screenshot 2023-04-19 at 13 48 34](https://user-images.githubusercontent.com/18791/233054815-aeb0f164-5790-46da-add4-24c41aaa45f2.png)
![Screenshot 2023-04-19 at 13 48 16](https://user-images.githubusercontent.com/18791/233054818-9f9a5b5a-5641-4edf-90de-fd6dbb3c3d21.png)
![Screenshot 2023-04-19 at 13 47 59](https://user-images.githubusercontent.com/18791/233054821-84b6414b-164b-4509-8b6c-a248f0f78f00.png)

**Comment by psifertex** [comment]
This is unfortunately a known limitation of the current implementation for our "builtin_" outlining functionality.  

The idea is that some address space is carved out from unused addresses, however in your case since you've fulled mapped the address space there's simply no where for it to go. We create a fake region of memory and put these function pointers there so that we can re-write the IL to convert inlined memcpy/strcpy style operations into an external call which vastly improves readability. However, in this case, there's simply no room to allocate them and the analysis produces that error as a result. 

Leaving this open to track the issue but long story short, there's no easy way to fix it other than for you to leave some empty space when you're defining the address space -- the advantage is that you can then get cross-references to those functions and more easily identify all of the times they're used.

**Comment by joelreymont** [comment]
V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by bpotchik** [comment]
I've updated the outlining feature to more gracefully handle existing segments that consume the entire address space. Now on build `3.5.4507`, if the entire address space is consumed, the feature will log a message and disable itself such that it does not interfere.

If you want the feature enabled again, you can always shorten the ram segment.
