### ISSUE TITLE
Synthetic intrinsic pointers not updated

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4324]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

I created a segment following my code and covering all memory space. BN created the synthetic intrinsics thusly

```
00013f470  void* __builtin_memcpy(void* dest, void* src, uint32_t n) = 
00013f470                                                  00 00 00 00                                                      ....
00013f474  void* __builtin_memset(void* s, int32_t c, uint32_t n) = 
00013f474                                                              00 00 00 00                                              ....
00013f478  char* __builtin_strcpy(char* dest, char const* src) = 
00013f478                                                                          00 00 00 00                                      ....
00013f47c  char* __builtin_strncpy(char* dest, char const* src, uint32_t n) = 
```

I deleted the segment at the end and BN created the synthetic intrinsics section. Unfortunately, the references in the database weren't updated.

For example, the synthetics are at `0xf0...` but the error still refers to addresses without the prefix.

Re-analyzing doesn't help.

```
f013f470  extern void* __builtin_memcpy(void* dest, void* src, uint32_t n)
f013f474  extern void* __builtin_memset(void* s, int32_t c, uint32_t n)
f013f478  extern char* __builtin_strcpy(char* dest, char const* src)
f013f47c  extern char* __builtin_strncpy(char* dest, char const* src, uint32_t n)
f013f480  extern wchar32* __builtin_wcscpy(wchar32* dest, wchar32 const* src)
```

![Screenshot 2023-05-19 at 4 12 17 PM](https://github.com/Vector35/binaryninja-api/assets/18791/a82c776f-08c5-48dc-98c9-7e81838cbcaa)

**Comment by bpotchik** [comment]
This is fixed in `3.5.4507`. However if you want to clean up your existing BNDB there are some steps you will need to follow.

1) When working with a mapped view, you should try make auto segments. Open your database and remove the existing user segment you made for RAM. Save the database and close it.
2) Using open with options, add a new auto segment (not a user segment) An example JSON is:
   {"start": 1373294, "length": 15338385, "data_offset": 0, "data_length": 0, "flags": 5, "auto_defined": true}
3) Delete the old symbols. You can find the old symbols with:
 `bv.get_symbols_by_name("__builtin_memcpy")` then use `bv.undefine_auto_symbol(...)`
4) Once removing the old symbols, all impacted functions should be reanalyzed and everything will be fixed up, pointing to the new builtins section.
