### ISSUE TITLE
Inconsistent Function Labels

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#434]
In Disassembly View, the function label is `main` but in IL view, the name changes to `data_0`. All of the functions in the file are exhibiting this behavior, though no function actually starts at Address 0.

If I had to guess, it's because the BinaryView is raw.

![wrong_name_binja](https://cloud.githubusercontent.com/assets/5834130/18036270/0625e8d0-6d34-11e6-992c-ed43839aaa6a.gif)

**Comment by psifertex** [comment]
So that's not actually a function label. We don't actually show function labels at all right now in IL view.

(Side note, you can tell because the colors are slightly off between the two)

Now, as to why the data label is showing up instead, presumably something else references that address and the label gets made? 

I can't reproduce that on any other local binaries, is that one you can share?

**Comment by joshwatson** [comment]
Yeah, sent via slack DM

**Comment by joshwatson** [comment]
Looks like this is fixed in dev, thanks to d6c63268eb98fb0801d1c825e1aa4f72c1e1d99c!

**Comment by psifertex** [comment]
It's one thing when you're better at customer service, but another thing when you're better at regression testing too! :-P

Thanks. ❤️
