### ISSUE TITLE
Strings search is super slow with lots of strings (~3 million)

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4340]
Version 3.4.4271 (b7fd028d)

If I had to guess, the strings list is probably being filtered whenever `QLineEdit::textChanged` is fired.

It might be worth adding a slight delay to see if the user is done typing before attempting to filter the list, perhaps only if the binary has lots of strings. Currently, if you type a word into the strings list you'll get to watch it appear one character at a time whilst the UI struggles to keep up.

I understand this is inherently a slow task, but there is a UX win to be had to make the experience less laggy.

**Comment by psifertex** [comment]
I've added a 500ms delay for builds >= 3.5.4295. Let me know if that doesn't help. 

Note that I applied it universally since it seems small enough to be reasonable in other views and will also help in situations with, for example, large numbers of types. If it is too obvious though, I might try to make it a bit more selective and react quicker for smaller sets of filtered items.
