### ISSUE TITLE
Type rename fails on certain programmatically created types

### ISSUE THREAD

**Issue by emesare** [Vector35/binaryninja-api#4345]
**Version and Platform**
- Binary Ninja Version: 3.5.4299-dev
- OS: Windows 11
- OS Version: 22H2
- CPU Architecture: x64

**Bug Description:**
After running my [C++ plugin](https://github.com/emesare/binja-msvc) that defines **user types**, any renaming of said type's results in only their definition being renamed, any reference to said type fails to be renamed.

**Steps To Reproduce:**
1. Download attached [executable](https://binaryninja.slack.com/files/U026W5LGT51/F0588GEC18F/overrides.exe) and [BNDB](https://binaryninja.slack.com/files/U026W5LGT51/F058GEG6SR4/overrides.bndb)
2. Rename type "__offset(0x10) Bird_vfTable" to "Bird::Flying_vfTable"
3. Observe that the type has not been updated within type "Bird" (field "vft_offset(0x10) Bird") or the data variable located at _0x140011380_

**Expected Behavior:**
I expect for every reference to the renamed type to be renamed.

**Screenshots:**
Type name "__offset(0x10) Bird_vfTable" not updated to "Bird::Flying_vfTable" within the type "Bird".
![image](https://github.com/Vector35/binaryninja-api/assets/35282038/e80efa21-bedd-46a4-a86b-0fd0485eb2be)
Type name "__offset(0x10) Bird_vfTable" not updated to "Bird::Flying_vfTable" for the data variable at _0x140011380_.
![image](https://github.com/Vector35/binaryninja-api/assets/35282038/5b9f1105-8ebc-4369-a5b8-5a95fb904637)

**Additional Information:**
Additional slack messages ([1](https://binaryninja.slack.com/archives/C1E616ZSQ/p1684383789450919), [2](https://binaryninja.slack.com/archives/C1E616ZSQ/p1684436169440819))

**Comment by plafosse** [comment]
I believe the problem here is that you're creating your types incorrectly. This is a really tricky part of the API which we have messed up internally frequently. I haven't verified with your scripts but I've seen this enough times to have a strong suspicion. 

Your structure member is being created as a struct rather than a NTR to a struct. 
```
>>> bv.types['Bird'].members[1].type.target
<type: immutable:StructureTypeClass 'struct __offset(0x10) Bird_vfTable'>
```

instead it should be a `NamedTypeReference` to the `Brid_vfTable`

Observe:
```
struct Foo
{
    class Animal* myanimal;
};
```

Create the above type then look at the member type:

```
>>> bv.types['Foo'].members[0].type.target
<type: immutable:NamedTypeReferenceClass 'class Animal'>
```
Hopefully this helps. There is some additional information int the docs here: https://docs.binary.ninja/dev/annotation.html#named-types
