### ISSUE TITLE
armv7 lifting of multiply instructions is incorrect

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#4364]
The armv7 lifter produces IL expressions where the size of a multiply operation does not match either of
the input operands. This causes the analysis of optimized division to always fail to simplify into a
division expression in armv7 binaries.

Several mulitply instructions are lifted in this way. All of the multiplication operations need to
verified and fixed so that the operand sizes match the operation size.

<img width="1330" alt="armv7" src="https://github.com/Vector35/binaryninja-api/assets/7007406/476ff27b-7ca8-44f7-801d-24ed843e4c06">

Example binary:

[armv7.zip](https://github.com/Vector35/binaryninja-api/files/11607133/armv7.zip)

**Comment by lwerdna** [comment]
Actual fix is at https://github.com/Vector35/arch-armv7/commit/8fb4292d846bdfc6818169f5abf9f7ca0a64f1ea.

![image](https://github.com/Vector35/binaryninja-api/assets/474191/1188614b-a760-478d-9e18-c5172a669d5f)

We agreed in meeting:
* `LLIL_MUL` is truncating multiply, operand signs unimportant
* `LLIL_MULS_DP` signed, output is double width of input
* `LLIL_MULU_DP` unsigned, output is double width of input
* size is byte width of **input** (which happens to be same as size of input for `LLIL_MUL`)

Which was clarified in our documentation at https://github.com/Vector35/binaryninja-api/commit/2f415e3da3a417160c07928cc8b91f42eddbac3f

A few additional multiply instructions were fixed in https://github.com/Vector35/arch-armv7/commit/8fb4292d846bdfc6818169f5abf9f7ca0a64f1ea and https://github.com/Vector35/arch-armv7/commit/59f92c3c551f65f04d5c10920e2625930a5b3faf but they don't seem to be critical for these magic constant division situations.
