### ISSUE TITLE
document native plugin building

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4396]
Building native plugins without the actual binary should be possible for various github CI workflows and we should demonstrate that with examples or documentation.

Related: we also need to clarify the license that the .lib included with the native windows install is released under the same [license](https://github.com/Vector35/binaryninja-api/blob/dev/LICENSE.txt) as the API repo.

**Comment by alexrp** [comment]
> Related: we also need to clarify the license that the .lib included with the native windows install is released under the same [license](https://github.com/Vector35/binaryninja-api/blob/dev/LICENSE.txt) as the API repo.

Speaking of which, it would be nice if that file was distributed somewhere in some official capacity so my build system could just grab it. It seems that the only option I have right now (if I want to be able to build native plugins in CI) is to commit the `.lib` to Git. That's not super good since it's a binary file and it's expected to change regularly.

One way I could see this working would be if you guys published "releases" on this repository containing everything needed to build a native plugin. So `binaryninjacore.h`, `binaryninjacore.lib`, and whatever else you deem to fit into that category. Then all anyone has to do is grab that release as part of their build system and use the artifacts in it.

**Comment by alexrp** [comment]
It seems like the approach I mentioned would also accommodate use cases such as the one mentioned here: https://github.com/Vector35/binaryninja-api/issues/3399#issuecomment-1421182648

**Comment by psifertex** [comment]
Lib license documentation complete in builds > 4500. Remainder of the documentation coming in the next release.

**Comment by psifertex** [comment]
Resolved some time ago but was accidentally missing from the outline until: https://github.com/Vector35/binaryninja-api/commit/ac3490ad00ba9d7d4298565168163b9becc66deb

Note in particular the new [example repo](https://github.com/CouleeApps/binja-ci-tests) though we still need to do some work to cleanup that workflow. In particular, building on windows is currently broken and tracked as issue 1 on that repo.
