### ISSUE TITLE
OOM on an obfuscated binary

### ISSUE THREAD

**Issue by ancorehraq** [Vector35/binaryninja-api#4425]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4342-dev
- OS: Ubuntu Linux
- OS Version: 22.04.2
- CPU Architecture: x64

**Bug Description:**
I'm seeing infinite memory usage on a 44MB obfuscated binary I grabbed from a running process. I'm emailing the binary to binaryninja@vector35.com.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open binary
2. Wait for Disassembling 7000ish
3. Memory use keeps increasing beyond 100GB with little progress being made

**Expected Behavior:**
Analysis completes with reasonable memory usage.

**Additional Information:**
I also tried:
- 3.4.4271
- Setting triage options to most basic
- Zeroing out first 4096 bytes containing the deliberately corrupted PE header

**Comment by fuzyll** [comment]
Binary is available to Vector 35 employees if they search for "Soften Tax Salesman Army".

**Comment by bpotchik** [comment]
I've verified a fix for this issue, and run-away basic block analysis in general.

In order to repro the analysis hang for this file perform the following steps:

- Open the sample with options and enable the 'Initial Analysis Hold' option
- Open the file
- Navigate to the address 0x1413736bf, and choose 'p' to create a function. A function creation action is prioritized.
- Release the analysis hold and observe the status with no analysis results provided.
- Eventually, binary will OOM.

![Screenshot 2024-08-06 at 12 01 43 PM](https://github.com/user-attachments/assets/b31a13b1-3abe-417f-a2c8-36cce1b52231)
