### ISSUE TITLE
Cannot run scripts when it have non-ascii characters

### ISSUE THREAD

**Issue by ltlly** [Vector35/binaryninja-api#4460]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4369-dev Personal, 256481c9
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
Cannot run scripts when it have non-ascii characters

**Steps To Reproduce:**
Write a py script with non-ascii characters,
```
#逆
print(1)
```
Run it in bn
![image](https://github.com/Vector35/binaryninja-api/assets/86669384/c0e0da90-1720-402e-9fcf-257a7bccf5e2)

**Expected Behavior:**
Proper running

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/86669384/c0e0da90-1720-402e-9fcf-257a7bccf5e2)

**Comment by xusheng6** [comment]
There are multiple places across the product that we assumed ASCII chars. We should definitely make them compatible with non-ASCII chars

**Comment by xusheng6** [comment]
@ltlly I fixed the issue for non-ASCII characters in the file. However, in your case, you will still get an error because your file path also contains non-ASCII characters. That issue is tracked by https://github.com/Vector35/binaryninja-api/issues/4510. You may be able to workaround the path issue by renaming the file and make it all ASCII chars
