### ISSUE TITLE
ITE instruction in Thumb2 may not be lifted correctly

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4498]
In the discussion below, at a quick glance, it looks like `ite cc` may not be applied correctly? This could be another case like #4430, although it seems like it's manifesting differently.

### Discussed in https://github.com/Vector35/binaryninja-api/discussions/4427

<div type='discussions-op-text'>

<sup>Originally posted by **imethod** June 20, 2023</sup>
Excuse me I used a translation tool

![image](https://github.com/Vector35/binaryninja-api/assets/109936536/e0a53137-5fc8-4ced-b531-46d6af596f82)

mil 
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/fa77072f-39a6-47fd-b270-18517993f6cc)

The three lines of thumb instruction should be an if else structure but mil complicates it 

I tried merging variables , But the branches weren't removed

![image](https://github.com/Vector35/binaryninja-api/assets/109936536/8d0ca601-d5c5-44b8-84f8-67df155a4b6c)

ida f5  effect
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/29beb0a4-dd00-4d3e-b71e-21df8dd52e0b)

ninja c
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/fdb6a1b0-ba41-4d76-850d-3a6ad78f46d2)

The most important thing is that when I set the value of the variable, the second if is not recognized
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/cff638b5-fa5b-4223-834e-3ffe97a376dd)

Maybe there is a function that can be optimized manually but I don't understand how 
thankes 0.0</div>

**Comment by lwerdna** [comment]
This issue is not the same as when we prematurely leave an IT block due to an exiting instruction (#4430).

I cannot reproduce this issue. Without an example binary, the best I can do is construct a similar case:

![image](https://github.com/Vector35/binaryninja-api/assets/474191/2a0b7d7c-3419-4f74-b855-0a90c98b8230)

which lifts and creates the expected if/then logic:

![image](https://github.com/Vector35/binaryninja-api/assets/474191/6d9c6820-4914-48ea-8a5f-5679025c5fcc)

If we can get an example binary and reproduce the problem, please reopen the issue.
