### ISSUE TITLE
DWARF import crashes on large binary (sqlite3)

### ISSUE THREAD

**Issue by sherman5-str** [Vector35/binaryninja-api#4514]
**Version and Platform (required):**
- Binary Ninja Version 3.5.4402-dev, Build ID c2f291a7
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
Binary Ninja crashes when analyzing the attached sqlite3 binary. This happens during the DWARF import stage (I have `DWARF Import Plugin` enabled in my settings). I've tested this twice (1) first on an existing .bndb where `Analysis > Import Debug Info` crashed and (2) on a fresh analysis of this binary where Binja crashed in the first stage of analysis (i.e. DWARF import).
[sqlite3.zip](https://github.com/Vector35/binaryninja-api/files/12141147/sqlite3.zip)

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Analyze this binary in Binja with `DWARF Import Plugin` enabled

**Expected Behavior:**
Analysis successfully imports DWARF info

**Comment by xusheng6** [comment]
The crash happens here: https://github.com/Vector35/pdb-rs/blob/b51abd394fdac8447274e5f79ac6d1c7b4c43b15/src/symbol/mod.rs#L347

**Comment by KyleMiles** [comment]
The root cause of this is because of completely duplicate type definitions in the DWARF info. This'll be fixed in 3.5.4403-dev. 

I also went ahead and added a progress indicator.

I'll also note here that it spends more time correctly parsing namespace information than it spends parsing the entire rest of the DWARF info, so that bit of code probably needs revisited.
