### ISSUE TITLE
HLIL removing firmware busy loops

### ISSUE THREAD

**Issue by lockbox** [Vector35/binaryninja-api#4527]
**Version and Platform (required):**
- Binary Ninja Version: latest dev (3.5.4409) + stable
- OS: ubuntu
- OS Version: 18.04
- CPU Architecture: x86_64

**Bug Description:**
HLIL + Pseudo C removing busy loops

**Steps To Reproduce:**
- Open a file like this: in binary ninja [bin.zip](https://github.com/Vector35/binaryninja-api/files/12195075/bin.zip), (built binary of [this github example](https://github.com/beckus/stm32_p103_demos/tree/master/demos/blink_flash)).
- go to `main` in `Dissasembly`, `LLIL` or `MLIL` view, note the presence of `busyLoop`
- change to `HLIL` or `Pseudo-C`, `busyLoop` is gone

**Expected Behavior:**
- unconditional function call to `busyLoop` should still be there

**Additional Information:**
im assuming this is doing some elimination of functions that "don't have side effects", when in this case `main` makes a whole heck of a lot more sense with the call to `busyLoop` than without, it's little things like this that make using binary ninja a little more painful to use for firmware re.

I'm also assuming that this has been mentioned before and might be tracked somewhere, so apologies for duplication if so

**Comment by xusheng6** [comment]
This can be fixed by setting `busyLoop` to non-pure. Go to function `busyLoop`, right click, `Edit function Properties...`. In the dialog that shows up, uncheck the `pure` option. Then the HLIL of main should not included calls to it. 

![image](https://github.com/Vector35/binaryninja-api/assets/94503187/2bfde58b-fbe8-497c-b76a-b26dda7a9ba8)
