### ISSUE TITLE
Allow selecting/copying Pseudo C code without selecting the hex addresses.

### ISSUE THREAD

**Issue by tur11ng** [Vector35/binaryninja-api#4534]

**Comment by psifertex** [comment]
You can use the "show address" menu item or command-palette item (even binding a hotkey if you want) to either include or exclude addresses in what's copied. I don't think we'll remove it from copy/paste by default since there are sometimes reasons to want it on and if we never selected it, it would be hard for people to figure out how to copy it with the addresses then. Given that I'm going to close this as wont-fix for now, but if you think there's a compelling argument for why the behavior should be changed and the work-around isn't sufficient, let me know!
