### ISSUE TITLE
DWARF Parsing Fails on `vgpreload_core`

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#4547]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4425-dev

**Bug Description:**
Crash when importing debug info

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open [vgpreload_core-x86-linux.so.txt](https://github.com/Vector35/binaryninja-api/files/12263757/vgpreload_core-x86-linux.so.txt)
2. Import debug info from [vgpreload_core-x86-linux.so.debug.txt](https://github.com/Vector35/binaryninja-api/files/12263759/vgpreload_core-x86-linux.so.debug.txt)

**Expected Behavior:**
It imports debug info without crashing

**Comment by KyleMiles** [comment]
This is a very odd crash. Gimli is reporting an unexpected EOF in the file, but dwarfdump shows it fine. Might be related to https://github.com/gimli-rs/gimli/issues/405, which seems fixable, so I'll look in to it. In the meantime I'll push a test branch that fixes that crash. Assuming the build servers like that I'll merge that and leave this ticket open until we fix the root cause...we won't be parsing the debug info out of this file in the meantime though.

**Comment by negasora** [comment]
This is fixed as of (and probably way before) `4.1.5626-dev`
