### ISSUE TITLE
Can't Detect MIPS64 ELFs By Default

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4555]
**Bug Description:**
We appear to be unable to accurately detect that an ELF is `mips64` instead of `mips32` by default. I suspect this is because the `e_machine` does not make a distinction between the two, and we rely on that to determine the default architecture.

You can work around this by using Open with Options and changing architecture and platform to `mips64`. But, it's easy to miss, and even easier if you don't have apriori knowledge of which architecture is correct.

**Steps To Reproduce:**
1. Open any MIPS64 binary.
2. Observe that it defaults to `mips32`.

**Expected Behavior:**
We open things as `mips64` when they are.

**Comment by lwerdna** [comment]
repro:

[busybox-mips64.zip](https://github.com/Vector35/binaryninja-api/files/12295777/busybox-mips64.zip)

then in the python window:

```
>>> bv.arch
<arch: mips32>
```

(should be mips64)

The Elf64_hdr `.e_machine` field is just `EM_MIPS` (so nothing to distinguish the 32/64 on), but we should look also to the `.e_ident[EI_CLASS]` field which has value 0x2 (marking 64-bit).

**Comment by lwerdna** [comment]
I was expecting to add some code that would look to `.e_ident[EI_CLASS]`. Instead, we're going to mix that field into the identifier when we register the architecture.

Currently, we use `.e_machine` as an architecture ID when we call `RegisterArchitecture()`. Now for those architectures whose ID here is not selective enough (like for MIPS, 8 is used by both 32-bit and 64-bit elfs), their ID will be augmented with `.e_ident[EI_CLASS]` shifted to bit position 16.

So instead of calling `RegisterArchitecture()` with EM_MIPS (8) all alone, we call it with 0x10008 for 32-bit and 0x20008 for 64-bit.

Commit in arch-mips: https://github.com/Vector35/arch-mips/commit/c8e2d4a813c604d04310f2d5a5e60a687b713c50
Commit in view-elf: https://github.com/Vector35/view-elf/commit/b651c02c55fe875a01997a7ebee14c06f11ab7c8
Commit in binja: https://github.com/Vector35/binaryninja/commit/138c8688527f71fe0120a0751cb9c08053a00a35
