### ISSUE TITLE
Import from remote BNDB

### ISSUE THREAD

**Issue by XploitBengineer** [Vector35/binaryninja-api#4562]
**What is the feature you'd like to have?**

Currently, to import types etc from one BNDB into another, you can select `Import from BNDB`, which lets users enter a file path or browse in a file explorer. For BNDBs hosted on an enterprise server, this currently involves navigating to `~/.binaryninja/remote` and then figuring out which directory and file hash represents BNDB you want.

On the enterprise edition, it would be cool to have a `Select from remote`, or similar, button which allows the us to select a BNDB in a more user friendly way.

**Is your feature request related to a problem?**

No problem, but a nice to have.

**Are any alternative solutions acceptable?**

Currently, we can identify the file hash of the bndb we want to import, and then import it as you would with a local file. e.g `~/.binaryninja/remote/0f348fc7c1bab7310d0b6b5445fc67336e0d13342eccc6f3e0464a54e6fb88ff/aeb1e666-e590-4745-8f55-ab646223bc8d/4d79934a-39b3-4823-be0c-799dbaee209e.bndb`

**Comment by fuzyll** [comment]
I *believe* this will be addressed by the upcoming Project support (#226), which was originally slated for the upcoming September stable release, but needed to be pushed back because it was wider in scope than we'd originally realized.

Keeping the issue open, linking it to Projects, and including it with our Enterprise issue tracking to make sure we don't miss it. Thanks for the report!

**Comment by negasora** [comment]
Added in `3.6.4784-dev`
