### ISSUE TITLE
vtables are sometimes rendered incorrectly

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4604]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4508-dev Personal (348d7548)
- OS: Windows
- OS Version: 10.0.23531.1001
- CPU Architecture: x64

**Bug Description:**
vtables are sometimes rendered incorrectly.

**Steps To Reproduce:**
1. https://drive.google.com/file/d/108NgAiRrCBPX1tf3X15NR2K7TCW3XmSp/view?usp=sharing
2. Go to `0x7ff69cb9dc08`
3. Type that vtable as `S1PetVolume::__vftable`

**Expected Behavior:**
The vtable should render normally.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/44076/be8008c5-4afc-4549-a8bb-15dfc56effe8)

**Comment by alexrp** [comment]
This doesn't seem to be a rendering issue after all. 🤔

What seems to have happened is that `S1PetVolume::__vftable` somehow ended up with the wrong size:

![image](https://github.com/Vector35/binaryninja-api/assets/44076/55124190-b7a5-4fca-bb3d-7476a1a2cd61)

I actually have no clue how that happened. I know that, in some cases, when you modify a type in a way that changes its size, other types that contain that type may not be updated accordingly. But that isn't what happened here since I created `S1ActionVolume::__vftable` before `S1PetVolune::__vftable`, and I didn't modify it after. 🤔

Should this be kept open to track that type size issue?

**Comment by emesare** [comment]
Simply updating the type in the `Change Type` interface seems to fix the size being calculated incorrectly. It seems that the issue lies in the width of the type not updating after changes are made to base structures, the fact that it shows up in the type view and with `bv.types["S1PetVolume::__vftable"].width` would also suggest this to be a type issue rather than a data renderer issue.

I have gone ahead and attached a video in which I (poorly) attempt to illustrate that the inherited members appear to update for the structure but not the structure size. 

https://github.com/Vector35/binaryninja-api/assets/35282038/b71e9c05-eae0-4c24-aefe-99373332a57a

**Comment by emesare** [comment]
Here is an easy way to reproduce:

- Create empty view
- Fill in three bytes
- Add the following types:
```c
struct baseStruct __packed {};

struct __base(baseStruct, 2) test __packed
{
    uint8_t first;
    uint8_t second;
};
```
- Apply the type to the view
- Add `uint8_t` field to `baseStruct`
- `bv.types["test"].width` incorrectly reports 2 instead of 3

**Comment by xusheng6** [comment]
There is no rendering issue involved. The type's size it not properly updated. 

I am closing this issue and creating a new one track the actual issue
