### ISSUE TITLE
online docs contain outdated files that need to be removed

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4653]
The `caller_sites` is present here: https://dev-api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.caller_sites. Though it is missing from this page: https://api.binary.ninja/binaryninja.function.Function.html. 

Related: https://github.com/mandiant/capa/issues/1754

**Comment by psifertex** [comment]
The second page is an old version of the documentation but because of how we include the version number it doesn't look like it (check the copyright at the bottom instead).

We should actually just remove outdated pages so this would be a 404 instead. Note that this isn't a problem if you use the offline version of the documentation. 

I've got a script running now doing that so the file should return 404 shortly and redirect to the main index where you can find the correct one.

Note: if we have any outdated links in other parts of the documentation or other sites we'll need to find and update those.
