### ISSUE TITLE
Crashes when trying to load a Linux Kernel Module (*.ko file).

### ISSUE THREAD

**Issue by tur11ng** [Vector35/binaryninja-api#4682]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.4585-dev
- OS: Ubuntu Linux
- OS Version: 22.04
- CPU Architecture: x64

The bug is mainly stated in the title. I tried opening a modified version of the Diamorphine rootkit (seen in HackTheBox's CyberPsychosis challenge) and it completely crashed the application.

**Comment by xusheng6** [comment]
Link to the challenge: https://app.hackthebox.com/challenges/cyberpsychosis. I think this is a recent regression since I have opened the file in BN 1-2 months ago and it works fine

**Comment by xusheng6** [comment]
Weird enough, the crash happens in the pdb parser code: https://github.com/Vector35/pdb-rs/blob/b51abd394fdac8447274e5f79ac6d1c7b4c43b15/src/symbol/mod.rs#L347. Note this is a Linux so file

**Comment by KyleMiles** [comment]
After thinking about this for some time, I've decided to fix the crash and call this an "upstream bug." The root-cause here is that gimli (the library we use to parse DWARF) is encountering an entry in the DWARF debug tree with an unknown attribute. It's unclear to me whether this is caused by some sort of custom debug info generator or file corruption, but if we see more cases like these down the line and it turns out to be the former, we can explore what would need to be done to support that.

For now, it will print "DWARF information is seriously malformed. Aborting parsing." and discard any DWARF information. Handling arbitrary "corrupt" nodes would have wide-spread implications for the DWARF parser, and I'm going to keep this issue closed until we can collect additional samples like this that we can say for certain aren't caused by file corruption.

Regardless, you should be able to analyze this file now, and thank you for the report!

**Comment by tur11ng** [comment]
Diamorphine's source code can be found publicly available [here](https://github.com/m0nad/Diamorphine). You can try compiling it yourself and try parsing it with the old version and see what happens. I now have updated my instance and cannot have access to the old version (or at least I don't know how). Thanks you for your time and effort ;)
