### ISSUE TITLE
Application hang on close of the entire application

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4734]
**Version and Platform (required):**
- Binary Ninja Version: 3.6 on MacOS 14.0

I seem to be getting regular hangs on close. I don't know when this started happening but it was before Oct 6th 2023

**Comment by jonpalmisc** [comment]
I was just about to come report this, but I'm unsure if this refers to closing Binary Ninja the application or closing a tab. Closing tabs (even for small binaries) has a visible lag for me and blocks the UI. If this isn't what you were referring to I can create a separate issue, although I suspect the underlying cause is related.

**Comment by jonpalmisc** [comment]
Created a separate issue: https://github.com/Vector35/binaryninja-api/issues/4740

**Comment by bpotchik** [comment]
A hang was fixed in `3.6.4711-dev`.
