### ISSUE TITLE
Type change not propagated in synthetic functions 

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#4758]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4644-dev Personal, d289b1cc
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
The type for this stack string is void after loading the binary to BN.
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/ef419c4a-ed19-4040-8b9f-7b8c4a5515c2)

After changing the type to char arr[], the variable still tries to find the address with `&` in __builtin_strcpy. This also follows in the next line. 
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/5d04f231-4a46-401d-b87d-4ee279bfb779)

**Expected Behavior:**
Once the type changes from value type to address type (like an array or pointer), that information should propagate and change the way variable is referenced in other places. (no more `&`)

File:

[TTrack.zip](https://github.com/Vector35/binaryninja-api/files/13402644/TTrack.zip)

**Comment by xusheng6** [comment]
I think this is not related to type propagation. Your change from "void" to "char[0x21]" has actually taken effect, and the "&" operator is just the natural result of decompilation, it is semantically correct and precise, though it may not be the most straightforward since we often times omit that "&" when we code. 

As a bit of context, both code in C would compile:

```C
char var_50[0x21];
strcpy(var_50, "fooabr");
```
and 
```C
char var_50[0x21];
strcpy(&var_50, "fooabr");
```

I am closing this for now and pls feel free to re-open it if you have more inputs to it!
