### ISSUE TITLE
Coverage percent / Func header overlapping top view (string, hex, etc...)

### ISSUE THREAD

**Issue by TheKikGen** [Vector35/binaryninja-api#4775]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526 Personal, ec37d737
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**

**Steps To Reproduce:**
Simply open a new file to analyse then switch to hex view.  

**Expected Behavior:**

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/35703467/0d54961f-57eb-4f08-bc9c-184e6a2792a9)

**Additional Information:**

**Comment by psifertex** [comment]
That looks like a bug with the Lighthouse plugin? I'm assuming such since we don't have any native "Cov %" in our default UI. Can you confirm that disabling Lighthouse and restarting fixes the issue?

**Comment by psifertex** [comment]
Given that, I'm going to close this issue here and can either reopen it for you over on the lighthouse repo or if you want to open it yourself there either way that's probably the best way forward. 

I suspect it has something to do with a QT version change since I don't think it's been updated since the latest update.
