### ISSUE TITLE
#4430 Continuation of the problem

### ISSUE THREAD

**Issue by imethod** [Vector35/binaryninja-api#4825]
**Version and Platform (required):**
3.6.4718-dev
**Bug Description:**
#4430 
The problem doesn't seem to be with the 'it' command
Although the other issues have been fixed, the "goto" instruction truncation still occurs during analysis

Also, edit Current line doesn't work well 
If I type "b #0x12bce ", he calculates the offset automatically
And then the instruction will be "b #0x25794."
You have to type "b #8" +offset to get the correct jump address

One more thing #4575
This bug doesn't appear in ninja 3.4 so it should be easy to fix
My current sample has a lot of control flow flattening, please fix it quickly, look at me so uncomfortable
thanks o(〃^▽^〃)o

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
#4430 fix.so.zip 
goto 0x12bc2
edit Current line  "b #8"

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/ac89efa6-912c-4338-b8fd-6b7bd783febf)

**Comment by lwerdna** [comment]
> look at me so uncomfortable thanks o(〃^▽^〃)o

😂

Internally, we assemble using LLVM, and we don't know how to tell it to disassemble at a location other than 0. Jumps/branches that are supplied absolute addresses but encode to relative operands are mostly affected.

The official recommended workaround is to use the Keypatch plugin. Install it via the plugin manager. Go to 0x12bc2 and invoke it (using Plugins -> Keypatch or command palette) and enter `b #0x12bce`:

![cool](https://github.com/Vector35/binaryninja-api/assets/474191/ab38f3f1-e761-4db3-96cc-7e3cf193c0fb)

And you should get the correct instruction:

![cool2](https://github.com/Vector35/binaryninja-api/assets/474191/7348738b-8435-4af4-a21a-404e64beee49)

I'm closing this issue because the others you referenced (https://github.com/Vector35/binaryninja-api/issues/4430 and https://github.com/Vector35/binaryninja-api/issues/4575) are still open and are responsible for tracking those problems.
