### ISSUE TITLE
any possible to make this window resizable??

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#4838]
**What is the feature you'd like to have?**
Please provide a clear and concise description of what you want.
![image](https://github.com/Vector35/binaryninja-api/assets/5463104/25012e7a-cc41-4fa8-aae8-338c4c22016c)

**Comment by psifertex** [comment]
What window manager are you using? We're not doing anything to prevent resizing as far as I can tell. It's resizable on MacOS.

**Comment by bb33bb** [comment]
I use manjaro 
Tomorrow I will try again to check 
Thanks for your answer

**Comment by bb33bb** [comment]
> What window manager are you using? We're not doing anything to prevent resizing as far as I can tell. It's resizable on MacOS.

I check it again
Sorry I should make a clear description
It is resible
But it can not make smaller
That is we can change the window  bigger, but we can not make it smaller.

**Comment by psifertex** [comment]
Whoops, I mis-rememebered this was an issue and thought it came from slack and filed a duplicate issue at #4847. Sorry about that! I'm closing this as a duplicate even though the other one is the real duplicate because I already set all the appropriate labels for it. 😉 

Builds >= 4730 will let you make the dialog smaller than the default size.
