### ISSUE TITLE
`scripts/install_api.py` does not ship with executable permissions

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4846]
The `install_api.py` script does not ship with it's executable bit set by default. It seems like it should.

```
$ ./install_api.py
zsh: permission denied: ./install_api.py

$ ll
total 16
drwxr-xr-x   3 jp  admin    96 Sep 15 06:49 .
drwxr-xr-x  18 jp  admin   576 Sep 15 06:49 ..
-rw-r--r--   1 jp  admin  6156 Sep 15 06:49 install_api.py
```

Binary Ninja 3.5.4526 for macOS

**Comment by psifertex** [comment]
It should be run with the specific python version you want it to add the path to, it's actually a bit of a bad idea to just run it directly and trust the`/usr/bin/env python3` in the shebang to do the right thing. What we _should_ do is document this though, so I've updated the file itself to explain this in the header and also updated the documentation that references this.

**Comment by psifertex** [comment]
I should clarify, there's nothing _wrong_ with just defaulting to your default `python3` it's just that it's likely to cause confusion on systems with different pythons installed (as is often the case due to, say, Homebrew or Macports) and so making people aware that the version they run the script with will be the version of python that gets the `.pth` added is a good thing!

**Comment by jonpalmisc** [comment]
On second thought, I didn't even think to check the script for a shebang. I just assumed that ~~something this obviously wrong must have been a mistake /s~~ it had one and it was just a permissions issue in the DMG or something.

**Comment by psifertex** [comment]
I mean, it does have a shebang so that would lead you to ask this reasonable question. In fact, maybe I should just remove it entirely?
