### ISSUE TITLE
Symbol Focus Partially Visible in Experimental new Symbols List

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#4900]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526
- OS: macOS
- OS Version: 14.2.1
- CPU Architecture: x64

**Bug Description:**
Selecting a function in the disassembly pane shifts focus in the Symbols pane. However, under certain conditions, the symbol in focus is at the very bottom of the pane, and barely visible.

**Steps To Reproduce:**
1. Select a symbol in the Symbols pane.
2. Scroll up in the Symbols pane so that the selected symbol is not visible
3. Single click any visible symbol.
4. In the disassembly pane, double click the function with the first symbol.
5. Observe that the symbol name is in focus in the Symbols pane, but only partially visible.

**Expected Behavior:**
The in-focus symbol name should be at the top of the Symbol pane or as close as possible.

**Screenshots:**
<img width="916" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/2775739/0700c5c1-d2fe-4eed-bb4b-396080cf5b05">

**Additional Information:**
This appears to be dependent on the size of the Symbols pane. If you resize it slightly up or down, this problem is worse or better.

**Comment by fuzyll** [comment]
This repros for me on 3.6.4771-dev. Some additional considerations:

* In the user's step 1, you need to double-click so it navigates you to that symbol.
* In the user's step 4, you need to be in linear view because we don't have a double-click action on that text in graph view.

This is kind of annoying and I would at least expect the current selection to not be hidden/partially-hidden.
