### ISSUE TITLE
Pane painting fails after pane moved

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4908]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4774-dev, 20b49d1e
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Steps To Reproduce:**
See the GIF please.

Need to do it with a bit large function in order to bug happen.

**Screenshots:**
![Recording 2024-01-17](https://github.com/Vector35/binaryninja-api/assets/109607896/931c4ee5-0490-49e0-8606-2050035f7eb7)

**Comment by xusheng6** [comment]
@op2786 do you have a binary that we can reproduce this with?

**Comment by op2786** [comment]
It is not a zip file. Just `ls` binary with `.zip` extension. You can reproduce the issue at `100006b2d`

[ls.zip](https://github.com/Vector35/binaryninja-api/files/14023107/ls.zip)

**Comment by fuzyll** [comment]
I have two functions in split panes, one disassembly and one HLIL, and I'm moving them around in ways similar to the GIF. But, I can't seem to reproduce this.

I am using macOS 14.3 and Binary Ninja 4.0.4868-dev. Is this still an issue you're seeing? Or, did we perhaps squash this one in the ~100ish builds since this was reported?

**Comment by op2786** [comment]
Seems like it is resolved. I'm not able to reproduce this anymore. @fuzyll
