### ISSUE TITLE
need better reversed Instructions Displayed

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#4918]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4780-dev Personal (d35c49ed)
- OS: manjaro
- OS Version: Linux version 6.6.10-1-MANJARO 
- CPU Architecture: x64

**Bug Description:**
the same to #4916 
I can not make it open , so type a new issue .
Sorry to upload the wrong example inlast issue
**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:

**Expected Behavior:**

**Screenshots:**

![image](https://github.com/Vector35/binaryninja-api/assets/5463104/68fe1ecd-7a0a-4fc6-90f8-be7e1bb8008d)

**Additional Information:**

**Comment by psifertex** [comment]
Heh, that makes more sense. I was wondering why it didn't quite look the same. :-) 

does "p" or the make function context menu I mentioned in the other issue work? For extremely small samples without code references it's not surprising that some dead code wouldn't be identified but it should be easy to manually trigger analysis. 

Looking a bit more closely it looks like there's some pointer issues either due to relocations not being applied or the code supposed to be based at a different address maybe? That could explain why the code isn't being identified if there are supposed to be branches. I'll take a closer look again later.

**Comment by bb33bb** [comment]
> Heh, that makes more sense. I was wondering why it didn't quite look the same. :-)
> 
> does "p" or the make function context menu I mentioned in the other issue work? For extremely small samples without code references it's not surprising that some dead code wouldn't be identified but it should be easy to manually trigger analysis.
> 
> Looking a bit more closely it looks like there's some pointer issues either due to relocations not being applied or the code supposed to be based at a different address maybe? That could explain why the code isn't being identified if there are supposed to be branches. I'll take a closer look again later.

p works
thats ok
i will close this issue.

**Comment by psifertex** [comment]
If you do want to upload the file so I can take a look at it I don't mind seeing if there's something else we can do to make it automatically identify everything, hard to do with just a screenshot. But at least you know the work-around for manual code creation!
