### ISSUE TITLE
Incorrect main function detection in PE, PDB causes duplicate `main`

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#4977]
We declare the wrong function as main in a PE via heuristics.
Also, when a pdb applies a symbol over our auto symbol we might want to remove our auto symbol.

v35 people can search for `funky mushroom planet revolution` for the files

**Comment by xusheng6** [comment]
This is caused by one of the detection heuristic we are using. When we see "invoke_main", we check the last call to check it for the main function. However, in this binary, the main is actually being jumped to, not called

![image](https://github.com/Vector35/binaryninja-api/assets/94503187/48732307-009d-417f-b940-e4f13eb84a1c)

**Comment by xusheng6** [comment]
I have fixed the issue for the particular binary in dev 3.6.4808. The suggested improvements are added to https://github.com/Vector35/binaryninja-api/issues/4814
