### ISSUE TITLE
Changing certain settings from Project-owned window does not update or save setting

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5002]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4818
- OS: macOS
- OS Version: macOS 14.1 23B73 arm64 

**Bug Description:**
Changing certain settings from Project-owned window does not update or save setting

**Steps To Reproduce:**
1. Open 3.6.4818 commercial/enterprise build
2. Open a Project
3. From the Project window, hit `Cmd+,` to open settings
4. Change the theme

**Comment by 0cyn** [comment]
This also repros with `rendering.hlil.newLinesAroundScopes`

**Comment by fuzyll** [comment]
I have seen this as well and thought it might be related to #2630. I haven't been able to repro with the steps provided because `Cmd+,` is totally broken for me since the action tries to trigger Settings from the first window and fails, opening nothing.

**Comment by 0cyn** [comment]
It does not repro via opening a secondary, non-project-owned window from the first.

**Comment by bpotchik** [comment]
Use `Cmd`+`Shift`+`.`

**Comment by bpotchik** [comment]
Fixed in `4.0.4829-dev`.

Currently:
`Cmd`+`.` => Opens to Resource settings for the current BinaryView; if no BinaryView then opens "Project Settings", if a current project is available
`Cmd`+ `Shift` + `.` => Always opens "Project Settings", if a current project is available
`Cmd` + `,` => Opens to User settings

Note: The prior behavior where `Cmd`+`,` does nothing from the project browser persists. It should probably be made to work as well. Was this disabled on purpose or is it a bug?
