### ISSUE TITLE
`UnicodeDecodeError` when installing/updating BinSync on Windows via Manage Plugins

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#5192]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.4966-dev Personal (ddc14755)
- OS: Windows
- OS Version: 10.0.26080.1400
- CPU Architecture: x64
- Python Version: 3.11.4

**Bug Description:**
When installing/updating BinSync on Windows via Manage Plugins, I see this in the log:

```text
[Default] BinSync
[Default] Exception ignored on calling ctypes callback function: <bound method PythonScriptingProvider._install_modules of <binaryninja.scriptingprovider.PythonScriptingProvider object at 0x000001F3564F4750>>
[Default] Traceback (most recent call last):
[Default]   File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 1414, in _install_modules
[Default]     if python_bin is not None and not self._pip_exists(str(python_bin), python_env=python_env):
[Default]                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Default]   File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 1316, in _pip_exists
[Default]     return self._run_args([python_bin, "-m", "pip", "--version"], env=python_env)[0]
[Default]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Default]   File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 1311, in _run_args
[Default]     return (True, subprocess.check_output(args, startupinfo=si, stderr=subprocess.STDOUT, env=env).decode("utf-8"))
[Default]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Default] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 29: invalid start byte
[Default] Successfully updated:
```

**Steps To Reproduce:**
Install or update BinSync via Manage Plugins. I would guess that there are also some environmental factors needed to reproduce this, but I don't know what exactly.

**Expected Behavior:**
No exception.

**Comment by alexrp** [comment]
I just realized I actually already mentioned this over in #4510. :eyes: But I guess it's a different issue since the Python plugin loads fine after that was fixed.

Also, it's just installing/updating BinSync in particular that seems to break. (No other plugins that I've tried have this issue.)

**Comment by xusheng6** [comment]
This happens when binary ninja tries to run the following command: `python -m pip --version`. On my box, this returns: `pip 24.0 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`. On a Windows box, this path probably includes the user's home directory, which contains non-ASCII chars. And since the python.exe that comes with binary ninja is not built with UTF-8 as default code page, it is probably returning the string in another encoding. So that the subsequent `decode("utf-8")` fails.

I guess we just need to apply the same fix as https://github.com/Vector35/binaryninja-api/issues/4510, but this time to python.exe. For reference: https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

**Comment by alexrp** [comment]
Just to clarify, I'm not using the Python shipped with BN, but rather Python 3.11.4 installed from python.org.

**Comment by xusheng6** [comment]
> Just to clarify, I'm not using the Python shipped with BN, but rather Python 3.11.4 installed from python.org.

Thanks for the info! Then I think the problem is trickier -- we can control what Python we ship, but we cannot control what Python people are using. 

Also, just wish to confirm my guess, would you please run `python -m pip --version` (with the python 3.11.4 you mentioned above), redirect the output to a file, and let me know its content and encoding?

**Comment by xusheng6** [comment]
We might need to do something like this: https://github.com/mandiant/capa/blob/master/capa/features/extractors/binja/find_binja_api.py, that have the python script encode the output as hex, and we then harvest it

**Comment by xusheng6** [comment]
I proposed a temporary fix which avoids running a command that may return non-ASCII chars: https://github.com/Vector35/binaryninja-api/commit/c6cad5b7c551

**Comment by alexrp** [comment]
```
❯ /c/Program\ Files/Python311/python.exe -m pip --version > pip-ver
❯ file pip-ver
pip-ver: ISO-8859 text, with CRLF, CR line terminators
```

**Comment by xusheng6** [comment]
> ```
> ❯ /c/Program\ Files/Python311/python.exe -m pip --version > pip-ver
> ❯ file pip-ver
> pip-ver: ISO-8859 text, with CRLF, CR line terminators
> ```

Thanks for the info! This confirms my guesses. 

At the same time, would you like to apply the patch in https://github.com/Vector35/binaryninja-api/commit/c6cad5b7c551 and see it it actually fixes the problem? This issues is a bit inconvenient for me to test, so if I can get feedback from you directly that would be very helpful! The `scriptingprovider.py` should be in `%APPDATA%\Vector35\BinaryNinja\python\binaryninja`

**Comment by alexrp** [comment]
Yes, that patch seems to work fine on my end. BinSync now installs w/o any errors.
