### ISSUE TITLE
Proper disassembly but IL fails

### ISSUE THREAD

**Issue by thanasisk** [Vector35/binaryninja-api#5296]
[main.nes.gz](https://github.com/Vector35/6502/files/8608172/main.nes.gz)
The following file while it disassembles properly (compared output with Mesen emulator), fails miserably at IL (starting from low level IL and going upwards). Might make an interesting test case. The file was taken from Angstrom CTF 2022

**Comment by fuzyll** [comment]
Going to go ahead and close this because, as far as I can tell, it still seems like it's working:

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/9c83a482-c8b9-4bce-8d8b-c1d02dd9794c">

Please feel free to reopen this with specific repro steps or additional information if I'm mistaken.
