### ISSUE TITLE
Support for external symbol/debug file

### ISSUE THREAD

**Issue by Manouchehri** [Vector35/binaryninja-api#534]
https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

**Comment by psifertex** [comment]
Are you asking specifically for support for this file format or just having symbols in an external file? As to the later, that's essentially what our `.bndb` files are. If you're looking for support for this particular file format, it's likely better off as a plugin than a core feature and I doubt it would be very much work but probably not something we'd focus on since it's so easy to implement using the existing API.

**Comment by Manouchehri** [comment]
Was referring to the former.

**Comment by KyleMiles** [comment]
I'm going to mark this as closed.  Generally "support for external symbol/debug files" is now supported via the load option `loader.debugInfoExternal` (which accepts a file path), the UI action under `Analysis` -> `Import Debug Info from External File`, or through the `DebugInfo` APIs. Specific `.debug` support is provided with [the official DWARF-import plugin](https://github.com/Vector35/dwarf_import), and better support should be coming with #3206.
