### ISSUE TITLE
Suspected memory leak: large amount of RAM is only freed after another file is opened

### ISSUE THREAD

**Issue by romanholidaypancakes** [Vector35/binaryninja-api#5354]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4911 free,  15e9149
- OS: windows
- OS Version: 10
- CPU Architecture: x86_64

**Bug Description:**

**Steps To Reproduce:**
When multiple files are opened for analysis in the same process, only the tab page for file analysis is retained; it can be found that the memory does not decrease.

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by xusheng6** [comment]
Could you please provide repro steps? I am not exactly sure what you mean (I know what you mean in general, but what in enough detail for me to reproduce it)

**Comment by negasora** [comment]
Does it repro with the latest free version? Should be 4.1.4958

**Comment by psifertex** [comment]
Pretty sure that was a typo. The last four matching are the most importabt bits.

**Comment by xusheng6** [comment]
Hi @romanholidaypancakes, I tried but cannot reproduce this. How did you measure the memory usage? 

Also, by the design, type objects are always leaked even after closing the file, though I do not think that should cause significant memory usage

**Comment by negasora** [comment]
If after those steps you:
1. Open the file again
2. Let analysis finish
3. Close the tab
Does memory usage drop back to ~417MB?

**Comment by xusheng6** [comment]
From the given information, I am not exactly sure whether there is a memory leak. Usually we do not use the memory usage info reported by the system as the measurement for memory usage. We use the following command in the Python console:

```
>>> get_memory_usage_info()
{'Active BasicBlock objects': 72, 'Active BinaryView objects': 2, 'Active Component objects': 0, 'Active FileMetadata objects': 1, 'Active FlowGraph objects': 0, 'Active Function objects': 4, 'Active LowLevelILFunction objects': 12, 'Active MediumLevelILFunction objects': 16, 'Active Type objects': 2086, 'Active TypeArchive objects': 0}
```

Which is, unfortunately, unavailable in the free version. That said, I have performed the process on the latest dev builds of the free version (which is not available to the public), and the above command will report 0 binary view objects after the operation. Which, according to our standard, means there is no outstanding memory leak. 

The memory usage you are seeing is a bit deceptive. You might think the initial RAM usage is like 30.2 MB, and in the end it becomes 417 MB and there must be a memory leak. However, this is not the case. Since, when you simply open binary ninja and do not open any file, there are many things that are not loaded, e.g., type libraries. Type libraries are only loaded when you open a file, and by design they are not freed even after the file itself has been closed. So in other words, the RAM consumption of an idle binary ninja is ~417MB. 

That is also the reason why my colleague is asking you to test if the memory usage would go down to 417MB after you open another file and then close it. If it does, then there is probably no memory leak. If it goes up a lot, then there is a memory leak. However, the memory usage is about 465MB after the process, and I cannot tell for sure whether there is a memory leak or not. We will need to look further into the issue

**Comment by xusheng6** [comment]
@negasora I noticed an interesting behavior, that if I open a very simple file as the second file (rather than opening the same file), the memory usage actually goes down (smaller than 417MB), even while the second file is open. I highly suspect that certain objects associated with the first file are leaked and they are only freed when a second file is opened. I have previously seen a case where the Python console causes delayed free-up of resources. Though this particular bug has been fixed a while ago

**Comment by saagarjha** [comment]
I can reproduce this quite easily on my Mac. All I need to do is open a large file (which uses massive amounts of memory–30+ GB on my machine) and then close it. It is quite obvious that it's not being freed because my memory usage barely changes after doing that. In fact if I close all my tabs I get this output which seems unexpected:

```console
>>> get_memory_usage_info()
{'Active BasicBlock objects': 5566127, 'Active BinaryView objects': 19, 'Active Component objects': 0, 'Active FileMetadata objects': 9, 'Active FlowGraph objects': 0, 'Active Function objects': 1455938, 'Active LowLevelILFunction objects': 1261, 'Active MediumLevelILFunction objects': 1688, 'Active Type objects': 2932766, 'Active TypeArchive objects': 0}
```

**Comment by xusheng6** [comment]
> I can reproduce this quite easily on my Mac. All I need to do is open a large file (which uses massive amounts of memory–30+ GB on my machine) and then close it. It is quite obvious that it's not being freed because my memory usage barely changes after doing that. In fact if I close all my tabs I get this output which seems unexpected:
> 
> ```
> >>> get_memory_usage_info()
> {'Active BasicBlock objects': 5566127, 'Active BinaryView objects': 19, 'Active Component objects': 0, 'Active FileMetadata objects': 9, 'Active FlowGraph objects': 0, 'Active Function objects': 1455938, 'Active LowLevelILFunction objects': 1261, 'Active MediumLevelILFunction objects': 1688, 'Active Type objects': 2932766, 'Active TypeArchive objects': 0}
> ```

is there any chance that you can provide the binary involved? Also the 19 active BinaryView objects are quite uncommon -- usually we just create a few (2-3) binary views for each file. Have you been using binary ninja for a while before you open the offending file? Or it behaves like that even if you open the file fresh?

**Comment by saagarjha** [comment]
I don't actually remember which binary this was but I'm pretty sure when I was doing that it was just some random large binary I had lying around. FWIW I tried this on the latest dev build and after closing the tab I don't see any binary views lying around, but memory usage is still very high due to hundreds of thousands of basic blocks being retained. This seems unfortunate to me…?

**Comment by xusheng6** [comment]
> I don't actually remember which binary this was but I'm pretty sure when I was doing that it was just some random large binary I had lying around. FWIW I tried this on the latest dev build and after closing the tab I don't see any binary views lying around, but memory usage is still very high due to hundreds of thousands of basic blocks being retained. This seems unfortunate to me…?

That is weird, if binary views are gone then basic blocks should also be gone. They could not even exist outside of a binary view. Let me try to reproduce it

**Comment by xusheng6** [comment]
I can almost certainly confirm this is a memory leak. I opened a giant shellcode buffer in binja and the memory usage goes up to 5GB and even more. Closing it causes the RAM usage to drop to 4.9 GB, but it is still significantly larger than what the initial usage looks like, which is around 131MB.

This shellcode loads zero types into binja, and opening other smaller regular files (e.g., a PE with various types imported) does not cause the RAM usage to go up that high), which means of the 4GB RAM it eventually occupies, many are specific to the file and should have been released, but not.

**Comment by VisualEhrmanntraut** [comment]
I have similar leak on Mac but with Types instead of BasicBlocks.
```
>>> get_memory_usage_info()
{'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 434464, 'Active TypeArchive objects': 0}
```
This is after opening a few databases then closing them. Total memory usage at that point is around 3GB.

**Comment by xusheng6** [comment]
> I have similar leak on Mac but with Types instead of BasicBlocks.
> 
> ```
> >>> get_memory_usage_info()
> {'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 434464, 'Active TypeArchive objects': 0}
> ```
> 
> This is after opening a few databases then closing them. Total memory usage at that point is around 3GB.

The "leak" on the Type object are expected behavior -- they are by design never freed. That is why I called it a suspected memory leak initially. However, the types along would not consume gigabytes of RAM. 

As I dig deeper, it seems we are also leaking memory on things related to analysis, e.g., MLIL SSA variables. I will continue to investigate this later

**Comment by plafosse** [comment]
So many Types objects are cached for both the platform and other common type objects. To verify a type leak you'd need to re-open the same file and close it and see the number of 'Active Type objects' continue to increase.

**Comment by xusheng6** [comment]
> So many Types objects are cached for both the platform and other common type objects. To verify a type leak you'd need to re-open the same file and close it and see the number of 'Active Type objects' continue to increase.

Type objects do not increase according to my test, so we are not leaking type objects

**Comment by VisualEhrmanntraut** [comment]
Ah, I see, I'd expect that the Types would be freed as some could be big in size and I didn't think that there would be a benefit to caching them.

**Comment by VisualEhrmanntraut** [comment]
I opened a database then closed it and reopened it again and it leaked Type objects
```
>>> get_memory_usage_info()
{'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 47085, 'Active TypeArchive objects': 0} 
>>> get_memory_usage_info()
{'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 47242, 'Active TypeArchive objects': 0}
```

**Comment by xusheng6** [comment]
> I opened a database then closed it and reopened it again and it leaked Type objects
> 
> ```
> 
> >>> get_memory_usage_info()
> 
> {'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 47085, 'Active TypeArchive objects': 0} 
> 
> >>> get_memory_usage_info()
> 
> {'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 47242, 'Active TypeArchive objects': 0}
> 
> ```

Interesting -- though I believe it's actually a separate issue. Does the test binary involve PDB or DWARF parsing?

**Comment by VisualEhrmanntraut** [comment]
> > I opened a database then closed it and reopened it again and it leaked Type objects
> > ```
> > 
> > >>> get_memory_usage_info()
> > 
> > {'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 47085, 'Active TypeArchive objects': 0} 
> > 
> > >>> get_memory_usage_info()
> > 
> > {'Active BasicBlock objects': 0, 'Active BinaryView objects': 0, 'Active Component objects': 0, 'Active FileMetadata objects': 0, 'Active FlowGraph objects': 0, 'Active Function objects': 0, 'Active LowLevelILFunction objects': 0, 'Active MediumLevelILFunction objects': 0, 'Active Type objects': 47242, 'Active TypeArchive objects': 0}
> > ```
> 
> Interesting -- though I believe it's actually a separate issue. Does the test binary involve PDB or DWARF parsing?

It's a symbolicated Mach-O with no dSYM.

**Comment by VisualEhrmanntraut** [comment]
Resigned the binary and opened it with Instruments

All allocations

<img width="1281" alt="image" src="https://github.com/user-attachments/assets/95ba5c4c-b923-415e-aba7-937ec4140a6a">

Persistent allocations

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/ea02af98-6c5f-4f16-8e62-e0a0f3d397d5">

Maybe this helps. Binary Ninja 4.2.6304

**Comment by VisualEhrmanntraut** [comment]
And what it thought were leaks
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/985dff2c-8192-4e3f-87f1-02be48d15e64">

**Comment by VisualEhrmanntraut** [comment]
As it didn't really detect leaks, seems to me like one or more things are getting retained and not freed until BN is closed.

**Comment by VisualEhrmanntraut** [comment]
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/6bc96834-ac6c-4dbe-a014-8110edb99647">
Persisted allocations compared to first open of BN and after the database closed.

**Comment by xusheng6** [comment]
Upon further investigation, I find the memory usage not going down is caused by the jemalloc's memory retention behavior. I.e., it reserves the memory previously allocated and do not immediately return it to the OS so as to avoid frequent reallocation. So it is not technically a leak.

However, I still think we should explicitly ask jemalloc to free the allocated RAM after a binary view object is closed. Will take this discussion to the team

**Comment by VisualEhrmanntraut** [comment]
~~May I suggest not using jemalloc?~~

**Comment by xusheng6** [comment]
I already have a fix for this and will land it after the stable release

**Comment by saagarjha** [comment]
```
>>> get_memory_usage_info()
{'Active BasicBlock objects': 951055, 'Active BinaryView objects': 3, 'Active Component objects': 0, 'Active FileMetadata objects': 1, 'Active FlowGraph objects': 0, 'Active Function objects': 213637, 'Active LowLevelILFunction objects': 267, 'Active MediumLevelILFunction objects': 356, 'Active Type objects': 3059497, 'Active TypeArchive objects': 0}
```

I loaded a shared cache and a few libraries, then closed it. I take it that this is not intended?

**Comment by xusheng6** [comment]
> ```
> >>> get_memory_usage_info()
> {'Active BasicBlock objects': 951055, 'Active BinaryView objects': 3, 'Active Component objects': 0, 'Active FileMetadata objects': 1, 'Active FlowGraph objects': 0, 'Active Function objects': 213637, 'Active LowLevelILFunction objects': 267, 'Active MediumLevelILFunction objects': 356, 'Active Type objects': 3059497, 'Active TypeArchive objects': 0}
> ```
> 
> I loaded a shared cache and a few libraries, then closed it. I take it that this is not intended?

Yeah this is surely a memory leak. However, I believe it is related to the shared cache. Could you please test and confirm it? If so, please file a new issue. 

This issue mainly concerns the jemalloc's memory retention behavior

**Comment by saagarjha** [comment]
Ok, I'll see if I can reproduce it for other binaries and let you know. Thanks!
