### ISSUE TITLE
Support enum as structure field in switch condition

### ISSUE THREAD

**Issue by emesare** [Vector35/binaryninja-api#5499]
**Bug Description:**
Normally enum in the condition expression of a switch statement will propagate the enum to the switch cases, however in cases where the enum is nested in a structure field, like on partial accesses, the enum is not.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to switch case
2. Make the switch condition an enum with partial access (i.e. `switch (myenum.d)`)
3. Observe no enum type propagation to switch cases

**Expected Behavior:**
A switched on structure field enum will have the switch cases display as the appropriate enum item

**Additional Information:**
Slack discussion: https://binaryninja.slack.com/archives/C0CVALTLN/p1715685078352569

**Comment by xusheng6** [comment]
Looking the MLIL SSA, I feel like the issue is when we have an `zx.q(enum)`, then the type of the expression becomes the integer of the extended size, and it is no longer the enum type. 

![Uploading Screenshot 2024-06-06 at 2.25.16 PM.png…]()

Should we change the way the type propagation works and make it retain the enum type, in case of a zx.q?

**Comment by emesare** [comment]
IIRC setting the type on `x8_2#3` breaks the switch-case detection because it moves the `zx.q` into the jump table expr preventing the switch-case detection.

If that is the case, maybe the solution is to fix the switch-case detection for `zx.q` and then we can easily deduce the enum type from within.

```c
switch (zx.q(my_enum)) { ... }
```
