### ISSUE TITLE
Comments on adjacent fields of structure rendered incorrectly (not visible)

### ISSUE THREAD

**Issue by mostobriv** [Vector35/binaryninja-api#5550]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5442-dev Personal
- OS: macOS

**Bug Description:**
When setting comment on adjacent structure fields, the one with higher address just not rendered.

**Steps To Reproduce:**
1. Define structure with 2+ fields
2. Apply this type to any address in database
3. Add comments to adjacent fields
4. You won't see some comments

**Expected Behavior:**
All the comments should be rendered/visible.

**Screenshots/Video Recording:**
<img width="1563" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/15954313/319a7779-c30f-4133-b1aa-47e49ab89667">

**Additional information:**
As you may see on screenshot, there is 2 comments on `0x10000410c` and `0x100004110`, but only the one on `0x10000410c` is visible. 

To ease repro a bit, here is database from screenshot:
[attachment.zip](https://github.com/user-attachments/files/15785175/attachment.zip)

**Comment by rssor** [comment]
Fixed in build 6429. Comment placement has been rewritten entirely to strongly prefer lines that contain actually bytes (ignoring lines with only braces or no actual data on them), no longer duplicate comments, and no longer lose comments when adjacent lines all have comments. Multi-line comment formatting has been fixed, and build 6430 has fixes for tag rendering inside a DataVariable as well.
