### ISSUE TITLE
Add support for popups (not message boxes) in the API

### ISSUE THREAD

**Issue by riskydissonance** [Vector35/binaryninja-api#5628]
**What is the feature you'd like to have?**
I'd like to be able to show a popup on the UI using the API, such as the one that provides a preview:

![image](https://github.com/Vector35/binaryninja-api/assets/20513519/1fc65260-51f2-4e37-8008-df5e717cfc27)

**Is your feature request related to a problem?**
I would like write a plugin to bind this popup to a hotkey (in my case `Ctrl-q`) which when pressed while hovering over a symbol (E.g. `VirtualAlloc` ) will attempt to find MDSN documentation for that symbol and show it in the popup. This is analogous to the JetBrains suite when hovering over something and pressing `ctrl-q` you get a popup with information:

![image](https://github.com/Vector35/binaryninja-api/assets/20513519/0d312897-7365-42bd-b728-ec2349d5f4ee)

The API should also support showing the popup on hover etc as well, though that is not my use case.

**Are any alternative solutions acceptable?**
None

**Additional Information:**
None

**Comment by psifertex** [comment]
Making a new window or making the tooltips arbitrarily configurable is actually already possible but using the QT API. We'd have to do a ton of work to replicate it to make it stand-alone without QT, so instead I'm just going to document the APIs and how I would make those changes here:

First, for this particular use-case I wouldn't even open up a tooltip but would rather just pop open a web-browser directly since it's very little code and it leverages the already existing system default browser:

```
>>> import binaryninjaui
>>> from PySide6.QtGui import QDesktopServices
>>> QDesktopServices.openUrl("https://google.com/")
True
```

A tool-tip style popup is a bit more work, I've got a bug in the sample I threw together, once I fix that I'll post it here.

**Comment by psifertex** [comment]
Here's an example of tooltip code you can use as well. Thanks @fuzyll for the help with it!

```python
from PySide6.QtWidgets import QWidget, QLabel, QVBoxLayout, QApplication, QMainWindow
from PySide6.QtCore import Qt, QPoint
import binaryninjaui

class TooltipPopup(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent, Qt.Window | Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)
        self.setFocusPolicy(Qt.StrongFocus)
        self.setWindowTitle("Tooltip Popup")

        layout = QVBoxLayout()
        label = QLabel("This is a tooltip-style popup. Press ESC to close.")
        layout.addWidget(label)

        self.setLayout(layout)
        self.adjustSize()

    def keyPressEvent(self, event):
        # This causes the fake tooltip to be closed when you hit Esc
        if event.key() == Qt.Key_Escape:
            print("Escape key pressed")
            self.close()
            event.accept()
        else:
            super().keyPressEvent(event)

    def showEvent(self, event):
        # This forces the fake tooltip to be focused
        super().showEvent(event)
        self.raise_()
        self.activateWindow()
        self.setFocus()
    
    def focusOutEvent(self, event):
        # This closes the fake tooltip when the user clicks into another UI element
        print("Lost focus")
        self.close()
        super().focusOutEvent(event)

def show_tooltip_popup(parent, pos):
    tooltip_popup = TooltipPopup(parent)
    tooltip_popup.move(pos)
    tooltip_popup.show() 
    parent.tooltip_popup = tooltip_popup  # Keep a reference to the tooltip

# Assuming this is within the context of an existing PySide6 application
ctx = binaryninjaui.UIContext.allContexts()[0]
mw = ctx.mainWindow()

execute_on_main_thread(lambda: show_tooltip_popup(mw, QPoint(100, 100)))
```

**Comment by fuzyll** [comment]
Some extra context for the code above: It doesn't use an "actual" Qt Tooltip because tooltips can't be an 'active' window (see [documentation](https://doc.qt.io/qt-6/qtooltip.html)). This means they can't respond to things like key-press events, even if you try to catch the event yourself. As a result, the code above fakes one with `Qt.FramelessWindowHint` and `Qt.WindowStaysOnTopHint`.

**Comment by riskydissonance** [comment]
Thanks both, greatly appreciated!

**Comment by 0xdevalias** [comment]
If it isn't already, I wonder if this info could be added to a section of the BN developer docs somewhere? It seems like really useful info to not let it get lost buried away in an ephemeral issue.

**Comment by psifertex** [comment]
It's a bit big for the [cookbook](https://docs.binary.ninja/dev/cookbook.html) so I've [added](https://github.com/Vector35/binaryninja-api/commit/049653a315d5bf0178dc8501f2ab513e6c2d018b) it to [examples](https://github.com/Vector35/binaryninja-api/tree/dev/python/examples)
