### ISSUE TITLE
Binja EE Server Welcome Page - Add location for settings.json file

### ISSUE THREAD

**Issue by mwales** [Vector35/binaryninja-api#5663]
**Version and Platform (required):**
- Binary Ninja Version: Enterprise Server 1.2.208-stable
- OS: Redhat something? / Ubuntu 20.04 for client
- OS Version: [e.g. 22.04]
- CPU Architecture: x64

**Bug Description:**
Go to Enterprise welcome page.  I can download Binja from links on the page from step 1.

Step 2 should says where settings.json should go / full path.  I guessed ~/.binaryninja, but I know other Linux programs use different conventions for path to settings file.  So I think you should say where to put the settings file (depending on OS I presume it changes).

The comma at the end of the line doesn't work (if its the only setting in between the braces).  and i assume the elipses wont work either.  I was somewhat concerned that if I made my own settings.json (that is only 1 setting), would that somehow break / prevent Binja from creating it's own populated with defaults when it finally does get up and running in happy state.  But my personal version of Binja looks like it never created one at all, so maybe not an issue.

Or just have settings.json get shoved into your download links and look in the folder where binaryninja is located.

**Comment by fuzyll** [comment]
We're actually working on an entirely new workflow for setting the initial server URL right now for the upcoming 4.1 release next month that should obviate the need for this. (It'll wind up creating the `settings.json` for you with the server you specify.) Keeping this issue open until we've got the fix in for this on a `dev` build, though.

For completeness:

* The user folder location is [documented here](https://docs.binary.ninja/guide/index.html#user-folder) and includes all 3 platforms.
* Since it's a JSON file, the trailing comma _will_ be an error if it's the last entry.
* Creating your own one-line `settings.json` file of `{ "enterprise.server.url": "https://your-server-here.com:3535" }` should be perfectly fine and not interfere with Binja making changes (assuming ownership is set properly on the file).

**Comment by CouleeApps** [comment]
As of 4.1.5591 there is now an updated workflow for configuring a server when you first start, where you can enter the server url manually (or the other methods still work). That brings this down to being a documentation issue now, which should be pretty easy to resolve.

**Comment by fuzyll** [comment]
I re-wrote step 2 of the welcome page to address the new changes we made. This should now be complete as of last Friday.
