### ISSUE TITLE
On Windows the `GetObject` function is renamed because of `#include <windows.h>`

### ISSUE THREAD

**Issue by mrexodia** [Vector35/binaryninja-api#5830]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5747-stable
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
In `binaryninjaapi.h` you include `windows.h`, which defines `GetObject`:

![image](https://github.com/user-attachments/assets/a74b8d2f-5a30-4c34-bfb2-9b4121df9842)

This does not cause any issues, but it means all the `GetObject` functions are renamed to `GetObjectA`.

Adding `#undef GetObject` after the include fixes it, but I'm not sure it's the cleanest solution.

**Comment by CouleeApps** [comment]
We've tried a number of times to fix this in the past and it has led to weird linker errors when one translation unit gets the #undef and another doesn't. We have given up trying to fix it as a result of this, and since it doesn't impact the code as written it shouldn't matter. If we were to make any change (and with such a critical api, very unlikely this will happen) it would be to try and avoid running into the winapi defines in the first place.

Or to quote the collab headers:

    \note Named with an underscore after a valiant defeat against winapi
