### ISSUE TITLE
Reconsider no longer constant data variables

### ISSUE THREAD

**Issue by emxll** [Vector35/binaryninja-api#5895]
**What is the feature you'd like to have?**
When changing a section containing a data variable (or at this point constant) from read-only to read-write, binary ninja will not reconsider these variables as mutable. It would be nice to have an option to force a refresh.

**Is your feature request related to a problem?**
Commonly, when a variable in the data section contains a pointer `ptr` that is initialized to `0`, accesses to offset `0xabc` will be treated as `*(0xabc)` instead of `*(ptr + 0xabc)`.

**Are any alternative solutions acceptable?**
The only thing I've been able to come up with is patching the binary to change section semantics and creating a new binary ninja project. However, that solution isn't really acceptable to me.

**Additional Information:**
I'm reversing a Mach-O.

**Comment by emxll** [comment]
I noticed (by looking in the memory map view) that the relevant segment (not section) was still RO so I went and patched initprot/maxprot for the relevant segment to be RW in the hex editor (the memory map view wouldn't let me), then did Analysis > Reanalyze and restarted binary ninja. That seems to have fixed it.

**Comment by bpotchik** [comment]
We have not updated the UI yet, however instead of patching the file header, you can also modify segment flags via the MemoryMap API in the python console.

Show the memory map:
`bv.memory_map`

Update flags for a named region:
`bv.memory_map.set_memory_region_flags("origin<PE>@0x400", SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable)`

We are planning to update the semantics/permissions model so that only updating the section will give you the desired behavior.
