### ISSUE TITLE
Cookbook documentation on creating structures via API

### ISSUE THREAD

**Issue by mwales** [Vector35/binaryninja-api#5929]
I wasted too much time trying to figure out how to create a new custom type via API.  ChatGPT was actually somewhat helpful.  I like cookbook section of docs, lots of good common recipes.

zznop pointed somone to this bit of source for creating a structure with structure builder and it was very helpful.

https://github.com/zznop/bnida/blob/master/binja/binja_import.py#L150

Also, a bunch of the scripting mechanics I use all the time like bv. I have no idea where that was documented anywhere, i just saw it used by other snippets.  "here" is also a thing that my teammate found that we don't know where it is documented, or if other helpful little things like that we don't know about.  Perhaps add some of that to the cookbook as well (unless I missed it elsewhere)

Lastly, the documentation for big classes like binaryview is soooooo long.  Could you configure the documentation to compile a more concise index of sorts with links to the full documentation.  Like Qt docs as an example:  https://doc.qt.io/qt-6/qlist.html

**Comment by mwales** [comment]
Either you guys recently added it, or I somehow missed it.  But there is a link to the magic variables page that I guess I somehow missed but just discovered today while reading through documentation.  Disregard paragraph 4 above, i'm just blind...

**Comment by fuzyll** [comment]
(Which is here, for anyone that comes across this in the future: https://docs.binary.ninja/guide/index.html?h=magic#magic-console-variables)

**Comment by CouleeApps** [comment]
All of the API documentation is under the Developer Guide section of the docs. Type creation is mostly found under https://docs.binary.ninja/dev/annotation.html

**Comment by psifertex** [comment]
RE: on the last item, we actually used to have this but it necessitated a bunch more pages of documentation which slowed the updates down so we intentionally removed it. I think we'll pretty much just leave this as "closed won't fix" for now unfortunately since it's not a tradeoff we're likely to make again. Unless the sphinx automodule code adds support for it

I think that covers most of the items requested but feel free to clarify if there's anything left and I'll reopen.
