### ISSUE TITLE
Recognize indirect calls to got entries

### ISSUE THREAD

**Issue by saelo** [Vector35/binaryninja-api#593]
BinaryNinja currently fails to disassemble [this](https://33c3ctf.ccc.ac/uploads/tea_files-10dab306c887daacc762152fd5708b4f0e3a2ec3.tar.xz) 64-bit ELF binary from the 33C3 CTF. Everything except the entry point just displays as hexdump.

**Comment by plafosse** [comment]
There are two issues at play here. First is that we don't recognize indirect calls to got entries to be equivalent to direct calls to PLT stubs. The second is that we don't yet have a linear sweep to try to identify additional functions. Since we already have an issue for linear sweep, I'm going to modify this ticket to reflect the first issue. Thank you for submitting the issue.

<img width="291" alt="screen shot 2017-01-03 at 10 35 17 am" src="https://cloud.githubusercontent.com/assets/10556585/21612897/f3909c66-d1a0-11e6-9d3c-b2dead2f4947.png">

**Comment by plafosse** [comment]
Fixed as of 1.0.891
