### ISSUE TITLE
LLIL_CALL_STACK_ADJUST bug

### ISSUE THREAD

**Issue by Chensne** [Vector35/binaryninja-api#6094]
![image](https://github.com/user-attachments/assets/2e1de7e7-3473-4ef0-94c5-383843cabf35)

After executing call, sp cannot be adjusted automatically

**Comment by xusheng6** [comment]
Hi @Chensne , is the issue resolved?

Usually this happens because our analysis does not figure out the stack adjustment of `sub_19a5e`. As a workaround, you can set the stack adjustment of it using the "Edit Function Properties" dialog: https://docs.binary.ninja/guide/index.html#edit-function-properties-dialog

Also, I am curious on what is causing our auto-analysis to be unable to figure out the stack adjustment. Is it possible to shrae the binary with us so that we can look into it?
