### ISSUE TITLE
Magic struct feature causes variable to be renamed

### ISSUE THREAD

**Issue by SlidyBat** [Vector35/binaryninja-api#6266]
**Version and Platform (required):**
- Binary Ninja Version: 4.3.6594-dev Personal (c7f7c5e4)
- OS: macOS Sonoma
- OS Version: 14.6.1
- CPU Architecture: M1

**Bug Description:**
When using the magic struct feature (hotkey S) on a variable, as well as retyping the variable, the variable will also be renamed and has an unnecessary `_1` suffix appended.

There is also some weird behaviour where trying to remove the new name will remove the type entirely.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Create new window and paste this assembly from hex: `4889f8c3`
2. Create x64 function
3. From HLIL, click on `arg1` and then click S to create a new struct, then click "Create"
4. See that `arg1` has been renamed `arg1_1`
5. Attempt to remove the name by clicking N on `arg1_1`, removing all the text in the prompt, and clicking "Accept"
6. See that `arg1_1` has been changed back to `arg1`, but the `struct_1` type is also gone

**Expected Behavior:**
The variable should have the new type applied, without having the name changed. Clearing a variable name also shouldn't affect the type.

**Comment by psifertex** [comment]
I can't reproduce step 6 in the above. When I rename the argument after 1-4, I still see the struct applied as expected:

<img width="1392" alt="Screenshot 2024-12-20 at 08 17 57" src="https://github.com/user-attachments/assets/18962cba-aea8-4895-b028-84752a0879da" />

Can you maybe record a video or otherwise be more precise about where you're clicking to rename?

The renaming with the extra `_1` isn't really an issue since you'll notice it only does this if the variable doesn't have a user-name beforehand. It would only really be a problem if it wasn't respecting an existing name but as far as I can see, it does do that properly.

**Comment by SlidyBat** [comment]
For step 6, you need to clear the name by removing all the text, then apply.
Giving it a name doesn't show the issue.

As for the existing name, I get the suffix even if it has a user-defined name.

Even if it wasn't the case, I still find this behaviour annoying, especially for arguments since calls to the function then show `arg1_1: X`:
![CleanShot 2024-12-21 at 00 31 45@2x](https://github.com/user-attachments/assets/bd4fe0a4-3ab5-4d3a-a748-7ec03720691b)

Here is a video:
https://github.com/user-attachments/assets/b6c9e6ed-e380-4b99-be83-3eceffd0148c

The video shows:
- Applying the `struct_1` type adds the `_1` suffix
- Clearing the name resets the name but also removes the type (maybe that should be considered separate issue)
- Custom name of "test" is applied
- Applying the `struct_2` type adds the `_1` suffix again

**Comment by psifertex** [comment]
Ahh yeah, the fact that it causes the argument to be duplicated in HLIL is a good point and makes it more annoying than it would otherwise be. 

Thanks for the clarification on the renaming that I missed. I believe that's unrelated to the magic structure renaming. I'm going to split this issue into two separate ones to track the two different issues.

**Comment by xusheng6** [comment]
I have surely seen this before and I just let it slip previously -- what a shame!

For as far as I can remember, this probably only happens when the variable being operated on is a function argument (which is actually quite common!). I am not sure why exactly this is happening, will need to look into it further

**Comment by psifertex** [comment]
This is resolved by @xusheng6 in builds >= 4.3.6613 (or potentially a bit earlier). Thanks for reporting!
