### ISSUE TITLE
Anti-aliasing is terrible on Linux / Contrast issues

### ISSUE THREAD

**Issue by msjyoo** [Vector35/binaryninja-api#643]
Hello,

On a default install of Binary Ninja, I get this:
![screenshot from 2017-03-27 22-22-25](https://cloud.githubusercontent.com/assets/2097812/24353987/eb715eee-133b-11e7-892e-bd495fa0f55b.png)

Changing the anti-aliasing to any other option does not fix the problem.

Thanks!

**Comment by sekjun9878** [comment]
The contrast of option menus on brighter themes is also quite terrible...

**Comment by psifertex** [comment]
What version of Linux are you using? What screen resolution? 

The screenshot doesn't particularly bad -- specifically, the text in the menu title which is presumably window manager managed looks equivalent to the text in the menus itself. Can you take a screeenshot that includes another app that doesn't have the same problem? 

Thanks.

**Comment by sekjun9878** [comment]
They just seem slightly blurred and out of focus, just enough to put my eyes out of focus and make them confused. I think it has to do with the combination of low contrast in menu text and the slight "depth" on letters like C, T, P, and F because of grey pixels (for example, around 'C')

I'm on 1920x1200. It's hard to take a clean screenshot since Binary Ninja seems to block all PrintScreen key combos when I click on a menu item :( Still, here are two screenshots taken from both the Dark theme which I have trouble with blurry fonts and low contrast, and Classic - just low contrast, no blurs.

![screenshot from 2017-03-27 23-44-17](https://cloud.githubusercontent.com/assets/2097812/24356965/a1410070-1347-11e7-8823-c30b4145c50e.png)

First, the most noticeable difference is the incoherence in the underlining. The N and P have solid white underlines, but C(ut) and C(opy) both have "depth-ed" underlines with both white and grey. This makes both of them look blurry because there isn't enough space at 11pt to display that. Ideally, they should all be consistently solid white.

Also, I added some solid white colours to show just how bad the contrast is. Look at letters like Se(l)ect and (N)one. Those characters are almost completely grey, making them look even more blurry. If you also look at the letters (C)ut and (C)opy, you can see some grey on the inner curve of the C, giving them depth when there really shouldn't be.

For comparison, have a look at the Classic theme.

![screenshot from 2017-03-27 23-45-18](https://cloud.githubusercontent.com/assets/2097812/24356964/a13fd6fa-1347-11e7-955b-5202db5340fe.png)

On the Classic theme, all of the underlines are consistent. There is also noticeably less grey pixels on the inner curve of the (C)ut and (C)opy. The contrast issue is still there though. I've put solid black on the images for comparison. Se(l)ect and (N)one are still completely solid grey.

**Comment by psifertex** [comment]
Gotcha those demonstrate the issue more clearly, thanks. What Linux flavor is this? That will help me repo and is likely related since some distros have their own different QT libraries and themes which can impact the display. 

The double underlines are a result of the "disabled" menus it looks like. Notice the font itself is also has a drop shadow on those as well.

**Comment by sekjun9878** [comment]
This is Debian Stretch (testing) with Cinnamon desktop.

**Comment by msjyoo** [comment]
Is there any update on this issue?

**Comment by bpotchik** [comment]
The theme color selection has been fixed in build 1.1.1294-dev. Have not looked into the anti-aliasing although I know we have bumped QT versions since then. Is it any better for you now?

**Comment by plafosse** [comment]
Closing as resolved.
