### ISSUE TITLE
low_level_il call requires optimisation

### ISSUE THREAD

**Issue by robert-yates** [Vector35/binaryninja-api#748]
i know this probably isn't high priority but it shouldn't be forgotten.

obtaining only the pointers to lowlevelil requires the same amount
of time as initial analysis in python or c++ api

```
>>> for f in bv.functions:
...  llil = f.low_level_il
```

for example my ~4000 function takes about 8 minutes on my machine.
unfortunately the combination of not being able to save a
database and obtaining il pointer info means that i have to
wait 20 minutes every time i start my code which has become
impracticable.

**Comment by psifertex** [comment]
Sorry for the delay on this, but after looking more closely this is actually a wont-fix. The reason is that the IL information is not saved because of memory constraints and must be re-generated. You can change the number of cached IL functions in the `analysis.limits.cacheSize` setting, but otherwise there's no way to get any different behavior.
