### ISSUE TITLE
Incorrect decoding of instruction byte 488c20.

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#778]
![image](https://user-images.githubusercontent.com/43664/29835422-f4ef2b88-8cbf-11e7-803d-a786cc9c70ee.png)

See: https://github.com/intelxed/xed/issues/66

Despite the Intel documentation saying it accesses a qword, it doesn't actually do this.

**Comment by psifertex** [comment]
We're not planning on putting work into specific x86 instruction decoding bugs at this point since we'd rather put the effort into #193. If this instruction in particular is causing important analysis problems for you or otherwise is higher priority for any reason, let us know. Otherwise I plan to close this and we'll track the xed bug in the existing ticket.

**Comment by KyleMiles** [comment]
Resolved in 1.1.1287-dev.
