### ISSUE TITLE
code signature invalid for '/MacOS/plugins/libmspack.dylib'

### ISSUE THREAD

**Issue by GeKK0** [Vector35/binaryninja-api#800]
Binary Ninja Version: 1.1.922, 4d40ebb7
Platform: OS X Yosemite (10.10)

error log:
Plugin module '/Applications/Binary Ninja.app/Contents/MacOS/plugins/libmspack.dylib' failed to load
dlerror() reports: dlopen(/Applications/Binary Ninja.app/Contents/MacOS/plugins/libmspack.dylib, 5): no suitable image found.  Did find:
	/Applications/Binary Ninja.app/Contents/MacOS/plugins/libmspack.dylib: code signature invalid for '/Applications/Binary Ninja.app/Contents/MacOS/plugins/libmspack.dylib'

**Comment by psifertex** [comment]
One of two things -- either a corrupted download (try download a fresh copy from https://binary.ninja/recover/  and reinstalling) or it's a problem with the old version of OS X (which we don't test on).

In the past, there was a problem running older OS X versions because of some linking issues, but that's not what this sounds like. Still, if you try running `otool -L ` on the libbinaryninjacore.dylib and look for any errors that might help. 

That said,

**Comment by GeKK0** [comment]
No luck with fresh install.  Ill update OS X later.

Thanks

**Comment by GeKK0** [comment]
Updating to OS X 10.13 fixed this issue
