### ISSUE TITLE
Graph View breaks on symbol rename randomly

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#802]
I haven't been able to reproduce it reliably (sorry), but sometimes when I rename a symbol in graph view, the entire view will reposition itself to (0,0) and won't respond to further interaction. This most recent time it happened in Disassembly view, but I am pretty sure it's happened to me in MLIL view as well.

**Comment by psifertex** [comment]
Yeah, there's a few focusing issues we haven't focused on (get it, get it?!) because we're waiting for the 1.2 refactor as they'll likely go away. Definitely aware of it. Now that I look at it, I don't think we have an overall UI refactor ticket so I'm going to create it and link this one as something to check on when we're working on it. 

Related to #803

**Comment by bpotchik** [comment]
I believe this to be fix due to recent UI improvements. Please reopen if noticed again.

**Comment by D0ntPanic** [comment]
A new repro was found and the underlying issue has been fixed in build 1477
