### ISSUE TITLE
Support for timeouts in update_analysis_and_wait()

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#813]
Would like to have an optional timeout parameter to update_analysis_and_wait() that allows for it to return after a specified amount of time. Useful when doing batch analysis and you don't mind skipping files that takes a lot of time to process or hangs during analysis.

**Comment by bpotchik** [comment]
There is the ability to register a callback for analysis completion. Then just call update_analysis which will not block. That thread can later signal to abort analysis after some time has elapsed. I believe after analysis is aborted the analysis results are perhaps in an incomplete/inconsistent state. If we do add this, we need to make it clear what's expected after a call to update_analysis_and_wait() returns because of timeout. Either we rollback analysis artifacts so everything is consistent, or as it currently works analysis is aborted and the only valid action is to close the database without save.

**Comment by psifertex** [comment]
Also, another fix for this is probably the features we're planning in #908

**Comment by bpotchik** [comment]
I think the enhancements in #908 may help with this. These were added in build 1.1-1236-dev. See comments in #908 for more info.
