### ISSUE TITLE
RFE: Do not delete user created files in the installation directory when upgrading

### ISSUE THREAD

**Issue by PeterBortas** [Vector35/binaryninja-api#816]
Currently the Binary Ninja automatic updater will delete all user created files when an upgrade is performed. This is not cosidered good practise on Linux, but will also come as a surprice for Mac and Windows users that are used to copying 3rd party plugins or developing their own in the application  plugin directory.

Discussed this in Slack, and I agree that a blanket warning on each upgrade is useless, that's just another thing to click through without thinking. I understand that this would also not be easily done with the current upgrade method. So place it apropriately low on the TODO, but keep in mind that sooner or later someone without a backup of their work will be hit by this.

I'll leave this here just in case someone wants to do it the kludgey way and be done with it for now:

- Make a backup directory with all files not found in the new install. This is doable regardless of current upgrade system. Downsides: Would not differentiate between user files and application files that have been removed, and it would then probably just be spammy to tell the user every time this happends. Would also temporaryly double the space used in the naive implementation.

**Comment by psifertex** [comment]
Our intended fix is to white-list built-in plugins and types that we ship to prevent any other files from being put there from loading. This will prevent the situation from happening because users will realize their changes aren't taking place and will find the correct location. We will not change the base-behavior of removing all old files because this will break things like notarization on MacOS.

**Comment by plafosse** [comment]
Our solution to this is that we refuse to load user plugins from the Binary Ninja core plugins directory.
