### ISSUE TITLE
Menu on OS X 10.12.6 (Sierra) contains duplicate items

### ISSUE THREAD

**Issue by soen-vanned** [Vector35/binaryninja-api#894]
The "Check For Updates" menu item is repeated twice.
<img width="235" alt="screen shot 2017-12-23 at 1 15 11 pm" src="https://user-images.githubusercontent.com/1918848/34322398-605413ba-e7e3-11e7-8de5-7764d879b5ac.png">

**Comment by psifertex** [comment]
This is a known bug that happened when we moved the updates to the Mac specific location as opposed to help and is ultimately a QT bug though we could work around it but haven't tried messing with it since we're evaluating UI changes anyway. . 

Closing this one now as there's another bug tracking it. 

Also, for what it's worth it only happens when you have multiple windows open at the same time.
