### ISSUE TITLE
UI papercuts

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#898]
Per discussion on Twitter I've been asked to file a single metabug for UI papercuts, so here it is. UI wishlist:
  - [x] A context menu item to add new enumerants to a enum
  - [x] A context menu item to change the value of an enumerant in an enum
  - [ ] A context menu item in the code view to navigate to the type definition, when a type is highlighted under cursor
  - [ ] A context menu item to add and remove undefined bytes in a structure (such that fields can be shifted back and forth after being defined)
  - [x] A context menu item to undefine the current function in linear disassembly view

**Comment by plafosse** [comment]
Can you be more specific here?

**Comment by joshwatson** [comment]
Are you talking about `types.Enumeration`?

**Comment by whitequark** [comment]
I mean in the GUI, in the Types pane. For structs, I have an "Append Field..." command, but for enums, I can only rename and undefine variants, not add new ones.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1317-dev.

You can navigate to specific types via double click on type tokens or clicking on a variable and hitting 't'. 't' will take you to types view regardless if a selected type exists or not. This was not added as a context menu item so I did not check the box above.

As for addition/removal of undefined bytes or shifting fields in a struct select and copy now work in types view.

**Comment by whitequark** [comment]
Sweet!
