### ISSUE TITLE
Registering a new plugin with the same name should replace the old one

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#901]
This way, testing new plugins can be as simple as `reload(plugin_name)` in the console.

**Comment by joshwatson** [comment]
Related: #781

**Comment by psifertex** [comment]
Equivalent to #50 so I'm going to close it and we'll keep using that to track it instead.

**Comment by psifertex** [comment]
As an update, I thought about it some more and this is a bit different than #50 since we can implement this without the ability to directly reload an entire plugin on disk. Given that, we've modified the registration APIs as of 1040 so that using the same name does indeed replace it, but we still don't have the ability requested in #50 to reload an entire plugin on disk.
