### ISSUE TITLE
x64: invalid instruction is recognized as valid

### ISSUE THREAD

**Issue by mossberg** [Vector35/binaryninja-api#907]
In this binary, 0x1e is recognized as a `push ds`, but various other sources say it's invalid.

![image](https://user-images.githubusercontent.com/2467355/34851278-4c61de1e-f6f7-11e7-8ea9-f04f11c8691e.png)

![image](https://user-images.githubusercontent.com/2467355/34851296-64736c3e-f6f7-11e7-970c-cf480f5311b0.png)

[sshd-585c3-17.zip](https://github.com/Vector35/binaryninja-api/files/1624389/sshd-585c3-17.zip)

**Comment by psifertex** [comment]
Good catch. True for all of 0x06, 0x07, 0x0e, 0x16, 0x17, 0x1e, 0x1f as well.

**Comment by psifertex** [comment]
We're not planning on putting work into specific x86 instruction decoding bugs at this point since we'd rather put the effort into #193. If this instruction in particular is causing important analysis problems for you or otherwise is higher priority for any reason, let us know. Otherwise I plan to close this and we'll track the xed bug in the existing ticket.

**Comment by KyleMiles** [comment]
Resolved in 1.1.1287.
