### ISSUE TITLE
data flow idiom: X + X == X << 1

### ISSUE THREAD

**Issue by pmackinlay** [Vector35/binaryninja-api#944]
Binary Ninja Version: 1.1.1057-dev Personal, 7bfb2b78
Platform: Windows 10 (10.0)

The architecture I'm working with uses a specific idiom when computing an offset into a branch table which BN does not currently recognise. The idiom is simply to take the original branch table index value in a register, and then add the register to itself twice, giving ```value << 2```. In case it's not completely clear, this multiplies the index by 4 to give the correct offset into an array of 32 bit addresses.

Currently, I have an LLIL hack implemented which produces a left shift when the source and destination of the add instruction are the same register, but it seems to me that BN should recognise that X + X == X << 1 as a built-in idiom.

**Comment by psifertex** [comment]
Can you replicate this issue on other architectures? This should work fine and is likely an issue with your lifting rather than with the core data flow. You can test it using the assembler to create a small snippet for another platform and see if it calculates the value appropriately. I'll test it later when I'm not on my phone as well.

**Comment by psifertex** [comment]
Hmm, never mind. I just caught up on slack. Looks like rss already tested it. Thanks for the report!

**Comment by bpotchik** [comment]
Fixed in build 1.1.1061-dev.

**Comment by pmackinlay** [comment]
It seems this fix may have regressed, I'm not sure when, but it shows the old behaviour in 1.1.1143-dev Personal.

**Comment by bpotchik** [comment]
This was fixed for ranges but not InSetOfValues. Adding support now.
