### ISSUE TITLE
Extra temp variables generated

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#954]
I see a lot of extra temp variables generated for no apparent reason in the last few dev builds, for example:

![scrot](https://ptpb.pw/-4a7)

```nasm
global _start
section .text

_start:
    mov rdi, 1
    mov rsi, 2
    call foo

exit:
    mov rax, 60
    xor rdi, rdi
    syscall

foo:
    sub rdi, rsi
    jo bkpt

    retn

bkpt:
    int3
```

**Comment by rssor** [comment]
There should be a significant reduction in temporary variables emitted due to flag generation as of build 1.1.1103-dev.

What used to look like this:
![before](https://user-images.githubusercontent.com/34997787/37379297-5170f63c-2709-11e8-87e1-4986e563d4ef.png)

Now looks like this:
![after](https://user-images.githubusercontent.com/34997787/37379316-67be3544-2709-11e8-9782-19fbe7725797.png)


The particular case pictured here is unaffected as flag generation occurs *after* the instruction that sets flags, meaning `rdi` needs to be preserved in a temp var.

**Comment by nshp** [comment]
Turns out the example I gave was off for other reasons, but the underlying issue seems fixed.
Thanks!
