### ISSUE TITLE
Branch dependence dataflow broken in SSA?

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#961]
I'm not 100% sure where the problem comes from here, but:
`var_40` is assigned 0:
![a](https://ptpb.pw/TZb7)

is `var_40 == 0`? no? call it.
At the callsite in LLIL, hovering `rax` says it is UndeterminedValue. In LLIL-SSA, however, it claims `rax#18` is 0.
![b](https://ptpb.pw/uV8l)

The result is MLIL thinks this is a call to 0 (... a.k.a. incorrectly, the ELF header):
![c](https://ptpb.pw/cc4N)

Maybe that whole basic block should actually be optimized out in MLIL, as it's under an impossible condition (assuming nobody's writing into our stack from another thread or something nasty).

This example is from libbinaryninjacore.so (build 69916358).

**Comment by rssor** [comment]
MLIL is not meant to remove opaque predicates, especially since they are often symptoms of not having enough type information inside the function yet.

This isn't a dataflow bug, it's just dataflow not having enough information yet to realize it's not an opaque predicate. The likely case when running into situations like this is that the stack variable is actually a member of a larger struct passed to another function -- if binaryninja isn't aware of the size of this struct on the stack, it's unable to realize that `var_40` had been aliased earlier in the function (when the start address of the struct would have been calculated).

Since analysis had no way to realize that `var_40` had likely been aliased earlier in the function the contents of `var_40` haven't been tied to the current memory version, so dataflow is providing a ConstantValue of 0 where it shouldn't be.

Creating a variable on the stack of the appropriate size would take care of the pictured opaque predicate, as the aliased vars would be recognized and tied to current memory version correctly.
